# Maryland Infrastructure Analysis

## Import Statements

In [8]:
import pandas as pd
from bs4 import BeautifulSoup as bs
import lxml
import requests
import json

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

import numpy as np
import math

# !pip install area
from area import area

# !pip install sodapy
from sodapy import Socrata

from sklearn.cluster import KMeans

import itertools

import matplotlib.pyplot as plt 
import matplotlib.cm as cm
import matplotlib.colors as colors
import matplotlib.dates as mdates

import folium
from geopy.geocoders import Nominatim # convert an address into latitude and longitude values

from shapely.geometry import Point
from shapely.geometry.polygon import Polygon

# Import BeautifulSoup
from bs4 import BeautifulSoup

import sys
import os
from pathlib import Path

from statsmodels.tsa.statespace.sarimax import SARIMAX
from statsmodels.tsa.arima.model import ARIMA

# Add the parent directory (main_directory) to the Python path
sys.path.append(str(Path("..")))

# Import the variable from the keys.py file in the subdirectory2 folder
from constants import * #import private API credentials

from llm_config import LLMManager, ModelLister

print("Imports complete")

Imports complete

## Set Save Parameters

### Set path to save figures and data

In [9]:
from pathlib import Path

current_directory = Path.cwd()
output_directory = current_directory.parent / 'data'
output_directory = output_directory.resolve()

print(output_directory)

C:\Users\ChrisPeoples\OneDrive - Peoples Partners and Associates, LLC\PP&A Working Directory\70_Studies_and_Reports\2023_EV_Infrastructure_Trends\data

### Function to save figures and data

In [10]:
def save_fig(fig_id, tight_layout=True, fig_extension="png", resolution=300):
    path = os.path.join(output_directory, fig_id + "." + fig_extension)
    print("Saving figure", fig_id)
    if tight_layout:
        plt.tight_layout()
    plt.savefig(path, format=fig_extension, dpi=resolution)

# Save data to csv
def save_data(data, filename):
    filetype = ".csv"
    filename = filename + filetype
    path = os.path.join(output_directory, filename)
    print("Saving data", filename)
    data.to_csv(path)
    print("File saved at " + path + "/" + filename)

print("Done")

Done

## Data Prep and ETL

### GDP | USA by State
pull GDP data by U.S. state, you can use the Bureau of Economic Analysis (BEA) API. The BEA's API is designed for developers and analysts to search, retrieve, and analyze data.: <a href="https://www.bea.gov/resources/for-developers">BEA Developer Site</a>

In [11]:
def get_data_from_bea(api_key, datasetname, tablename, linecode, year, geofips):
    base_url = 'https://apps.bea.gov/api/data'
    params = {
        'UserID': api_key,
        'method': 'GetData',
        'datasetname': datasetname,
        'tablename': tablename,
        'linecode': linecode,
        'year': year,
        'GeoFips': geofips,
        'ResultFormat': 'json'
    }
    response = requests.get(base_url, params=params)
    data = response.json()
    return data

api_key = BEA_KEY
datasetname = 'Regional'
tablename = 'SASUMMARY'  # GDP by state
linecode = '4'  # Line code for GDP
year = 'ALL'  # Year of the data
geofips = 'STATE'  # GeoFips code for all states

data = get_data_from_bea(api_key, datasetname, tablename, linecode, year, geofips)

# Extract the data part of the JSON
data_values = data['BEAAPI']['Results']['Data']

# Convert the data to a DataFrame
df = pd.DataFrame(data_values)

# Remove commas from the 'DataValue' column
df['DataValue'] = df['DataValue'].str.replace(',', '')

# Convert the 'DataValue' column to numeric
df['DataValue'] = pd.to_numeric(df['DataValue'], errors='coerce')

# List of all U.S. states including District of Columbia
states = ['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'District of Columbia', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming']

# Filter the DataFrame to include only the states
df = df[df['GeoName'].isin(states)]

# Pivot the DataFrame to have 'GeoName' as index, 'TimePeriod' as columns, and 'DataValue' as values
df_pivot = df.pivot(index='GeoName', columns='TimePeriod', values='DataValue')

# Print the pivoted DataFrame
state_gdp = df_pivot

state_gdp.head()

TimePeriod,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
GeoName,,,,,,,,,,,,,,,,,,,,,,,,,
Alabama,110212.0,115680.1,119851.7,122915.5,127505.0,134152.6,147715.2,158846.8,166469.0,172975.2,174526.3,170930.9,177249.2,183916.6,189245.5,194786.9,197406.9,202372.4,207368.4,214606.3,223859.3,231561.9,230892.1,254109.7,277817.5
Alaska,24227.5,24744.3,26806.6,28494.1,29756.8,32037.9,35302.4,40356.6,45094.1,49583.7,55122.5,49957.8,53331.6,56896.3,58283.6,57247.7,56484.9,51490.9,50727.7,53301.5,54899.6,54728.2,50475.2,57349.4,63618.0
Arizona,143302.6,155755.8,165110.7,171909.6,180522.3,193634.9,206541.1,227915.9,245957.0,261392.0,262926.0,246424.3,251153.0,260915.7,271440.0,278591.6,287666.6,299393.3,313081.4,332001.8,351879.5,372393.5,382072.3,420026.7,458949.8
Arkansas,62396.7,66811.3,68678.5,70616.7,74113.9,78695.1,85199.6,90887.7,95875.1,98381.6,99706.8,97508.1,101486.5,105768.1,108492.1,113227.3,116139.4,117786.8,119152.4,122466.7,127535.7,131578.3,133969.1,148676.1,165220.6
California,1147520.4,1241899.7,1356975.4,1375761.3,1418429.6,1497918.7,1588177.4,1698560.4,1812210.0,1898902.0,1944695.3,1890165.9,1954092.7,2023500.0,2113096.4,2220389.9,2335286.5,2473555.9,2569634.0,2728743.1,2897200.7,3042694.1,3020173.4,3373240.7,3598102.7

In [69]:
# Save dataframe using the save_data function
save_data(state_gdp, 'USA_State_GDP')

### Census Population Data | USA by State
<div>Current census data is from 2019</div>
<div>Data is pulled from <span><a href="https://www.census.gov/data/developers/guidance/api-user-guide.html">Census.gov</a></span></div>

In [13]:
def get_census_data(year):
    # Define the base URL for the API endpoint
    if year == 2019:
        # Define the base URL for the API endpoint
        base_url = f"https://api.census.gov/data/2019/pep/population"

        # Define the parameters for the API request
        params = {
            "get": "NAME,POP",
            "for": "state:*",
            "key": CENSUS_KEY
        }
    else:
        # Define the base URL for the API endpoint
        base_url = f"https://api.census.gov/data/{year}/acs/acs1?get=NAME,B01001_001E&for=state:*"

        # Define the parameters for the API request
        params = {
            # "get": "NAME,b01001_001E",
            # "for": "state:*",
            "key": CENSUS_KEY
        }

    # Send a GET request to the API endpoint
    response = requests.get(base_url, params=params)

    print(response.status_code)
    print(response.text)

    # Convert the response to a DataFrame
    data = response.json()
    df = pd.DataFrame(data[1:], columns=data[0])
    df['Year'] = year  # Add a column for the year

    return df

# Initialize an empty DataFrame to store all the data
hist_population = pd.DataFrame()

# Loop through the years 2010 to 2019
for year in range(2010, 2020):
    # Get the data for the current year
    year_data = get_census_data(year)
    # Append the data for the current year to the all_data DataFrame

    hist_population = pd.concat([hist_population, year_data])

# Reset the index of the all_data DataFrame
hist_population.reset_index(drop=True, inplace=True)

# Replace NaN values in the POP column with values from the B01001_001E column
hist_population['POP'] = hist_population['POP'].fillna(hist_population['B01001_001E'])

# Drop the B01001_001E column
hist_population.drop(columns='B01001_001E', inplace=True)

# Convert POP values to integers
hist_population['POP'] = hist_population['POP'].astype(int)

# Pivot Data to have 'NAME' as index, 'Year' as columns, and 'POP' as values
hist_population = hist_population.pivot(index='NAME', columns='Year', values='POP')

print(hist_population)

200
[["NAME","B01001_001E","state"],
["Alabama","4785298","01"],
["Alaska","713985","02"],
["Arizona","6413737","04"],
["Arkansas","2921606","05"],
["California","37349363","06"],
["Colorado","5049071","08"],
["Connecticut","3577073","09"],
["Delaware","899769","10"],
["District of Columbia","604453","11"],
["Florida","18843326","12"],
["Georgia","9712587","13"],
["Hawaii","1363621","15"],
["Idaho","1571450","16"],
["Illinois","12843166","17"],
["Indiana","6490621","18"],
["Iowa","3049883","19"],
["Kansas","2859169","20"],
["Kentucky","4346266","21"],
["Louisiana","4544228","22"],
["Maine","1327567","23"],
["Maryland","5785982","24"],
["Massachusetts","6557254","25"],
["Michigan","9877574","26"],
["Minnesota","5310584","27"],
["Mississippi","2970036","28"],
["Missouri","5996231","29"],
["Montana","990898","30"],
["Nebraska","1830429","31"],
["Nevada","2704642","32"],
["New Hampshire","1316759","33"],
["New Jersey","8801624","34"],
["New Mexico","2065932","35"],
["New York","19392283","36"],
["North Carolina","9561558","37"],
["North Dakota","674499","38"],
["Ohio","11536182","39"],
["Oklahoma","3761702","40"],
["Oregon","3838957","41"],
["Pennsylvania","12709630","42"],
["Rhode Island","1052886","44"],
["South Carolina","4636312","45"],
["South Dakota","816463","46"],
["Tennessee","6356897","47"],
["Texas","25257114","48"],
["Utah","2776469","49"],
["Vermont","625960","50"],
["Virginia","8024617","51"],
["Washington","6744496","53"],
["West Virginia","1853973","54"],
["Wisconsin","5691047","55"],
["Wyoming","564460","56"],
["Puerto Rico","3722133","72"]]
200
[["NAME","B01001_001E","state"],
["Alabama","4802740","01"],
["Alaska","722718","02"],
["Arizona","6482505","04"],
["Arkansas","2937979","05"],
["California","37691912","06"],
["Colorado","5116796","08"],
["Connecticut","3580709","09"],
["Delaware","907135","10"],
["District of Columbia","617996","11"],
["Florida","19057542","12"],
["Georgia","9815210","13"],
["Hawaii","1374810","15"],
["Idaho","1584985","16"],
["Illinois","12869259","17"],
["Indiana","6516922","18"],
["Iowa","3062309","19"],
["Kansas","2871238","20"],
["Kentucky","4369356","21"],
["Louisiana","4574836","22"],
["Maine","1328188","23"],
["Maryland","5828289","24"],
["Massachusetts","6587536","25"],
["Michigan","9876187","26"],
["Minnesota","5344861","27"],
["Mississippi","2978512","28"],
["Missouri","6010688","29"],
["Montana","998199","30"],
["Nebraska","1842641","31"],
["Nevada","2723322","32"],
["New Hampshire","1318194","33"],
["New Jersey","8821155","34"],
["New Mexico","2082224","35"],
["New York","19465197","36"],
["North Carolina","9656401","37"],
["North Dakota","683932","38"],
["Ohio","11544951","39"],
["Oklahoma","3791508","40"],
["Oregon","3871859","41"],
["Pennsylvania","12742886","42"],
["Rhode Island","1051302","44"],
["South Carolina","4679230","45"],
["South Dakota","824082","46"],
["Tennessee","6403353","47"],
["Texas","25674681","48"],
["Utah","2817222","49"],
["Vermont","626431","50"],
["Virginia","8096604","51"],
["Washington","6830038","53"],
["West Virginia","1855364","54"],
["Wisconsin","5711767","55"],
["Wyoming","568158","56"],
["Puerto Rico","3706690","72"]]
200
[["NAME","B01001_001E","state"],
["Alabama","4822023","01"],
["Alaska","731449","02"],
["Arizona","6553255","04"],
["Arkansas","2949131","05"],
["California","38041430","06"],
["Colorado","5187582","08"],
["Delaware","917092","10"],
["District of Columbia","632323","11"],
["Connecticut","3590347","09"],
["Florida","19317568","12"],
["Georgia","9919945","13"],
["Idaho","1595728","16"],
["Hawaii","1392313","15"],
["Illinois","12875255","17"],
["Indiana","6537334","18"],
["Iowa","3074186","19"],
["Kansas","2885905","20"],
["Kentucky","4380415","21"],
["Louisiana","4601893","22"],
["Maine","1329192","23"],
["Maryland","5884563","24"],
["Massachusetts","6646144","25"],
["Michigan","9883360","26"],
["Minnesota","5379139","27"],
["Mississippi","2984926","28"],
["Missouri","6021988","29"],
["Montana","1005141","30"],
["Nebraska","1855525","31"],
["Nevada","2758931","32"],
["New Hampshire","1320718","33"],
["New Jersey","8864590","34"],
["New Mexico","2085538","35"],
["New York","19570261","36"],
["North Carolina","9752073","37"],
["North Dakota","699628","38"],
["Ohio","11544225","39"],
["Oklahoma","3814820","40"],
["Oregon","3899353","41"],
["Pennsylvania","12763536","42"],
["Rhode Island","1050292","44"],
["South Carolina","4723723","45"],
["South Dakota","833354","46"],
["Tennessee","6456243","47"],
["Texas","26059203","48"],
["Vermont","626011","50"],
["Utah","2855287","49"],
["Virginia","8185867","51"],
["Washington","6897012","53"],
["West Virginia","1855413","54"],
["Wisconsin","5726398","55"],
["Wyoming","576412","56"],
["Puerto Rico","3667084","72"]]
200
[["NAME","B01001_001E","state"],
["Mississippi","2991207","28"],
["Missouri","6044171","29"],
["Montana","1015165","30"],
["Nebraska","1868516","31"],
["Nevada","2790136","32"],
["New Hampshire","1323459","33"],
["New Jersey","8899339","34"],
["New Mexico","2085287","35"],
["New York","19651127","36"],
["North Carolina","9848060","37"],
["North Dakota","723393","38"],
["Ohio","11570808","39"],
["Oklahoma","3850568","40"],
["Oregon","3930065","41"],
["Pennsylvania","12773801","42"],
["Rhode Island","1051511","44"],
["South Carolina","4774839","45"],
["South Dakota","844877","46"],
["Tennessee","6495978","47"],
["Texas","26448193","48"],
["Vermont","626630","50"],
["Utah","2900872","49"],
["Virginia","8260405","51"],
["Washington","6971406","53"],
["West Virginia","1854304","54"],
["Wisconsin","5742713","55"],
["Wyoming","582658","56"],
["Puerto Rico","3615086","72"],
["Alabama","4833722","01"],
["Alaska","735132","02"],
["Arizona","6626624","04"],
["Arkansas","2959373","05"],
["California","38332521","06"],
["Colorado","5268367","08"],
["Delaware","925749","10"],
["District of Columbia","646449","11"],
["Connecticut","3596080","09"],
["Florida","19552860","12"],
["Georgia","9992167","13"],
["Idaho","1612136","16"],
["Hawaii","1404054","15"],
["Illinois","12882135","17"],
["Indiana","6570902","18"],
["Iowa","3090416","19"],
["Kansas","2893957","20"],
["Kentucky","4395295","21"],
["Louisiana","4625470","22"],
["Maine","1328302","23"],
["Maryland","5928814","24"],
["Massachusetts","6692824","25"],
["Michigan","9895622","26"],
["Minnesota","5420380","27"]]
200
[["NAME","B01001_001E","state"],
["Alabama","4849377","01"],
["Alaska","736732","02"],
["Arizona","6731484","04"],
["Arkansas","2966369","05"],
["California","38802500","06"],
["Colorado","5355866","08"],
["Delaware","935614","10"],
["District of Columbia","658893","11"],
["Connecticut","3596677","09"],
["Florida","19893297","12"],
["Georgia","10097343","13"],
["Idaho","1634464","16"],
["Hawaii","1419561","15"],
["Illinois","12880580","17"],
["Indiana","6596855","18"],
["Iowa","3107126","19"],
["Kansas","2904021","20"],
["Kentucky","4413457","21"],
["Louisiana","4649676","22"],
["Maine","1330089","23"],
["Maryland","5976407","24"],
["Massachusetts","6745408","25"],
["Michigan","9909877","26"],
["Minnesota","5457173","27"],
["Mississippi","2994079","28"],
["Missouri","6063589","29"],
["Montana","1023579","30"],
["Nebraska","1881503","31"],
["Nevada","2839099","32"],
["New Hampshire","1326813","33"],
["New Jersey","8938175","34"],
["New Mexico","2085572","35"],
["New York","19746227","36"],
["North Carolina","9943964","37"],
["North Dakota","739482","38"],
["Ohio","11594163","39"],
["Oklahoma","3878051","40"],
["Oregon","3970239","41"],
["Pennsylvania","12787209","42"],
["Rhode Island","1055173","44"],
["South Carolina","4832482","45"],
["South Dakota","853175","46"],
["Tennessee","6549352","47"],
["Texas","26956958","48"],
["Vermont","626562","50"],
["Utah","2942902","49"],
["Virginia","8326289","51"],
["Washington","7061530","53"],
["West Virginia","1850326","54"],
["Wisconsin","5757564","55"],
["Wyoming","584153","56"],
["Puerto Rico","3548397","72"]]
200
[["NAME","B01001_001E","state"],
["Mississippi","2992333","28"],
["Missouri","6083672","29"],
["Montana","1032949","30"],
["Nebraska","1896190","31"],
["Nevada","2890845","32"],
["New Hampshire","1330608","33"],
["New Jersey","8958013","34"],
["New Mexico","2085109","35"],
["New York","19795791","36"],
["North Carolina","10042802","37"],
["North Dakota","756928","38"],
["Ohio","11613423","39"],
["Oklahoma","3911338","40"],
["Oregon","4028977","41"],
["Pennsylvania","12802503","42"],
["Rhode Island","1056298","44"],
["South Carolina","4896146","45"],
["South Dakota","858469","46"],
["Tennessee","6600299","47"],
["Texas","27469114","48"],
["Vermont","626042","50"],
["Utah","2995919","49"],
["Virginia","8382993","51"],
["Washington","7170351","53"],
["West Virginia","1844128","54"],
["Wisconsin","5771337","55"],
["Wyoming","586107","56"],
["Puerto Rico","3474182","72"],
["Alabama","4858979","01"],
["Alaska","738432","02"],
["Arizona","6828065","04"],
["Arkansas","2978204","05"],
["California","39144818","06"],
["Colorado","5456574","08"],
["Delaware","945934","10"],
["District of Columbia","672228","11"],
["Connecticut","3590886","09"],
["Florida","20271272","12"],
["Georgia","10214860","13"],
["Idaho","1654930","16"],
["Hawaii","1431603","15"],
["Illinois","12859995","17"],
["Indiana","6619680","18"],
["Iowa","3123899","19"],
["Kansas","2911641","20"],
["Kentucky","4425092","21"],
["Louisiana","4670724","22"],
["Maine","1329328","23"],
["Maryland","6006401","24"],
["Massachusetts","6794422","25"],
["Michigan","9922576","26"],
["Minnesota","5489594","27"]]
200
[["NAME","B01001_001E","state"],
["Mississippi","2988726","28"],
["Missouri","6093000","29"],
["Montana","1042520","30"],
["Nebraska","1907116","31"],
["Nevada","2940058","32"],
["New Hampshire","1334795","33"],
["New Jersey","8944469","34"],
["New Mexico","2081015","35"],
["New York","19745289","36"],
["North Carolina","10146788","37"],
["North Dakota","757953","38"],
["Ohio","11614373","39"],
["Oklahoma","3923561","40"],
["Oregon","4093465","41"],
["Pennsylvania","12784227","42"],
["Rhode Island","1056426","44"],
["South Carolina","4961119","45"],
["South Dakota","865454","46"],
["Tennessee","6651194","47"],
["Texas","27862596","48"],
["Vermont","624594","50"],
["Utah","3051217","49"],
["Virginia","8411808","51"],
["Washington","7288000","53"],
["West Virginia","1831102","54"],
["Wisconsin","5778709","55"],
["Wyoming","585501","56"],
["Puerto Rico","3411307","72"],
["Alabama","4863300","01"],
["Alaska","741894","02"],
["Arizona","6931071","04"],
["Arkansas","2988248","05"],
["California","39250017","06"],
["Colorado","5540545","08"],
["Delaware","952065","10"],
["District of Columbia","681170","11"],
["Connecticut","3576452","09"],
["Florida","20612439","12"],
["Georgia","10310371","13"],
["Idaho","1683140","16"],
["Hawaii","1428557","15"],
["Illinois","12801539","17"],
["Indiana","6633053","18"],
["Iowa","3134693","19"],
["Kansas","2907289","20"],
["Kentucky","4436974","21"],
["Louisiana","4681666","22"],
["Maine","1331479","23"],
["Maryland","6016447","24"],
["Massachusetts","6811779","25"],
["Michigan","9928300","26"],
["Minnesota","5519952","27"]]
200
[["NAME","B01001_001E","state"],
["Mississippi","2984100","28"],
["Missouri","6113532","29"],
["Montana","1050493","30"],
["Nebraska","1920076","31"],
["Nevada","2998039","32"],
["New Hampshire","1342795","33"],
["New Jersey","9005644","34"],
["New Mexico","2088070","35"],
["New York","19849399","36"],
["North Carolina","10273419","37"],
["North Dakota","755393","38"],
["Ohio","11658609","39"],
["Oklahoma","3930864","40"],
["Oregon","4142776","41"],
["Pennsylvania","12805537","42"],
["Rhode Island","1059639","44"],
["South Carolina","5024369","45"],
["South Dakota","869666","46"],
["Tennessee","6715984","47"],
["Texas","28304596","48"],
["Vermont","623657","50"],
["Utah","3101833","49"],
["Virginia","8470020","51"],
["Washington","7405743","53"],
["West Virginia","1815857","54"],
["Wisconsin","5795483","55"],
["Wyoming","579315","56"],
["Puerto Rico","3337177","72"],
["Alabama","4874747","01"],
["Alaska","739795","02"],
["Arizona","7016270","04"],
["Arkansas","3004279","05"],
["California","39536653","06"],
["Colorado","5607154","08"],
["Delaware","961939","10"],
["District of Columbia","693972","11"],
["Connecticut","3588184","09"],
["Florida","20984400","12"],
["Georgia","10429379","13"],
["Idaho","1716943","16"],
["Hawaii","1427538","15"],
["Illinois","12802023","17"],
["Indiana","6666818","18"],
["Iowa","3145711","19"],
["Kansas","2913123","20"],
["Kentucky","4454189","21"],
["Louisiana","4684333","22"],
["Maine","1335907","23"],
["Maryland","6052177","24"],
["Massachusetts","6859819","25"],
["Michigan","9962311","26"],
["Minnesota","5576606","27"]]
200
[["NAME","B01001_001E","state"],
["Alabama","4887871","01"],
["Alaska","737438","02"],
["Arizona","7171646","04"],
["Arkansas","3013825","05"],
["California","39557045","06"],
["Colorado","5695564","08"],
["Delaware","967171","10"],
["District of Columbia","702455","11"],
["Connecticut","3572665","09"],
["Florida","21299325","12"],
["Georgia","10519475","13"],
["Idaho","1754208","16"],
["Hawaii","1420491","15"],
["Illinois","12741080","17"],
["Indiana","6691878","18"],
["Iowa","3156145","19"],
["Kansas","2911510","20"],
["Kentucky","4468402","21"],
["Louisiana","4659978","22"],
["Maine","1338404","23"],
["Maryland","6042718","24"],
["Massachusetts","6902149","25"],
["Michigan","9995915","26"],
["Minnesota","5611179","27"],
["Wisconsin","5813568","55"],
["Wyoming","577737","56"],
["Puerto Rico","3195153","72"],
["Mississippi","2986530","28"],
["Missouri","6126452","29"],
["Montana","1062305","30"],
["Nebraska","1929268","31"],
["Nevada","3034392","32"],
["New Hampshire","1356458","33"],
["New Jersey","8908520","34"],
["New Mexico","2095428","35"],
["New York","19542209","36"],
["North Carolina","10383620","37"],
["North Dakota","760077","38"],
["Ohio","11689442","39"],
["Oklahoma","3943079","40"],
["Oregon","4190713","41"],
["Pennsylvania","12807060","42"],
["Rhode Island","1057315","44"],
["South Carolina","5084127","45"],
["South Dakota","882235","46"],
["Tennessee","6770010","47"],
["Texas","28701845","48"],
["Vermont","626299","50"],
["Utah","3161105","49"],
["Virginia","8517685","51"],
["Washington","7535591","53"],
["West Virginia","1805832","54"]]
200
[["NAME","POP","state"],
["Alabama","4903185","01"],
["Alaska","731545","02"],
["Arizona","7278717","04"],
["Arkansas","3017804","05"],
["California","39512223","06"],
["Colorado","5758736","08"],
["Delaware","973764","10"],
["District of Columbia","705749","11"],
["Connecticut","3565287","09"],
["Florida","21477737","12"],
["Georgia","10617423","13"],
["Idaho","1787065","16"],
["Hawaii","1415872","15"],
["Illinois","12671821","17"],
["Indiana","6732219","18"],
["Iowa","3155070","19"],
["Kansas","2913314","20"],
["Kentucky","4467673","21"],
["Louisiana","4648794","22"],
["Maine","1344212","23"],
["Maryland","6045680","24"],
["Massachusetts","6892503","25"],
["Michigan","9986857","26"],
["Minnesota","5639632","27"],
["Nebraska","1934408","31"],
["Mississippi","2976149","28"],
["Missouri","6137428","29"],
["Montana","1068778","30"],
["Nevada","3080156","32"],
["New Hampshire","1359711","33"],
["New Jersey","8882190","34"],
["New Mexico","2096829","35"],
["New York","19453561","36"],
["North Carolina","10488084","37"],
["North Dakota","762062","38"],
["Ohio","11689100","39"],
["Oklahoma","3956971","40"],
["Oregon","4217737","41"],
["Pennsylvania","12801989","42"],
["Tennessee","6829174","47"],
["Rhode Island","1059361","44"],
["South Carolina","5148714","45"],
["South Dakota","884659","46"],
["Texas","28995881","48"],
["Vermont","623989","50"],
["Utah","3205958","49"],
["Virginia","8535519","51"],
["Washington","7614893","53"],
["West Virginia","1792147","54"],
["Wisconsin","5822434","55"],
["Wyoming","578759","56"],
["Puerto Rico","3193694","72"]]
Year                      2010      2011      2012      2013      2014
NAME
Alabama                4785298   4802740   4822023   4833722   4849377  \
Alaska                  713985    722718    731449    735132    736732
Arizona                6413737   6482505   6553255   6626624   6731484
Arkansas               2921606   2937979   2949131   2959373   2966369
California            37349363  37691912  38041430  38332521  38802500
Colorado               5049071   5116796   5187582   5268367   5355866
Connecticut            3577073   3580709   3590347   3596080   3596677
Delaware                899769    907135    917092    925749    935614
District of Columbia    604453    617996    632323    646449    658893
Florida               18843326  19057542  19317568  19552860  19893297
Georgia                9712587   9815210   9919945   9992167  10097343
Hawaii                 1363621   1374810   1392313   1404054   1419561
Idaho                  1571450   1584985   1595728   1612136   1634464
Illinois              12843166  12869259  12875255  12882135  12880580
Indiana                6490621   6516922   6537334   6570902   6596855
Iowa                   3049883   3062309   3074186   3090416   3107126
Kansas                 2859169   2871238   2885905   2893957   2904021
Kentucky               4346266   4369356   4380415   4395295   4413457
Louisiana              4544228   4574836   4601893   4625470   4649676
Maine                  1327567   1328188   1329192   1328302   1330089
Maryland               5785982   5828289   5884563   5928814   5976407
Massachusetts          6557254   6587536   6646144   6692824   6745408
Michigan               9877574   9876187   9883360   9895622   9909877
Minnesota              5310584   5344861   5379139   5420380   5457173
Mississippi            2970036   2978512   2984926   2991207   2994079
Missouri               5996231   6010688   6021988   6044171   6063589
Montana                 990898    998199   1005141   1015165   1023579
Nebraska               1830429   1842641   1855525   1868516   1881503
Nevada                 2704642   2723322   2758931   2790136   2839099
New Hampshire          1316759   1318194   1320718   1323459   1326813
New Jersey             8801624   8821155   8864590   8899339   8938175
New Mexico             2065932   2082224   2085538   2085287   2085572
New York              19392283  19465197  19570261  19651127  19746227
North Carolina         9561558   9656401   9752073   9848060   9943964
North Dakota            674499    683932    699628    723393    739482
Ohio                  11536182  11544951  11544225  11570808  11594163
Oklahoma               3761702   3791508   3814820   3850568   3878051
Oregon                 3838957   3871859   3899353   3930065   3970239
Pennsylvania          12709630  12742886  12763536  12773801  12787209
Puerto Rico            3722133   3706690   3667084   3615086   3548397
Rhode Island           1052886   1051302   1050292   1051511   1055173
South Carolina         4636312   4679230   4723723   4774839   4832482
South Dakota            816463    824082    833354    844877    853175
Tennessee              6356897   6403353   6456243   6495978   6549352
Texas                 25257114  25674681  26059203  26448193  26956958
Utah                   2776469   2817222   2855287   2900872   2942902
Vermont                 625960    626431    626011    626630    626562
Virginia               8024617   8096604   8185867   8260405   8326289
Washington             6744496   6830038   6897012   6971406   7061530
West Virginia          1853973   1855364   1855413   1854304   1850326
Wisconsin              5691047   5711767   5726398   5742713   5757564
Wyoming                 564460    568158    576412    582658    584153

Year                      2015      2016      2017      2018      2019
NAME
Alabama                4858979   4863300   4874747   4887871   4903185
Alaska                  738432    741894    739795    737438    731545
Arizona                6828065   6931071   7016270   7171646   7278717
Arkansas               2978204   2988248   3004279   3013825   3017804

#### Forecast population from 2020 to 2029 using historic census data

In [14]:
# Assuming your data is in a pandas DataFrame called df
df = hist_population

# Transpose the DataFrame and reset the index
df = df.transpose().reset_index()
# Rename the 'index' column to 'Year'
df = df.rename(columns={'index': 'Year'})

# Convert the DataFrame from wide format to long format
df_long = pd.melt(df, id_vars='Year', var_name='State', value_name='Population')

# # set year as index
# df_long.set_index('Year', inplace=True)
#
# # Convert index to datetime and set to year only
# df_long.index = pd.to_datetime(df_long.index, format='%Y').year

df_long

     Year                 State  Population
0    2010               Alabama     4785298
1    2011               Alabama     4802740
2    2012               Alabama     4822023
3    2013               Alabama     4833722
4    2014               Alabama     4849377
5    2015               Alabama     4858979
6    2016               Alabama     4863300
7    2017               Alabama     4874747
8    2018               Alabama     4887871
9    2019               Alabama     4903185
10   2010                Alaska      713985
11   2011                Alaska      722718
12   2012                Alaska      731449
13   2013                Alaska      735132
14   2014                Alaska      736732
15   2015                Alaska      738432
16   2016                Alaska      741894
17   2017                Alaska      739795
18   2018                Alaska      737438
19   2019                Alaska      731545
20   2010               Arizona     6413737
21   2011               Arizona     6482505
22   2012               Arizona     6553255
23   2013               Arizona     6626624
24   2014               Arizona     6731484
25   2015               Arizona     6828065
26   2016               Arizona     6931071
27   2017               Arizona     7016270
28   2018               Arizona     7171646
29   2019               Arizona     7278717
30   2010              Arkansas     2921606
31   2011              Arkansas     2937979
32   2012              Arkansas     2949131
33   2013              Arkansas     2959373
34   2014              Arkansas     2966369
35   2015              Arkansas     2978204
36   2016              Arkansas     2988248
37   2017              Arkansas     3004279
38   2018              Arkansas     3013825
39   2019              Arkansas     3017804
40   2010            California    37349363
41   2011            California    37691912
42   2012            California    38041430
43   2013            California    38332521
44   2014            California    38802500
45   2015            California    39144818
46   2016            California    39250017
47   2017            California    39536653
48   2018            California    39557045
49   2019            California    39512223
50   2010              Colorado     5049071
51   2011              Colorado     5116796
52   2012              Colorado     5187582
53   2013              Colorado     5268367
54   2014              Colorado     5355866
55   2015              Colorado     5456574
56   2016              Colorado     5540545
57   2017              Colorado     5607154
58   2018              Colorado     5695564
59   2019              Colorado     5758736
60   2010           Connecticut     3577073
61   2011           Connecticut     3580709
62   2012           Connecticut     3590347
63   2013           Connecticut     3596080
64   2014           Connecticut     3596677
65   2015           Connecticut     3590886
66   2016           Connecticut     3576452
67   2017           Connecticut     3588184
68   2018           Connecticut     3572665
69   2019           Connecticut     3565287
70   2010              Delaware      899769
71   2011              Delaware      907135
72   2012              Delaware      917092
73   2013              Delaware      925749
74   2014              Delaware      935614
75   2015              Delaware      945934
76   2016              Delaware      952065
77   2017              Delaware      961939
78   2018              Delaware      967171
79   2019              Delaware      973764
80   2010  District of Columbia      604453
81   2011  District of Columbia      617996
82   2012  District of Columbia      632323
83   2013  District of Columbia      646449
84   2014  District of Columbia      658893
85   2015  District of Columbia      672228
86   2016  District of Columbia      681170
87   2017  District of Columbia      693972
88   2018  District of Columbia      702455
89   2019  District of Columbia      705749
90   2010               Florida    18843326
91   2011               Florida    19057542
92   2012               Florida    19317568
93   2013               Florida    19552860
94   2014               Florida    19893297
95   2015               Florida    20271272
96   2016               Florida    20612439
97   2017               Florida    20984400
98   2018               Florida    21299325
99   2019               Florida    21477737
100  2010               Georgia     9712587
101  2011               Georgia     9815210
102  2012               Georgia     9919945
103  2013               Georgia     9992167
104  2014               Georgia    10097343
105  2015               Georgia    10214860
106  2016               Georgia    10310371
107  2017               Georgia    10429379
108  2018               Georgia    10519475
109  2019               Georgia    10617423
110  2010                Hawaii     1363621
111  2011                Hawaii     1374810
112  2012                Hawaii     1392313
113  2013                Hawaii     1404054
114  2014                Hawaii     1419561
115  2015                Hawaii     1431603
116  2016                Hawaii     1428557
117  2017                Hawaii     1427538
118  2018                Hawaii     1420491
119  2019                Hawaii     1415872
120  2010                 Idaho     1571450
121  2011                 Idaho     1584985
122  2012                 Idaho     1595728
123  2013                 Idaho     1612136
124  2014                 Idaho     1634464
125  2015                 Idaho     1654930
126  2016                 Idaho     1683140
127  2017                 Idaho     1716943
128  2018                 Idaho     1754208
129  2019                 Idaho     1787065
130  2010              Illinois    12843166
131  2011              Illinois    12869259
132  2012              Illinois    12875255
133  2013              Illinois    12882135
134  2014              Illinois    12880580
135  2015              Illinois    12859995
136  2016              Illinois    12801539
137  2017              Illinois    12802023
138  2018              Illinois    12741080
139  2019              Illinois    12671821
140  2010               Indiana     6490621
141  2011               Indiana     6516922
142  2012               Indiana     6537334
143  2013               Indiana     6570902
144  2014               Indiana     6596855
145  2015               Indiana     6619680
146  2016               Indiana     6633053
147  2017               Indiana     6666818
148  2018               Indiana     6691878
149  2019               Indiana     6732219
150  2010                  Iowa     3049883
151  2011                  Iowa     3062309
152  2012                  Iowa     3074186
153  2013                  Iowa     3090416
154  2014                  Iowa     3107126
155  2015                  Iowa     3123899
156  2016                  Iowa     3134693
157  2017                  Iowa     3145711
158  2018                  Iowa     3156145
159  2019                  Iowa     3155070
160  2010                Kansas     2859169
161  2011                Kansas     2871238
162  2012                Kansas     2885905
163  2013                Kansas     2893957
164  2014                Kansas     2904021
165  2015                Kansas     2911641
166  2016                Kansas     2907289
167  2017                Kansas     2913123
168  2018                Kansas     2911510
169  2019                Kansas     2913314
170  2010              Kentucky     4346266
171  2011              Kentucky     4369356
172  2012              Kentucky     4380415
173  2013              Kentucky     4395295
174  2014              Kentucky     4413457
175  2015              Kentucky     4425092
176  2016              Kentucky     4436974
177  2017              Kentucky     4454189
178  2018              Kentucky     4468402
179  2019              Kentucky     4467673
180  2010             Louisiana     4544228
181  2011             Louisiana     4574836
182  2012             Louisiana     4601893
183  2013             Louisiana     4625470
184  2014             Louisiana     4649676
185  2015             Louisiana     4670724
186  2016             Louisiana     4681666
187  2017             Louisiana     4684333
188  2018             Louisiana     4659978
189  2019             Louisiana     4648794
190  2010                 Maine     1327567
191  2011                 Maine     1328188
192  2012                 Maine     1329192
193  2013                 Maine     1328302
194  2014                 Maine     1330089
195  2015                 Maine     1329328
196  2016                 Maine     1331479
197  2017                 Maine     1335907
198  2018                 Maine     1338404
199  2019                 Maine     1344212
200  2010              Maryland     5785982
201  2011              Maryland     5828289
202  2012              Maryland     5884563
203  2013              Maryland     5928814
204  2014              Maryland     5976407
205  2015              Maryland     6006401
206  2016              Maryland     6016447
207  2017              Maryland     6052177
208  2018              Maryland     6042718
209  2019              Maryland     6045680
210  2010         Massachusetts     6557254
211  2011         Massachusetts     6587536
212  2012         Massachusetts     6646144
213  2013         Massachusetts     6692824
214  2014         Massachusetts     6745408
215  2015         Massachusetts     6794422
216  2016         Massachusetts     6811779
217  2017         Massachusetts     6859819
218  2018         Massachusetts     6902149
219  2019         Massachusetts     6892503
220  2010              Michigan     9877574
221  2011              Michigan     9876187
222  2012              Michigan     9883360
223  2013              Michigan     9895622
224  2014              Michigan     9909877
225  2015              Michigan     9922576
226  2016              Michigan     9928300
227  2017              Michigan     9962311
228  2018              Michigan     9995915
229  2019              Michigan     9986857
230  2010             Minnesota     5310584
231  2011             Minnesota     5344861
232  2012             Minnesota     5379139
233  2013             Minnesota     5420380
234  2014             Minnesota     5457173
235  2015             Minnesota     5489594
236  2016             Minnesota     5519952
237  2017             Minnesota     5576606
238  2018             Minnesota     5611179
239  2019             Minnesota     5639632
240  2010           Mississippi     2970036
241  2011           Mississippi     2978512
242  2012           Mississippi     2984926
243  2013           Mississippi     2991207
244  2014           Mississippi     2994079
245  2015           Mississippi     2992333
246  2016           Mississippi     2988726
247  2017           Mississippi     2984100
248  2018           Mississippi     2986530
249  2019           Mississippi     2976149
250  2010              Missouri     5996231
251  2011              Missouri     6010688
252  2012              Missouri     6021988
253  2013              Missouri     6044171
254  2014              Missouri     6063589
255  2015              Missouri     6083672
256  2016              Missouri     6093000
257  2017              Missouri     6113532
258  2018              Missouri     6126452
259  2019              Missouri     6137428
260  2010               Montana      990898
261  2011               Montana      998199
262  2012               Montana     1005141
263  2013               Montana     1015165
264  2014               Montana     1023579
265  2015               Montana     1032949
266  2016               Montana     1042520
267  2017               Montana     1050493
268  2018               Montana     1062305
269  2019               Montana     1068778
270  2010              Nebraska     1830429
271  2011              Nebraska     1842641
272  2012              Nebraska     1855525
273  2013              Nebraska     1868516
274  2014              Nebraska     1881503
275  2015              Nebraska     1896190
276  2016              Nebraska     1907116
277  2017              Nebraska     1920076
278  2018              Nebraska     1929268
279  2019              Nebraska     1934408
280  2010                Nevada     2704642
281  2011                Nevada     2723322
282  2012                Nevada     2758931
283  2013                Nevada     2790136
284  2014                Nevada     2839099
285  2015                Nevada     2890845
286  2016                Nevada     2940058
287  2017                Nevada     2998039
288  2018                Nevada     3034392
289  2019                Nevada     3080156
290  2010         New Hampshire     1316759
291  2011         New Hampshire     1318194
292  2012         New Hampshire     1320718
293  2013         New Hampshire     1323459
294  2014         New Hampshire     1326813
295  2015         New Hampshire     1330608
296  2016         New Hampshire     1334795
297  2017         New Hampshire     1342795
298  2018         New Hampshire     1356458
299  2019         New Hampshire     1359711
300  2010            New Jersey     8801624
301  2011            New Jersey     8821155
302  2012            New Jersey     8864590
303  2013            New Jersey     8899339
304  2014            New Jersey     8938175
305  2015            New Jersey     8958013
306  2016            New Jersey     8944469
307  2017            New Jersey     9005644
308  2018            New Jersey     8908520
309  2019            New Jersey     8882190
310  2010            New Mexico     2065932
311  2011            New Mexico     2082224
312  2012            New Mexico     2085538
313  2013            New Mexico     2085287
314  2014            New Mexico     2085572
315  2015            New Mexico     2085109
316  2016            New Mexico     2081015
317  2017            New Mexico     2088070
318  2018            New Mexico     2095428
319  2019            New Mexico     2096829
320  2010              New York    19392283
321  2011              New York    19465197
322  2012              New York    19570261
323  2013              New York    19651127
324  2014              New York    19746227
325  2015              New York    19795791
326  2016              New York    19745289
327  2017              New York    19849399
328  2018              New York    19542209
329  2019              New York    19453561
330  2010        North Carolina     9561558
331  2011        North Carolina     9656401
332  2012        North Carolina     9752073
333  2013        North Carolina     9848060
334  2014        North Carolina     9943964
335  2015        North Carolina    10042802
336  2016        North Carolina    10146788
337  2017        North Carolina    10273419
338  2018        North Carolina    10383620
339  2019        North Carolina    10488084
340  2010          North Dakota      674499
341  2011          North Dakota      683932
342  2012          North Dakota      699628
343  2013          North Dakota      723393
344  2014          North Dakota      739482
345  2015          North Dakota      756928
346  2016          North Dakota      757953
347  2017          North Dakota      755393
348  2018          North Dakota      760077
349  2019          North Dakota      762062
350  2010                  Ohio    11536182
351  2011                  Ohio    11544951
352  2012                  Ohio    11544225
353  2013                  Ohio    11570808
354  2014                  Ohio    11594163
355  2015                  Ohio    11613423
356  2016                  Ohio    11614373
357  2017                  Ohio    11658609
358  2018                  Ohio    11689442
359  2019                  Ohio    11689100
360  2010              Oklahoma     3761702
361  2011              Oklahoma     3791508
362  2012              Oklahoma     3814820
363  2013              Oklahoma     3850568
364  2014              Oklahoma     3878051
365  2015              Oklahoma     3911338
366  2016              Oklahoma     3923561
367  2017              Oklahoma     3930864
368  2018              Oklahoma     3943079
369  2019              Oklahoma     3956971
370  2010                Oregon     3838957
371  2011                Oregon     3871859
372  2012                Oregon     3899353
373  2013                Oregon     3930065
374  2014                Oregon     3970239
375  2015                Oregon     4028977
376  2016                Oregon     4093465
377  2017                Oregon     4142776
378  2018                Oregon     4190713
379  2019                Oregon     4217737
380  2010          Pennsylvania    12709630
381  2011          Pennsylvania    12742886
382  2012          Pennsylvania    12763536
383  2013          Pennsylvania    12773801
384  2014          Pennsylvania    12787209
385  2015          Pennsylvania    12802503
386  2016          Pennsylvania    12784227
387  2017          Pennsylvania    12805537
388  2018          Pennsylvania    12807060
389  2019          Pennsylvania    12801989
390  2010           Puerto Rico     3722133
391  2011           Puerto Rico     3706690
392  2012           Puerto Rico     3667084
393  2013           Puerto Rico     3615086
394  2014           Puerto Rico     3548397
395  2015           Puerto Rico     3474182
396  2016           Puerto Rico     3411307
397  2017           Puerto Rico     3337177
398  2018           Puerto Rico     3195153
399  2019           Puerto Rico     3193694
400  2010          Rhode Island     1052886
401  2011          Rhode Island     1051302
402  2012          Rhode Island     1050292
403  2013          Rhode Island     1051511
404  2014          Rhode Island     1055173
405  2015          Rhode Island     1056298
406  2016          Rhode Island     1056426
407  2017          Rhode Island     1059639
408  2018          Rhode Island     1057315
409  2019          Rhode Island     1059361
410  2010        South Carolina     4636312
411  2011        South Carolina     4679230
412  2012        South Carolina     4723723
413  2013        South Carolina     4774839
414  2014        South Carolina     4832482
415  2015        South Carolina     4896146
416  2016        South Carolina     4961119
417  2017        South Carolina     5024369
418  2018        South Carolina     5084127
419  2019        South Carolina     5148714
420  2010          South Dakota      816463
421  2011          South Dakota      824082
422  2012          South Dakota      833354
423  2013          South Dakota      844877
424  2014          South Dakota      853175
425  2015          South Dakota      858469
426  2016          South Dakota      865454
427  2017          South Dakota      869666
428  2018          South Dakota      882235
429  2019          South Dakota      884659
430  2010             Tennessee     6356897
431  2011             Tennessee     6403353
432  2012             Tennessee     6456243
433  2013             Tennessee     6495978
434  2014             Tennessee     6549352
435  2015             Tennessee     6600299
436  2016             Tennessee     6651194
437  2017             Tennessee     6715984
438  2018             Tennessee     6770010
439  2019             Tennessee     6829174
440  2010                 Texas    25257114
441  2011                 Texas    25674681
442  2012                 Texas    26059203
443  2013                 Texas    26448193
444  2014                 Texas    26956958
445  2015                 Texas    27469114
446  2016                 Texas    27862596
447  2017                 Texas    28304596
448  2018                 Texas    28701845
449  2019                 Texas    28995881
450  2010                  Utah     2776469
451  2011                  Utah     2817222
452  2012                  Utah     2855287

In [15]:
# Empty DataFrame to store the forecasted results for each state
forecast_df = pd.DataFrame()

# Loop over each unique state in the DataFrame
for state in df_long['State'].unique():
    # Filter the DataFrame for the current state
    state_df = df_long[df_long['State'] == state]

    # Reset the index
    state_df = state_df.reset_index()

    # Make sure the index is a datetime index with frequency set to 'A'
    state_df.index = pd.DatetimeIndex(pd.to_datetime(state_df['Year'], format='%Y')).to_period('A')

    # Create and fit the ARIMA model
    model = ARIMA(state_df['Population'], order=(1, 1, 1))
    model_fit = model.fit()

    # Forecast the population for the next 10 years
    forecast = model_fit.predict(len(state_df), len(state_df) + 9)

    # Prepare forecasted data for merging with original data
    forecast_data = pd.DataFrame({'Year': forecast.index.year, 'State': state, 'Population': forecast.values})

    # Concatenate forecasted data to the main forecast DataFrame
    forecast_df = pd.concat([forecast_df, forecast_data], ignore_index=True)

# Convert 'Year' in forecast_df to integer
forecast_df['Year'] = forecast_df['Year'].astype(int)

# Concatenate the historical and forecast dataframes
population_complete = pd.concat([df_long, forecast_df])

# Sort by 'Year' and 'State'
population_complete = population_complete.sort_values(['Year', 'State'])

# Pivot the DataFrame to have 'State' as index, 'Year' as columns, and 'Population' as values
population_complete = population_complete.pivot(index='State', columns='Year', values='Population')

# Convert values to integers
population_complete = population_complete.astype(int)

population_complete

C:\Users\ChrisPeoples\anaconda3\envs\2023_EV_Infrastructure_Trends\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:966: UserWarning: Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
  warn('Non-stationary starting autoregressive parameters'
C:\Users\ChrisPeoples\anaconda3\envs\2023_EV_Infrastructure_Trends\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:966: UserWarning: Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
  warn('Non-stationary starting autoregressive parameters'
C:\Users\ChrisPeoples\anaconda3\envs\2023_EV_Infrastructure_Trends\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:978: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'
C:\Users\ChrisPeoples\anaconda3\envs\2023_EV_Infrastructure_Trends\lib\site-packages\statsmodels\base\model.py:604: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\ChrisPeoples\anaconda3\envs\2023_EV_Infrastructure_Trends\lib\site-packages\statsmodels\base\model.py:604: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\ChrisPeoples\anaconda3\envs\2023_EV_Infrastructure_Trends\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:978: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'
C:\Users\ChrisPeoples\anaconda3\envs\2023_EV_Infrastructure_Trends\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:978: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'
C:\Users\ChrisPeoples\anaconda3\envs\2023_EV_Infrastructure_Trends\lib\site-packages\statsmodels\base\model.py:604: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\ChrisPeoples\anaconda3\envs\2023_EV_Infrastructure_Trends\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:966: UserWarning: Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
  warn('Non-stationary starting autoregressive parameters'
C:\Users\ChrisPeoples\anaconda3\envs\2023_EV_Infrastructure_Trends\lib\site-packages\statsmodels\base\model.py:604: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\ChrisPeoples\anaconda3\envs\2023_EV_Infrastructure_Trends\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:966: UserWarning: Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
  warn('Non-stationary starting autoregressive parameters'
C:\Users\ChrisPeoples\anaconda3\envs\2023_EV_Infrastructure_Trends\lib\site-packages\statsmodels\base\model.py:604: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\ChrisPeoples\anaconda3\envs\2023_EV_Infrastructure_Trends\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:966: UserWarning: Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
  warn('Non-stationary starting autoregressive parameters'
C:\Users\ChrisPeoples\anaconda3\envs\2023_EV_Infrastructure_Trends\lib\site-packages\statsmodels\base\model.py:604: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\ChrisPeoples\anaconda3\envs\2023_EV_Infrastructure_Trends\lib\site-packages\statsmodels\base\model.py:604: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\ChrisPeoples\anaconda3\envs\2023_EV_Infrastructure_Trends\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:978: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'
C:\Users\ChrisPeoples\anaconda3\envs\2023_EV_Infrastructure_Trends\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:966: UserWarning: Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
  warn('Non-stationary starting autoregressive parameters'
C:\Users\ChrisPeoples\anaconda3\envs\2023_EV_Infrastructure_Trends\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:978: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'
C:\Users\ChrisPeoples\anaconda3\envs\2023_EV_Infrastructure_Trends\lib\site-packages\statsmodels\base\model.py:604: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\ChrisPeoples\anaconda3\envs\2023_EV_Infrastructure_Trends\lib\site-packages\statsmodels\base\model.py:604: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\ChrisPeoples\anaconda3\envs\2023_EV_Infrastructure_Trends\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:978: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'
C:\Users\ChrisPeoples\anaconda3\envs\2023_EV_Infrastructure_Trends\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:978: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'
C:\Users\ChrisPeoples\anaconda3\envs\2023_EV_Infrastructure_Trends\lib\site-packages\statsmodels\base\model.py:604: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\ChrisPeoples\anaconda3\envs\2023_EV_Infrastructure_Trends\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:978: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'
C:\Users\ChrisPeoples\anaconda3\envs\2023_EV_Infrastructure_Trends\lib\site-packages\statsmodels\base\model.py:604: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\ChrisPeoples\anaconda3\envs\2023_EV_Infrastructure_Trends\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:966: UserWarning: Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
  warn('Non-stationary starting autoregressive parameters'
C:\Users\ChrisPeoples\anaconda3\envs\2023_EV_Infrastructure_Trends\lib\site-packages\statsmodels\base\model.py:604: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\ChrisPeoples\anaconda3\envs\2023_EV_Infrastructure_Trends\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:966: UserWarning: Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
  warn('Non-stationary starting autoregressive parameters'
C:\Users\ChrisPeoples\anaconda3\envs\2023_EV_Infrastructure_Trends\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:978: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'
C:\Users\ChrisPeoples\anaconda3\envs\2023_EV_Infrastructure_Trends\lib\site-packages\statsmodels\base\model.py:604: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\ChrisPeoples\anaconda3\envs\2023_EV_Infrastructure_Trends\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:966: UserWarning: Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
  warn('Non-stationary starting autoregressive parameters'
C:\Users\ChrisPeoples\anaconda3\envs\2023_EV_Infrastructure_Trends\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:978: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'
C:\Users\ChrisPeoples\anaconda3\envs\2023_EV_Infrastructure_Trends\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:966: UserWarning: Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
  warn('Non-stationary starting autoregressive parameters'
C:\Users\ChrisPeoples\anaconda3\envs\2023_EV_Infrastructure_Trends\lib\site-packages\statsmodels\base\model.py:604: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\ChrisPeoples\anaconda3\envs\2023_EV_Infrastructure_Trends\lib\site-packages\statsmodels\base\model.py:604: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\ChrisPeoples\anaconda3\envs\2023_EV_Infrastructure_Trends\lib\site-packages\statsmodels\base\model.py:604: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\ChrisPeoples\anaconda3\envs\2023_EV_Infrastructure_Trends\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:966: UserWarning: Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
  warn('Non-stationary starting autoregressive parameters'
C:\Users\ChrisPeoples\anaconda3\envs\2023_EV_Infrastructure_Trends\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:978: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'
C:\Users\ChrisPeoples\anaconda3\envs\2023_EV_Infrastructure_Trends\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:978: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'
C:\Users\ChrisPeoples\anaconda3\envs\2023_EV_Infrastructure_Trends\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:966: UserWarning: Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
  warn('Non-stationary starting autoregressive parameters'
C:\Users\ChrisPeoples\anaconda3\envs\2023_EV_Infrastructure_Trends\lib\site-packages\statsmodels\base\model.py:604: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\ChrisPeoples\anaconda3\envs\2023_EV_Infrastructure_Trends\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:966: UserWarning: Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
  warn('Non-stationary starting autoregressive parameters'
C:\Users\ChrisPeoples\anaconda3\envs\2023_EV_Infrastructure_Trends\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:978: UserWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  warn('Non-invertible starting MA parameters found.'
C:\Users\ChrisPeoples\anaconda3\envs\2023_EV_Infrastructure_Trends\lib\site-packages\statsmodels\base\model.py:604: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\ChrisPeoples\anaconda3\envs\2023_EV_Infrastructure_Trends\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:966: UserWarning: Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
  warn('Non-stationary starting autoregressive parameters'
C:\Users\ChrisPeoples\anaconda3\envs\2023_EV_Infrastructure_Trends\lib\site-packages\statsmodels\base\model.py:604: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\ChrisPeoples\anaconda3\envs\2023_EV_Infrastructure_Trends\lib\site-packages\statsmodels\base\model.py:604: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
C:\Users\ChrisPeoples\anaconda3\envs\2023_EV_Infrastructure_Trends\lib\site-packages\statsmodels\tsa\statespace\sarimax.py:966: UserWarning: Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
  warn('Non-stationary starting autoregressive parameters'

Year,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026,2027,2028,2029
State,,,,,,,,,,,,,,,,,,,,
Alabama,4785298,4802740,4822023,4833722,4849377,4858979,4863300,4874747,4887871,4903185,4912840,4921953,4930554,4938672,4946333,4953563,4960387,4966828,4972906,4978643
Alaska,713985,722718,731449,735132,736732,738432,741894,739795,737438,731545,731551,731554,731557,731558,731559,731560,731560,731560,731560,731560
Arizona,6413737,6482505,6553255,6626624,6731484,6828065,6931071,7016270,7171646,7278717,7374280,7469813,7565315,7660785,7756225,7851634,7947012,8042359,8137675,8232960
Arkansas,2921606,2937979,2949131,2959373,2966369,2978204,2988248,3004279,3013825,3017804,3025601,3032940,3039847,3046348,3052465,3058223,3063642,3068742,3073541,3078058
California,37349363,37691912,38041430,38332521,38802500,39144818,39250017,39536653,39557045,39512223,39616385,39705692,39782261,39847910,39904196,39952455,39993831,40029306,40059721,40085798
Colorado,5049071,5116796,5187582,5268367,5355866,5456574,5540545,5607154,5695564,5758736,5837000,5915154,5993199,6071135,6148961,6226679,6304288,6381787,6459179,6536462
Connecticut,3577073,3580709,3590347,3596080,3596677,3590886,3576452,3588184,3572665,3565287,3564432,3563600,3562787,3561995,3561223,3560470,3559735,3559019,3558321,3557639
Delaware,899769,907135,917092,925749,935614,945934,952065,961939,967171,973764,980665,987336,993782,1000011,1006032,1011850,1017473,1022908,1028159,1033235
District of Columbia,604453,617996,632323,646449,658893,672228,681170,693972,702455,705749,712892,719449,725468,730993,736065,740720,744994,748917,752518,755824
Florida,18843326,19057542,19317568,19552860,19893297,20271272,20612439,20984400,21299325,21477737,21767708,22057435,22346917,22636155,22925148,23213897,23502401,23790662,24078680,24366454
Georgia,9712587,9815210,9919945,9992167,10097343,10214860,10310371,10429379,10519475,10617423,10716595,10815556,10914307,11012847,11111177,11209298,11307209,11404912,11502407,11599694
Hawaii,1363621,1374810,1392313,1404054,1419561,1431603,1428557,1427538,1420491,1415872,1416922,1417706,1418289,1418725,1419049,1419291,1419472,1419606,1419706,1419781
Idaho,1571450,1584985,1595728,1612136,1634464,1654930,1683140,1716943,1754208,1787065,1811231,1835397,1859562,1883726,1907888,1932050,1956210,1980370,2004528,2028685
Illinois,12843166,12869259,12875255,12882135,12880580,12859995,12801539,12802023,12741080,12671821,12653425,12635085,12616799,12598568,12580390,12562267,12544198,12526183,12508222,12490314
Indiana,6490621,6516922,6537334,6570902,6596855,6619680,6633053,6666818,6691878,6732219,6758586,6784946,6811299,6837645,6863985,6890317,6916643,6942962,6969274,6995579
Iowa,3049883,3062309,3074186,3090416,3107126,3123899,3134693,3145711,3156145,3155070,3162638,3169602,3176010,3181906,3187331,3192324,3196917,3201144,3205034,3208612
Kansas,2859169,2871238,2885905,2893957,2904021,2911641,2907289,2913123,2911510,2913314,2914735,2915835,2916687,2917346,2917856,2918251,2918557,2918793,2918977,2919118
Kentucky,4346266,4369356,4380415,4395295,4413457,4425092,4436974,4454189,4468402,4467673,4475561,4482697,4489153,4494993,4500276,4505055,4509378,4513289,4516827,4520028
Louisiana,4544228,4574836,4601893,4625470,4649676,4670724,4681666,4684333,4659978,4648794,4650649,4651999,4652983,4653700,4654221,4654601,4654878,4655079,4655226,4655333
Maine,1327567,1328188,1329192,1328302,1330089,1329328,1331479,1335907,1338404,1344212,1346008,1347802,1349592,1351378,1353161,1354941,1356717,1358490,1360259,1362025
Maryland,5785982,5828289,5884563,5928814,5976407,6006401,6016447,6052177,6042718,6045680,6055769,6064111,6071010,6076715,6081432,6085332,6088558,6091225,6093430,6095254
Massachusetts,6557254,6587536,6646144,6692824,6745408,6794422,6811779,6859819,6902149,6892503,6916512,6938589,6958888,6977553,6994716,7010497,7025007,7038350,7050618,7061898
Michigan,9877574,9876187,9883360,9895622,9909877,9922576,9928300,9962311,9995915,9986857,9986859,9986859,9986859,9986859,9986859,9986859,9986859,9986859,9986859,9986859
Minnesota,5310584,5344861,5379139,5420380,5457173,5489594,5519952,5576606,5611179,5639632,5675660,5711601,5747455,5783221,5818900,5854493,5889998,5925417,5960750,5995997
Mississippi,2970036,2978512,2984926,2991207,2994079,2992333,2988726,2984100,2986530,2976149,2976229,2976279,2976309,2976328,2976340,2976347,2976352,2976355,2976356,2976357
Missouri,5996231,6010688,6021988,6044171,6063589,6083672,6093000,6113532,6126452,6137428,6151510,6165297,6178796,6192012,6204951,6217619,6230021,6242164,6254053,6265692
Montana,990898,998199,1005141,1015165,1023579,1032949,1042520,1050493,1062305,1068778,1077374,1085964,1094547,1103123,1111693,1120256,1128812,1137361,1145904,1154440
Nebraska,1830429,1842641,1855525,1868516,1881503,1896190,1907116,1920076,1929268,1934408,1943197,1951534,1959442,1966944,1974061,1980811,1987215,1993289,1999051,2004517
Nevada,2704642,2723322,2758931,2790136,2839099,2890845,2940058,2998039,3034392,3080156,3121638,3163106,3204559,3245998,3287421,3328830,3370224,3411603,3452968,3494318
New Hampshire,1316759,1318194,1320718,1323459,1326813,1330608,1334795,1342795,1356458,1359711,1364374,1369032,1373687,1378338,1382985,1387627,1392265,1396900,1401530,1406156
New Jersey,8801624,8821155,8864590,8899339,8938175,8958013,8944469,9005644,8908520,8882190,8884144,8885568,8886605,8887360,8887910,8888311,8888603,8888815,8888970,8889083
New Mexico,2065932,2082224,2085538,2085287,2085572,2085109,2081015,2088070,2095428,2096829,2096859,2096867,2096869,2096870,2096870,2096870,2096870,2096870,2096870,2096870
New York,19392283,19465197,19570261,19651127,19746227,19795791,19745289,19849399,19542209,19453561,19454826,19455664,19456221,19456590,19456834,19456997,19457104,19457175,19457223,19457254
North Carolina,9561558,9656401,9752073,9848060,9943964,10042802,10146788,10273419,10383620,10488084,10590079,10691928,10793633,10895192,10996607,11097876,11199002,11299983,11400820,11501513
North Dakota,674499,683932,699628,723393,739482,756928,757953,755393,760077,762062,765938,769225,772013,774378,776383,778084,779527,780750,781788,782668
Ohio,11536182,11544951,11544225,11570808,11594163,11613423,11614373,11658609,11689442,11689100,11705721,11722303,11738844,11755346,11771809,11788231,11804614,11820958,11837262,11853527
Oklahoma,3761702,3791508,3814820,3850568,3878051,3911338,3923561,3930864,3943079,3956971,3968593,3978937,3988143,3996337,4003628,4010118,4015893,4021033,4025608,4029679
Oregon,3838957,3871859,3899353,3930065,3970239,4028977,4093465,4142776,4190713,4217737,4259478,4301188,4342866,4384513,4426128,4467712,4509265,4550786,4592276,4633734
Pennsylvania,12709630,12742886,12763536,12773801,12787209,12802503,12784227,12805537,12807060,12801989,12804914,12807209,12809009,12810421,12811528,12812397,12813078,12813612,12814031,12814360
Puerto Rico,3722133,3706690,3667084,3615086,3548397,3474182,3411307,3337177,3195153,3193694,3147695,3103278,3060387,3018970,2978977,2940359,2903068,2867059,2832287,2798711
Rhode Island,1052886,1051302,1050292,1051511,1055173,1056298,1056426,1059639,1057315,1059361,1059367,1059362,1059366,1059363,1059365,1059363,1059365,1059364,1059364,1059364
South Carolina,4636312,4679230,4723723,4774839,4832482,4896146,4961119,5024369,5084127,5148714,5204985,5261192,5317335,5373415,5429430,5485381,5541268,5597092,5652852,5708548
South Dakota,816463,824082,833354,844877,853175,858469,865454,869666,882235,884659,890331,895696,900770,905569,910108,914401,918461,922301,925933,929369
Tennessee,6356897,6403353,6456243,6495978,6549352,6600299,6651194,6715984,6770010,6829174,6881228,6933232,6985184,7037085,7088936,7140735,7192484,7244181,7295828,7347425
Texas,25257114,25674681,26059203,26448193,26956958,27469114,27862596,28304596,28701845,28995881,29377056,29751822,30120288,30482558,30838737,31188928,31533231,31871745,32204567,32531794
Utah,2776469,2817222,2855287,2900872,2942902,2995919,3051217,3101833,3161105,3205958,3253443,3300908,3348352,3395777,3443181,3490564,3537928,3585271,3632594,3679897
Vermont,625960,626431,626011,626630,626562,626042,624594,623657,626299,623989,623987,623987,623987,623987,623987,623987,623987,623987,623987,623987
Virginia,8024617,8096604,8185867,8260405,8326289,8382993,8411808,8470020,8517685,8535519,8566551,8594272,8619036,8641159,8660921,8678576,8694347,8708435,8721021,8732264
Washington,6744496,6830038,6897012,6971406,7061530,7170351,7288000,7405743,7535591,7614893,7711205,7807481,7903721,7999925,8096093,8192225,8288322,8384382,8480406,8576394
West Virginia,1853973,1855364,1855413,1854304,1850326,1844128,1831102,1815857,1805832,1792147,1792133,1792133,1792133,1792133,1792133,1792133,1792133,1792133,1792133,1792133
Wisconsin,5691047,5711767,5726398,5742713,5757564,5771337,5778709,5795483,5813568,5822434,5833860,5844756,5855144,5865048,5874492,5883496,5892082,5900267,5908072,5915514
Wyoming,564460,568158,576412,582658,584153,586107,585501,579315,577737,578759,578905,579005,579071,579117,579147,579168,579182,579191,579197,579202

In [16]:
# Save dataframe using the save_data function
save_data(population_complete, 'USA_State_Population')

Saving data USA_State_Population.csv
File saved at C:\Users\ChrisPeoples\OneDrive - Peoples Partners and Associates, LLC\PP&A Working Directory\70_Studies_and_Reports\2023_EV_Infrastructure_Trends\data\USA_State_Population.csv/USA_State_Population.csv

#### EV Charging Infrastructure (NREL Data)

##### Build Dataframe structure for charging infrastructure data

In [17]:
# define the dataframe columns
column_names = ['ID',
                'Name',
                'EV Network',
                'Owner Type',
                'Pricing', 
                'Renewable Source',
                'Access Type',
                'Access Details',
                'Access Times',
                'Connector Types',
                'Level 1 Chargers Count',
                'Level 2 Chargers Count',
                'DC Fast Chargers Count',
                'Other Charger Count',
                'Street Address',
                'City',
                'State',
                'Zip Code', 
                'Latitude', 
                'Longitude'] 

# instantiate the dataframe
ev_charger_structure = pd.DataFrame(columns=column_names)
ev_charger_structure

Empty DataFrame
Columns: [ID, Name, EV Network, Owner Type, Pricing, Renewable Source, Access Type, Access Details, Access Times, Connector Types, Level 1 Chargers Count, Level 2 Chargers Count, DC Fast Chargers Count, Other Charger Count, Street Address, City, State, Zip Code, Latitude, Longitude]
Index: []

##### Selected Data Definitions
<a href="https://developer.nrel.gov/docs/transportation/alt-fuel-stations-v1/get/">Link to NREL Documentation</a>
<section>
    <h5 style="text-decoration: underline; line-height: 0; margin-top: 20px;">Ownership Type:</h5>
<ul>
    <li>P - Privately Owned</li>
    <li>T - Utility Owned</li>
    <li>FG - Federal Government Owned</li>
    <li>LG - Local Government</li>
    <li>SG - State Government</li>
    <li>J - Joint Ownership</li>
</ul>
</section>

<section>
    <h5 style="text-decoration: underline; line-height: 0; margin-top: 20px;">EV Connector Types:</h5>
<ul>
    <li>NEMA515 - NEMA 5 - 15 (Level 1)</li>
    <li>NEMA520 - NEMA 5 - 20 (Level 1)</li>
    <li>NEMA1450 - NEMA 14 - 50 (Level 1)</li>
    <li>J1772 - J1772 (Level 2)</li>
    <li>CHADEMO - HAdeMO (DC Fast Charging)</li>
    <li>J1772COMBO - SAE J1772 Combo (DC Fast Charging)</li>
    <li>TESLA - Tesla (DC Fast Charging)</li>
</ul>
</section>

<section>
    <h5 style="text-decoration: underline; line-height: 0; margin-top: 20px;">Other Charger Types:</h5>
<ul>
    <li>SP Inductive - Small Paddle Inductive</li>
    <li>LP Inductive - Large Paddle Inductive</li>
    <li>Avcon - Conductive</li>
</ul>
</section>

<section>
    <h5 style="text-decoration: underline; line-height: 0; margin-top: 20px;">Access Details:</h5>
<ul>
    <li>Public - Publicly available to all customers</li>
    <li>Public - Call ahead - Publicly available, but customers should call before visiting</li>
    <li>Public - Credit card at all times - Publicly available, but only accepts credit cards as payment. The station may also except fleet cards or station-specific fueling cards</li>
    <li>Public - Card key at all times - Publicly available, but only accepts fleet cards or station-specific fueling cards</li>
    <li>Public - Credit card after hours - Publicly available and accepts credit cards 24 hours a day. The station may also except fleet cards or station-specific fueling cards</li>
    <li>Public - Card key after hours - Publicly available 24 hours a day, but only accepts fleet cards or station-specific fueling cards</li>
</ul>
</section>

##### Prepare NREL query statement

In [18]:
url = "https://developer.nrel.gov/api/alt-fuel-stations/v1.json?fuel_type=ELEC&api_key={}".format(NREL_ID)
NREL_ev_data = requests.get(url).json()
NREL_ev_data = NREL_ev_data['fuel_stations']

##### Function to convert NREL data into dataframe format

In [19]:
def get_EV_data(data_input):
    rows = []

    # Loop to convert JSON results to dataframe rows
    for ind, entry in enumerate(data_input):
        connector_types = entry['ev_connector_types'] if entry['ev_connector_types'] else []

        # Check for status code and assign the appropriate description
        status_code = entry['status_code']
        if status_code == 'E':
            status_description = 'Available'
        elif status_code == 'P':
            status_description = 'Planned'
        elif status_code == 'T':
            status_description = 'Temporarily Unavailable'
        else:
            status_description = 'Unknown'

        # Assign data entry data to a dictionary
        row = {
            'ID': entry['id'],
            'Status': status_description,
            'Open Date': entry['open_date'],
            'Name': entry['station_name'],
            'EV Network': entry['ev_network'],
            'Owner Type': entry['owner_type_code'],
            'Pricing': entry['ev_pricing'],
            'Renewable Source': entry['ev_renewable_source'],
            'Access Type': entry['access_code'],
            'Access Details': entry['groups_with_access_code'],
            'Access Times': entry['access_days_time'],
            'Level 1 Chargers Count': entry['ev_level1_evse_num'],
            'Level 2 Chargers Count': entry['ev_level2_evse_num'],
            'DC Fast Chargers Count': entry["ev_dc_fast_num"],
            'Other Charger Count': entry['ev_other_evse'],
            'NEMA 14-50': int('NEMA1450' in connector_types),
            'NEMA 5-15': int('NEMA515' in connector_types),
            'NEMA 5-20': int('NEMA520' in connector_types),
            'J1772': int('J1772' in connector_types),
            'CCS': int('J1772COMBO' in connector_types),
            'CHAdeMO': int('CHADEMO' in connector_types),
            'Tesla': int('TESLA' in connector_types),
            'Facility Type': entry['facility_type'],
            'Street Address': entry['street_address'],
            'City': entry['city'],
            'State': entry['state'],
            'Zip Code': entry['zip'],
            'Latitude': entry['latitude'],
            'Longitude': entry['longitude'],
            'Expected Date': entry['expected_date']
        }

        # Append the row dictionary to the list
        rows.append(row)

    # Create a DataFrame from the list of dictionaries
    output = pd.DataFrame(rows)

    # Output dataframe
    return output

print("Ready")

Ready

In [20]:
ev_data = get_EV_data(NREL_ev_data)
print("Done")

Done

In [21]:
print(ev_data.shape)
ev_data.head(20)

(61913, 30)

,ID,Status,Open Date,Name,EV Network,Owner Type,Pricing,Renewable Source,Access Type,Access Details,Access Times,Level 1 Chargers Count,Level 2 Chargers Count,DC Fast Chargers Count,Other Charger Count,NEMA 14-50,NEMA 5-15,NEMA 5-20,J1772,CCS,CHAdeMO,Tesla,Facility Type,Street Address,City,State,Zip Code,Latitude,Longitude,Expected Date
0,1517,Available,1999-10-15,LADWP - Truesdale Center,Non-Networked,LG,None,None,private,Private,Fleet use only,NaN,39.0,3.0,None,0,0,0,1,1,1,0,UTILITY,11797 Truesdale St,Sun Valley,CA,91352,34.248319,-118.387971,None
1,1519,Available,2020-02-28,LADWP - West LA District Office,Non-Networked,LG,Free,None,private,Private,None,NaN,4.0,NaN,None,0,0,0,1,0,0,0,UTILITY,1394 S Sepulveda Blvd,Los Angeles,CA,90024,34.052542,-118.448504,None
2,1523,Available,1995-08-30,Los Angeles Convention Center,Non-Networked,P,Free; parking fee,None,public,Public,5:30am-9pm; pay lot,NaN,7.0,NaN,None,0,0,0,1,0,0,0,PARKING_GARAGE,1201 S Figueroa St,Los Angeles,CA,90015,34.040539,-118.271387,None
3,1525,Available,1999-10-15,LADWP - John Ferraro Building,Non-Networked,LG,None,None,private,Private,For fleet and employee use only,NaN,311.0,2.0,None,0,0,0,1,1,1,0,UTILITY,111 N Hope St,Los Angeles,CA,90012,34.059133,-118.248589,None
4,1531,Available,2018-05-01,LADWP - Haynes Power Plant,Non-Networked,LG,None,None,private,Private,Fleet use only,NaN,19.0,1.0,None,0,0,0,1,1,1,0,UTILITY,6801 E 2nd St,Long Beach,CA,90803,33.759802,-118.096665,None
5,1552,Available,1999-10-15,LADWP - Harbor Generating Station,Non-Networked,LG,None,None,private,Private,Fleet use only,NaN,10.0,NaN,None,0,0,0,1,0,0,0,UTILITY,161 N Island Ave,Wilmington,CA,90744,33.770508,-118.265628,None
6,1556,Available,2016-01-01,LADWP - Sylmar West,Non-Networked,LG,None,None,private,Private - Government only,Fleet use only,NaN,2.0,NaN,None,0,0,0,1,0,0,0,UTILITY,13201 Sepulveda Blvd,Sylmar,CA,91342,34.303090,-118.480505,None
7,1572,Available,1999-10-15,LADWP - EV Service Center,Non-Networked,LG,None,None,private,Private,Fleet and employee use only,NaN,46.0,1.0,None,0,0,0,1,0,1,0,UTILITY,1630 N Main St,Los Angeles,CA,90012,34.066801,-118.227605,None
8,1573,Available,2019-04-01,LADWP - Fairfax Center,Non-Networked,LG,None,None,private,Private,Fleet use only,NaN,13.0,NaN,None,0,0,0,1,0,0,0,UTILITY,2311 S Fairfax Ave,Los Angeles,CA,90016,34.036777,-118.368841,None
9,1583,Available,1996-10-15,California Air Resources Board,Non-Networked,SG,Free,None,public,Public,24 hours daily,NaN,3.0,NaN,None,0,0,0,1,0,0,0,STATE_GOV,9530 Telstar Ave,El Monte,CA,91731,34.068720,-118.064000,None
10,1589,Available,1999-10-15,LADWP - Palmetto Center,Non-Networked,LG,None,None,private,Private,Fleet use only,NaN,10.0,NaN,None,0,0,0,1,0,0,0,UTILITY,1212 Palmetto St,Los Angeles,CA,90013,34.039736,-118.236065,None
11,6355,Available,1997-07-30,Scripps Green Hospital,Non-Networked,P,Free; parking fee,None,public,Public,24 hours daily,NaN,1.0,NaN,None,0,0,0,1,0,0,0,HOSPITAL,10666 N Torrey Pines Rd,La Jolla,CA,92037,32.899470,-117.243000,None
12,6405,Available,2012-12-11,Galpin Motors,Non-Networked,P,Free,None,public,Public - Call ahead,Dealership business hours,NaN,2.0,NaN,None,0,0,0,1,0,0,0,CAR_DEALER,15421 Roscoe Blvd,Sepulveda,CA,91343,34.221665,-118.468371,None
13,6425,Available,1997-08-30,Galleria at Tyler,Non-Networked,P,Free,None,public,Public,6am-12am daily,NaN,4.0,NaN,None,0,0,0,1,0,0,0,SHOPPING_MALL,1299 Galleria at Tyler,Riverside,CA,92503,33.909914,-117.459053,None
14,6505,Available,1997-08-30,City of Pasadena - Holly Street Garage,Non-Networked,LG,Free,None,public,Public,24 hours daily; pay lot,NaN,16.0,NaN,None,0,0,0,1,0,0,0,PARKING_GARAGE,150 E Holly St,Pasadena,CA,91103,34.147620,-118.147111,None
15,6506,Available,1997-08-30,City of Pasadena - De Lacey Garage,Non-Networked,LG,Free; parking fee,None,public,Public,24 hours daily; pay lot,NaN,2.0,NaN,None,0,0,0,1,0,0,0,PARKING_GARAGE,45 De Lacey Ave,Pasadena,CA,91105,34.145138,-118.152655,None
16,6507,Available,1997-08-30,City of Pasadena - Schoolhouse Garage,Non-Networked,LG,"$1 for the first two hours, $2 each additional...",None,public,Public,24 hours daily; pay lot,NaN,3.0,NaN,None,0,0,0,1,0,0,0,PARKING_GARAGE,33 E Green St,Pasadena,CA,91105,34.145119,-118.150133,None
17,6509,Available,1997-08-31,Bristol Farms,Non-Networked,P,Free,None,public,Public,24 hours daily,NaN,NaN,NaN,1 LP Inductive,0,0,0,0,0,0,0,GROCERY,606 Fair Oaks Ave,South Pasadena,CA,91030,34.118433,-118.149597,None
18,7172,Available,2012-05-04,Hyatt Regency Long Beach,Non-Networked,P,Free,None,public,Public,24 hours daily; pay lot; see valet for access,NaN,1.0,NaN,None,0,0,0,1,0,0,0,HOTEL,200 S Pine Ave,Long Beach,CA,90802,33.763700,-118.192000,None
19,7184,Available,1998-06-30,Los Angeles International Airport (LAX) - Lot 6,Non-Networked,LG,$2 service fee + $0.45 per kWh,None,public,Public,24 hours daily; pay lot,NaN,20.0,NaN,None,0,0,0,1,0,0,0,AIRPORT,1 World Way,Los Angeles,CA,90045,33.943250,-118.403342,None

In [22]:
ev_data.dtypes

ID                          int64
Status                     object
Open Date                  object
Name                       object
EV Network                 object
Owner Type                 object
Pricing                    object
Renewable Source           object
Access Type                object
Access Details             object
Access Times               object
Level 1 Chargers Count    float64
Level 2 Chargers Count    float64
DC Fast Chargers Count    float64
Other Charger Count        object
NEMA 14-50                  int64
NEMA 5-15                   int64
NEMA 5-20                   int64
J1772                       int64
CCS                         int64
CHAdeMO                     int64
Tesla                       int64
Facility Type              object
Street Address             object
City                       object
State                      object
Zip Code                   object
Latitude                  float64
Longitude                 float64
Expected Date              object
dtype: object

##### Clean EV Infrastructure Data Set

Cleaning tasks:
*   Replace 'None' values in charger columns
*   Replace Pricing, Access Times, and Expected Dates 'None' values with not available indicators
*   Set variables to Int type

In [23]:
# Replace 'None' values in charger columns
chargers = ['Level 1 Chargers Count', 'Level 2 Chargers Count', 'DC Fast Chargers Count', 'Other Charger Count']
ev_data[chargers] = ev_data[chargers].replace(np.nan, 0)

# Replace Pricing, Access Times, and Expected Dates 'None' values with not available indicators
cols = ['Pricing', 'Access Times', 'Expected Date', 'Owner Type', 'Renewable Source']
ev_data[cols] = ev_data[cols].replace(np.nan, 'NA')

# Set variables to Int type
# ev_data['Zip Code'] = ev_data['Zip Code'].astype(int)
ev_data['Level 1 Chargers Count'] = ev_data['Level 1 Chargers Count'].astype(int)
ev_data['Level 2 Chargers Count'] = ev_data['Level 2 Chargers Count'].astype(int)
ev_data['DC Fast Chargers Count'] = ev_data['DC Fast Chargers Count'].astype(int)
print("Clean")

Clean

##### Validate NREL Data Completeness

In [24]:
missing_data = ev_data.isnull()

for column in missing_data.columns.values.tolist():
    print(column)
    print (missing_data[column].value_counts())
    print("")

ID
ID
False    61913
Name: count, dtype: int64

Status
Status
False    61913
Name: count, dtype: int64

Open Date
Open Date
False    61803
True       110
Name: count, dtype: int64

Name
Name
False    61913
Name: count, dtype: int64

EV Network
EV Network
False    61909
True         4
Name: count, dtype: int64

Owner Type
Owner Type
False    61913
Name: count, dtype: int64

Pricing
Pricing
False    61913
Name: count, dtype: int64

Renewable Source
Renewable Source
False    61913
Name: count, dtype: int64

Access Type
Access Type
False    61912
True         1
Name: count, dtype: int64

Access Details
Access Details
False    61913
Name: count, dtype: int64

Access Times
Access Times
False    61913
Name: count, dtype: int64

Level 1 Chargers Count
Level 1 Chargers Count
False    61913
Name: count, dtype: int64

Level 2 Chargers Count
Level 2 Chargers Count
False    61913
Name: count, dtype: int64

DC Fast Chargers Count
DC Fast Chargers Count
False    61913
Name: count, dtype: int64

Other Charger Count
Other Charger Count
False    61913
Name: count, dtype: int64

NEMA 14-50
NEMA 14-50
False    61913
Name: count, dtype: int64

NEMA 5-15
NEMA 5-15
False    61913
Name: count, dtype: int64

NEMA 5-20
NEMA 5-20
False    61913
Name: count, dtype: int64

J1772
J1772
False    61913
Name: count, dtype: int64

CCS
CCS
False    61913
Name: count, dtype: int64

CHAdeMO
CHAdeMO
False    61913
Name: count, dtype: int64

Tesla
Tesla
False    61913
Name: count, dtype: int64

Facility Type
Facility Type
True     45254
False    16659
Name: count, dtype: int64

Street Address
Street Address
False    61880
True        33
Name: count, dtype: int64

City
City
False    61913
Name: count, dtype: int64

State
State
False    61908
True         5
Name: count, dtype: int64

Zip Code
Zip Code
False    61913
Name: count, dtype: int64

Latitude
Latitude
False    61913
Name: count, dtype: int64

Longitude
Longitude
False    61913
Name: count, dtype: int64

Expected Date
Expected Date
False    61913
Name: count, dtype: int64

In [25]:
ev_data.dtypes

ID                          int64
Status                     object
Open Date                  object
Name                       object
EV Network                 object
Owner Type                 object
Pricing                    object
Renewable Source           object
Access Type                object
Access Details             object
Access Times               object
Level 1 Chargers Count      int32
Level 2 Chargers Count      int32
DC Fast Chargers Count      int32
Other Charger Count        object
NEMA 14-50                  int64
NEMA 5-15                   int64
NEMA 5-20                   int64
J1772                       int64
CCS                         int64
CHAdeMO                     int64
Tesla                       int64
Facility Type              object
Street Address             object
City                       object
State                      object
Zip Code                   object
Latitude                  float64
Longitude                 float64
Expected Date              object
dtype: object

In [26]:
ev_data.head()

,ID,Status,Open Date,Name,EV Network,Owner Type,Pricing,Renewable Source,Access Type,Access Details,Access Times,Level 1 Chargers Count,Level 2 Chargers Count,DC Fast Chargers Count,Other Charger Count,NEMA 14-50,NEMA 5-15,NEMA 5-20,J1772,CCS,CHAdeMO,Tesla,Facility Type,Street Address,City,State,Zip Code,Latitude,Longitude,Expected Date
0,1517,Available,1999-10-15,LADWP - Truesdale Center,Non-Networked,LG,NA,NA,private,Private,Fleet use only,0,39,3,0,0,0,0,1,1,1,0,UTILITY,11797 Truesdale St,Sun Valley,CA,91352,34.248319,-118.387971,NA
1,1519,Available,2020-02-28,LADWP - West LA District Office,Non-Networked,LG,Free,NA,private,Private,NA,0,4,0,0,0,0,0,1,0,0,0,UTILITY,1394 S Sepulveda Blvd,Los Angeles,CA,90024,34.052542,-118.448504,NA
2,1523,Available,1995-08-30,Los Angeles Convention Center,Non-Networked,P,Free; parking fee,NA,public,Public,5:30am-9pm; pay lot,0,7,0,0,0,0,0,1,0,0,0,PARKING_GARAGE,1201 S Figueroa St,Los Angeles,CA,90015,34.040539,-118.271387,NA
3,1525,Available,1999-10-15,LADWP - John Ferraro Building,Non-Networked,LG,NA,NA,private,Private,For fleet and employee use only,0,311,2,0,0,0,0,1,1,1,0,UTILITY,111 N Hope St,Los Angeles,CA,90012,34.059133,-118.248589,NA
4,1531,Available,2018-05-01,LADWP - Haynes Power Plant,Non-Networked,LG,NA,NA,private,Private,Fleet use only,0,19,1,0,0,0,0,1,1,1,0,UTILITY,6801 E 2nd St,Long Beach,CA,90803,33.759802,-118.096665,NA

##### Filter to Baltimore EV Infrastructure Data

In [27]:
ev_baltimore = ev_data[ev_data["City"]=='Baltimore']
print(ev_baltimore.shape)
ev_baltimore.head()

(313, 30)

,ID,Status,Open Date,Name,EV Network,Owner Type,Pricing,Renewable Source,Access Type,Access Details,Access Times,Level 1 Chargers Count,Level 2 Chargers Count,DC Fast Chargers Count,Other Charger Count,NEMA 14-50,NEMA 5-15,NEMA 5-20,J1772,CCS,CHAdeMO,Tesla,Facility Type,Street Address,City,State,Zip Code,Latitude,Longitude,Expected Date
474,40012,Available,2011-08-15,Municipal Garage,Non-Networked,LG,Free,NA,public,Public,24 hours daily; Drivers must bring their own J...,1,2,0,0,0,0,1,1,0,0,0,FLEET_GARAGE,200 N Holliday St,Baltimore,MD,21202,39.291785,-76.610539,NA
653,43190,Available,2012-01-15,UM PTS GRAND,ChargePoint Network,NA,NA,NA,public,Public,24 hours daily,0,2,0,0,0,0,0,1,0,0,0,None,5 N Paca St,Baltimore,MD,21201,39.290036,-76.621894,NA
654,43191,Available,2012-01-15,UM PTS PEARL #3,ChargePoint Network,NA,NA,NA,public,Public,24 hours daily,0,2,0,0,0,0,0,1,0,0,0,None,622 W Fayette St,Baltimore,MD,21201,39.290764,-76.624390,NA
655,43195,Available,2012-01-15,UM PTS PRATT,ChargePoint Network,NA,NA,NA,public,Public,24 hours daily,0,2,0,0,0,0,0,1,0,0,0,None,646 West Pratt Street,Baltimore,MD,21201,39.286510,-76.624935,NA
656,43196,Available,2012-01-15,UM PTS PLAZA #1,ChargePoint Network,NA,NA,NA,public,Public,24 hours daily,0,2,0,0,0,0,0,1,0,0,0,None,500 West Redwood Street,Baltimore,MD,21201,39.288080,-76.622679,NA

### Fuel Prices | Northeastern Region (incl. Maryland)

<div>Gas price data is unavailable via API at present but can be found at the following link:</div>
<div><a href="https://www.eia.gov/dnav/pet/hist/LeafHandler.ashx?n=PET&s=EMM_EPMR_PTE_R1Y_DPG&f=M">Gas Price Data</a></div>

In [28]:
# Pull the data
url = "https://api.eia.gov/v2/petroleum/pri/gnd/data/?frequency=monthly&data[0]=value&facets[series][]=EMM_EPMR_PTE_R1Y_DPG&sort[0][column]=period&sort[0][direction]=desc&offset=0&length=5000&api_key={}".format(NREL_ID)

response = requests.get(url)

# The data is returned as JSON
data = response.json()

print(data)
#
# # Assume the data is in the first series (you should adjust this according to the actual structure of the response)
# series_data = data['series'][0]['data']
#
# # Convert the data to a DataFrame
# df = pd.DataFrame(series_data, columns=['Date', 'Value'])
#
# # Print the DataFrame
# print(df)

{'response': {'total': 726, 'dateFormat': 'YYYY-MM', 'frequency': 'monthly', 'data': [{'period': '2023-06', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 3.572, 'units': '$/GAL'}, {'period': '2023-05', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 3.573, 'units': '$/GAL'}, {'period': '2023-04', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 3.554, 'units': '$/GAL'}, {'period': '2023-03', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 3.406, 'units': '$/GAL'}, {'period': '2023-02', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 3.458, 'units': '$/GAL'}, {'period': '2023-01', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 3.469, 'units': '$/GAL'}, {'period': '2022-12', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 3.472, 'units': '$/GAL'}, {'period': '2022-11', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 3.851, 'units': '$/GAL'}, {'period': '2022-10', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 3.702, 'units': '$/GAL'}, {'period': '2022-09', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 3.71, 'units': '$/GAL'}, {'period': '2022-08', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 4.175, 'units': '$/GAL'}, {'period': '2022-07', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 4.622, 'units': '$/GAL'}, {'period': '2022-06', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 4.921, 'units': '$/GAL'}, {'period': '2022-05', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 4.588, 'units': '$/GAL'}, {'period': '2022-04', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 4.105, 'units': '$/GAL'}, {'period': '2022-03', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 4.256, 'units': '$/GAL'}, {'period': '2022-02', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 3.632, 'units': '$/GAL'}, {'period': '2022-01', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 3.42, 'units': '$/GAL'}, {'period': '2021-12', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 3.444, 'units': '$/GAL'}, {'period': '2021-11', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 3.491, 'units': '$/GAL'}, {'period': '2021-10', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 3.363, 'units': '$/GAL'}, {'period': '2021-09', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 3.23, 'units': '$/GAL'}, {'period': '2021-08', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 3.18, 'units': '$/GAL'}, {'period': '2021-07', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 3.15, 'units': '$/GAL'}, {'period': '2021-06', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 3.084, 'units': '$/GAL'}, {'period': '2021-05', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 3.005, 'units': '$/GAL'}, {'period': '2021-04', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 2.863, 'units': '$/GAL'}, {'period': '2021-03', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 2.869, 'units': '$/GAL'}, {'period': '2021-02', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 2.625, 'units': '$/GAL'}, {'period': '2021-01', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 2.472, 'units': '$/GAL'}, {'period': '2020-12', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 2.337, 'units': '$/GAL'}, {'period': '2020-11', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 2.255, 'units': '$/GAL'}, {'period': '2020-10', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 2.276, 'units': '$/GAL'}, {'period': '2020-09', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 2.278, 'units': '$/GAL'}, {'period': '2020-08', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 2.253, 'units': '$/GAL'}, {'period': '2020-07', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 2.248, 'units': '$/GAL'}, {'period': '2020-06', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 2.162, 'units': '$/GAL'}, {'period': '2020-05', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 2.027, 'units': '$/GAL'}, {'period': '2020-04', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 2.061, 'units': '$/GAL'}, {'period': '2020-03', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 2.349, 'units': '$/GAL'}, {'period': '2020-02', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 2.526, 'units': '$/GAL'}, {'period': '2020-01', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 2.638, 'units': '$/GAL'}, {'period': '2019-12', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 2.604, 'units': '$/GAL'}, {'period': '2019-11', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 2.616, 'units': '$/GAL'}, {'period': '2019-10', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 2.605, 'units': '$/GAL'}, {'period': '2019-09', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 2.625, 'units': '$/GAL'}, {'period': '2019-08', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 2.712, 'units': '$/GAL'}, {'period': '2019-07', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 2.802, 'units': '$/GAL'}, {'period': '2019-06', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 2.771, 'units': '$/GAL'}, {'period': '2019-05', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 2.901, 'units': '$/GAL'}, {'period': '2019-04', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 2.807, 'units': '$/GAL'}, {'period': '2019-03', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 2.585, 'units': '$/GAL'}, {'period': '2019-02', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 2.407, 'units': '$/GAL'}, {'period': '2019-01', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 2.391, 'units': '$/GAL'}, {'period': '2018-12', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'series': 'EMM_EPMR_PTE_R1Y_DPG', 'series-description': 'Central Atlantic (PADD 1B) Regular All Formulations Retail Gasoline Prices (Dollars per Gallon)', 'value': 2.506, 'units': '$/GAL'}, {'period': '2018-11', 'duoarea': 'R1Y', 'area-name': 'PADD 1B', 'product': 'EPMR', 'product-name': 'Regular Gasoline', 'process': 'PTE', 'process-name': 'Retail Sales', 'seri

In [29]:
# Convert to dataframes

# Extract the data points
series_data = data['response']['data']

# Convert the data to a DataFrame
df = pd.DataFrame(series_data)
df['period'] = pd.to_datetime(df['period'])  # Convert 'period' column to datetime

df.head()

# Extract the gas prices
gas_prices = df[['period', 'value']]

# Rename the columns
gas_prices.columns = ['date', 'gas_price']

# Filter to specific date range
gas_prices = gas_prices[(gas_prices['date'] >= '2019-01-01') & (gas_prices['date'] <= '2023-12-01')]
gas_prices

         date  gas_price
0  2023-06-01      3.572
1  2023-05-01      3.573
2  2023-04-01      3.554
3  2023-03-01      3.406
4  2023-02-01      3.458
5  2023-01-01      3.469
6  2022-12-01      3.472
7  2022-11-01      3.851
8  2022-10-01      3.702
9  2022-09-01      3.710
10 2022-08-01      4.175
11 2022-07-01      4.622
12 2022-06-01      4.921
13 2022-05-01      4.588
14 2022-04-01      4.105
15 2022-03-01      4.256
16 2022-02-01      3.632
17 2022-01-01      3.420
18 2021-12-01      3.444
19 2021-11-01      3.491
20 2021-10-01      3.363
21 2021-09-01      3.230
22 2021-08-01      3.180
23 2021-07-01      3.150
24 2021-06-01      3.084
25 2021-05-01      3.005
26 2021-04-01      2.863
27 2021-03-01      2.869
28 2021-02-01      2.625
29 2021-01-01      2.472
30 2020-12-01      2.337
31 2020-11-01      2.255
32 2020-10-01      2.276
33 2020-09-01      2.278
34 2020-08-01      2.253
35 2020-07-01      2.248
36 2020-06-01      2.162
37 2020-05-01      2.027
38 2020-04-01      2.061
39 2020-03-01      2.349
40 2020-02-01      2.526
41 2020-01-01      2.638
42 2019-12-01      2.604
43 2019-11-01      2.616
44 2019-10-01      2.605
45 2019-09-01      2.625
46 2019-08-01      2.712
47 2019-07-01      2.802
48 2019-06-01      2.771
49 2019-05-01      2.901
50 2019-04-01      2.807
51 2019-03-01      2.585
52 2019-02-01      2.407
53 2019-01-01      2.391

### Electricity Prices | Maryland Electricity Price Data

In [30]:
# Pull the data
url = "https://api.eia.gov/v2/electricity/retail-sales/data/?frequency=monthly&data[0]=price&facets[stateid][]=MD&start=2019-01&sort[0][column]=period&sort[0][direction]=desc&offset=0&length=5000&api_key={}".format(NREL_ID)

response = requests.get(url)

# The data is returned as JSON
data = response.json()

print(data)

{'response': {'total': 312, 'dateFormat': 'YYYY-MM', 'frequency': 'monthly', 'data': [{'period': '2023-04', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'IND', 'sectorName': 'industrial', 'price': 9.61, 'price-units': 'cents per kilowatthour'}, {'period': '2023-04', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'OTH', 'sectorName': 'other', 'price': None, 'price-units': 'cents per kilowatthour'}, {'period': '2023-04', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'RES', 'sectorName': 'residential', 'price': 15.92, 'price-units': 'cents per kilowatthour'}, {'period': '2023-04', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'TRA', 'sectorName': 'transportation', 'price': 11.18, 'price-units': 'cents per kilowatthour'}, {'period': '2023-04', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'ALL', 'sectorName': 'all sectors', 'price': 13.87, 'price-units': 'cents per kilowatthour'}, {'period': '2023-04', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'COM', 'sectorName': 'commercial', 'price': 12.69, 'price-units': 'cents per kilowatthour'}, {'period': '2023-03', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'OTH', 'sectorName': 'other', 'price': None, 'price-units': 'cents per kilowatthour'}, {'period': '2023-03', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'RES', 'sectorName': 'residential', 'price': 15.76, 'price-units': 'cents per kilowatthour'}, {'period': '2023-03', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'TRA', 'sectorName': 'transportation', 'price': 10.36, 'price-units': 'cents per kilowatthour'}, {'period': '2023-03', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'ALL', 'sectorName': 'all sectors', 'price': 13.85, 'price-units': 'cents per kilowatthour'}, {'period': '2023-03', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'COM', 'sectorName': 'commercial', 'price': 12.56, 'price-units': 'cents per kilowatthour'}, {'period': '2023-03', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'IND', 'sectorName': 'industrial', 'price': 9.51, 'price-units': 'cents per kilowatthour'}, {'period': '2023-02', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'COM', 'sectorName': 'commercial', 'price': 14.22, 'price-units': 'cents per kilowatthour'}, {'period': '2023-02', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'ALL', 'sectorName': 'all sectors', 'price': 14.9, 'price-units': 'cents per kilowatthour'}, {'period': '2023-02', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'TRA', 'sectorName': 'transportation', 'price': 11.23, 'price-units': 'cents per kilowatthour'}, {'period': '2023-02', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'RES', 'sectorName': 'residential', 'price': 16.12, 'price-units': 'cents per kilowatthour'}, {'period': '2023-02', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'OTH', 'sectorName': 'other', 'price': None, 'price-units': 'cents per kilowatthour'}, {'period': '2023-02', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'IND', 'sectorName': 'industrial', 'price': 10.28, 'price-units': 'cents per kilowatthour'}, {'period': '2023-01', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'ALL', 'sectorName': 'all sectors', 'price': 15, 'price-units': 'cents per kilowatthour'}, {'period': '2023-01', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'TRA', 'sectorName': 'transportation', 'price': 10.79, 'price-units': 'cents per kilowatthour'}, {'period': '2023-01', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'RES', 'sectorName': 'residential', 'price': 15.87, 'price-units': 'cents per kilowatthour'}, {'period': '2023-01', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'OTH', 'sectorName': 'other', 'price': None, 'price-units': 'cents per kilowatthour'}, {'period': '2023-01', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'IND', 'sectorName': 'industrial', 'price': 10.34, 'price-units': 'cents per kilowatthour'}, {'period': '2023-01', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'COM', 'sectorName': 'commercial', 'price': 14.64, 'price-units': 'cents per kilowatthour'}, {'period': '2022-12', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'ALL', 'sectorName': 'all sectors', 'price': 14.7, 'price-units': 'cents per kilowatthour'}, {'period': '2022-12', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'TRA', 'sectorName': 'transportation', 'price': 10.36, 'price-units': 'cents per kilowatthour'}, {'period': '2022-12', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'RES', 'sectorName': 'residential', 'price': 15.56, 'price-units': 'cents per kilowatthour'}, {'period': '2022-12', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'OTH', 'sectorName': 'other', 'price': None, 'price-units': 'cents per kilowatthour'}, {'period': '2022-12', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'IND', 'sectorName': 'industrial', 'price': 11.19, 'price-units': 'cents per kilowatthour'}, {'period': '2022-12', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'COM', 'sectorName': 'commercial', 'price': 14.17, 'price-units': 'cents per kilowatthour'}, {'period': '2022-11', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'IND', 'sectorName': 'industrial', 'price': 9.8, 'price-units': 'cents per kilowatthour'}, {'period': '2022-11', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'OTH', 'sectorName': 'other', 'price': None, 'price-units': 'cents per kilowatthour'}, {'period': '2022-11', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'RES', 'sectorName': 'residential', 'price': 15.42, 'price-units': 'cents per kilowatthour'}, {'period': '2022-11', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'TRA', 'sectorName': 'transportation', 'price': 10.46, 'price-units': 'cents per kilowatthour'}, {'period': '2022-11', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'ALL', 'sectorName': 'all sectors', 'price': 13.89, 'price-units': 'cents per kilowatthour'}, {'period': '2022-11', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'COM', 'sectorName': 'commercial', 'price': 13.1, 'price-units': 'cents per kilowatthour'}, {'period': '2022-10', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'TRA', 'sectorName': 'transportation', 'price': 10.83, 'price-units': 'cents per kilowatthour'}, {'period': '2022-10', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'RES', 'sectorName': 'residential', 'price': 15.89, 'price-units': 'cents per kilowatthour'}, {'period': '2022-10', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'OTH', 'sectorName': 'other', 'price': None, 'price-units': 'cents per kilowatthour'}, {'period': '2022-10', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'IND', 'sectorName': 'industrial', 'price': 10.1, 'price-units': 'cents per kilowatthour'}, {'period': '2022-10', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'COM', 'sectorName': 'commercial', 'price': 13.64, 'price-units': 'cents per kilowatthour'}, {'period': '2022-10', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'ALL', 'sectorName': 'all sectors', 'price': 14.29, 'price-units': 'cents per kilowatthour'}, {'period': '2022-09', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'ALL', 'sectorName': 'all sectors', 'price': 13.6, 'price-units': 'cents per kilowatthour'}, {'period': '2022-09', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'TRA', 'sectorName': 'transportation', 'price': 11.18, 'price-units': 'cents per kilowatthour'}, {'period': '2022-09', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'RES', 'sectorName': 'residential', 'price': 14.61, 'price-units': 'cents per kilowatthour'}, {'period': '2022-09', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'OTH', 'sectorName': 'other', 'price': None, 'price-units': 'cents per kilowatthour'}, {'period': '2022-09', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'IND', 'sectorName': 'industrial', 'price': 10.63, 'price-units': 'cents per kilowatthour'}, {'period': '2022-09', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'COM', 'sectorName': 'commercial', 'price': 13.11, 'price-units': 'cents per kilowatthour'}, {'period': '2022-08', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'COM', 'sectorName': 'commercial', 'price': 13.1, 'price-units': 'cents per kilowatthour'}, {'period': '2022-08', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'IND', 'sectorName': 'industrial', 'price': 11.05, 'price-units': 'cents per kilowatthour'}, {'period': '2022-08', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'OTH', 'sectorName': 'other', 'price': None, 'price-units': 'cents per kilowatthour'}, {'period': '2022-08', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'RES', 'sectorName': 'residential', 'price': 14.3, 'price-units': 'cents per kilowatthour'}, {'period': '2022-08', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'TRA', 'sectorName': 'transportation', 'price': 11.41, 'price-units': 'cents per kilowatthour'}, {'period': '2022-08', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'ALL', 'sectorName': 'all sectors', 'price': 13.56, 'price-units': 'cents per kilowatthour'}, {'period': '2022-07', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'TRA', 'sectorName': 'transportation', 'price': 9.84, 'price-units': 'cents per kilowatthour'}, {'period': '2022-07', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'ALL', 'sectorName': 'all sectors', 'price': 13.41, 'price-units': 'cents per kilowatthour'}, {'period': '2022-07', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'RES', 'sectorName': 'residential', 'price': 14.28, 'price-units': 'cents per kilowatthour'}, {'period': '2022-07', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'OTH', 'sectorName': 'other', 'price': None, 'price-units': 'cents per kilowatthour'}, {'period': '2022-07', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'IND', 'sectorName': 'industrial', 'price': 10.64, 'price-units': 'cents per kilowatthour'}, {'period': '2022-07', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'COM', 'sectorName': 'commercial', 'price': 12.85, 'price-units': 'cents per kilowatthour'}, {'period': '2022-06', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'ALL', 'sectorName': 'all sectors', 'price': 13.47, 'price-units': 'cents per kilowatthour'}, {'period': '2022-06', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'TRA', 'sectorName': 'transportation', 'price': 8.67, 'price-units': 'cents per kilowatthour'}, {'period': '2022-06', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'RES', 'sectorName': 'residential', 'price': 14.67, 'price-units': 'cents per kilowatthour'}, {'period': '2022-06', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'OTH', 'sectorName': 'other', 'price': None, 'price-units': 'cents per kilowatthour'}, {'period': '2022-06', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'IND', 'sectorName': 'industrial', 'price': 10.51, 'price-units': 'cents per kilowatthour'}, {'period': '2022-06', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'COM', 'sectorName': 'commercial', 'price': 12.78, 'price-units': 'cents per kilowatthour'}, {'period': '2022-05', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'TRA', 'sectorName': 'transportation', 'price': 8.3, 'price-units': 'cents per kilowatthour'}, {'period': '2022-05', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'ALL', 'sectorName': 'all sectors', 'price': 12.68, 'price-units': 'cents per kilowatthour'}, {'period': '2022-05', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'RES', 'sectorName': 'residential', 'price': 14.22, 'price-units': 'cents per kilowatthour'}, {'period': '2022-05', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'COM', 'sectorName': 'commercial', 'price': 11.85, 'price-units': 'cents per kilowatthour'}, {'period': '2022-05', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'IND', 'sectorName': 'industrial', 'price': 9.88, 'price-units': 'cents per kilowatthour'}, {'period': '2022-05', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'OTH', 'sectorName': 'other', 'price': None, 'price-units': 'cents per kilowatthour'}, {'period': '2022-04', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'ALL', 'sectorName': 'all sectors', 'price': 12.57, 'price-units': 'cents per kilowatthour'}, {'period': '2022-04', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'TRA', 'sectorName': 'transportation', 'price': 8.38, 'price-units': 'cents per kilowatthour'}, {'period': '2022-04', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'RES', 'sectorName': 'residential', 'price': 14.17, 'price-units': 'cents per kilowatthour'}, {'period': '2022-04', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'OTH', 'sectorName': 'other', 'price': None, 'price-units': 'cents per kilowatthour'}, {'period': '2022-04', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'IND', 'sectorName': 'industrial', 'price': 9.52, 'price-units': 'cents per kilowatthour'}, {'period': '2022-04', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'COM', 'sectorName': 'commercial', 'price': 11.6, 'price-units': 'cents per kilowatthour'}, {'period': '2022-03', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'ALL', 'sectorName': 'all sectors', 'price': 12.52, 'price-units': 'cents per kilowatthour'}, {'period': '2022-03', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'TRA', 'sectorName': 'transportation', 'price': 7.83, 'price-units': 'cents per kilowatthour'}, {'period': '2022-03', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'IND', 'sectorName': 'industrial', 'price': 8.81, 'price-units': 'cents per kilowatthour'}, {'period': '2022-03', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'OTH', 'sectorName': 'other', 'price': None, 'price-units': 'cents per kilowatthour'}, {'period': '2022-03', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'RES', 'sectorName': 'residential', 'price': 14.18, 'price-units': 'cents per kilowatthour'}, {'period': '2022-03', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'COM', 'sectorName': 'commercial', 'price': 11.42, 'price-units': 'cents per kilowatthour'}, {'period': '2022-02', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'IND', 'sectorName': 'industrial', 'price': 9.4, 'price-units': 'cents per kilowatthour'}, {'period': '2022-02', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'COM', 'sectorName': 'commercial', 'price': 12.33, 'price-units': 'cents per kilowatthour'}, {'period': '2022-02', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'ALL', 'sectorName': 'all sectors', 'price': 13.05, 'price-units': 'cents per kilowatthour'}, {'period': '2022-02', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'TRA', 'sectorName': 'transportation', 'price': 8.08, 'price-units': 'cents per kilowatthour'}, {'period': '2022-02', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'RES', 'sectorName': 'residential', 'price': 14.08, 'price-units': 'cents per kilowatthour'}, {'period': '2022-02', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'OTH', 'sectorName': 'other', 'price': None, 'price-units': 'cents per kilowatthour'}, {'period': '2022-01', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'ALL', 'sectorName': 'all sectors', 'price': 12.49, 'price-units': 'cents per kilowatthour'}, {'period': '2022-01', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'TRA', 'sectorName': 'transportation', 'price': 7.99, 'price-units': 'cents per kilowatthour'}, {'period': '2022-01', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'COM', 'sectorName': 'commercial', 'price': 11.73, 'price-units': 'cents per kilowatthour'}, {'period': '2022-01', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'OTH', 'sectorName': 'other', 'price': None, 'price-units': 'cents per kilowatthour'}, {'period': '2022-01', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'IND', 'sectorName': 'industrial', 'price': 9.44, 'price-units': 'cents per kilowatthour'}, {'period': '2022-01', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'RES', 'sectorName': 'residential', 'price': 13.41, 'price-units': 'cents per kilowatthour'}, {'period': '2021-12', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'COM', 'sectorName': 'commercial', 'price': 11.48, 'price-units': 'cents per kilowatthour'}, {'period': '2021-12', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'ALL', 'sectorName': 'all sectors', 'price': 12.57, 'price-units': 'cents per kilowatthour'}, {'period': '2021-12', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'IND', 'sectorName': 'industrial', 'price': 9.1, 'price-units': 'cents per kilowatthour'}, {'period': '2021-12', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'OTH', 'sectorName': 'other', 'price': None, 'price-units': 'cents per kilowatthour'}, {'period': '2021-12', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'RES', 'sectorName': 'residential', 'price': 14.07, 'price-units': 'cents per kilowatthour'}, {'period': '2021-12', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'TRA', 'sectorName': 'transportation', 'price': 7.87, 'price-units': 'cents per kilowatthour'}, {'period': '2021-11', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'IND', 'sectorName': 'industrial', 'price': 9.21, 'price-units': 'cents per kilowatthour'}, {'period': '2021-11', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'OTH', 'sectorName': 'other', 'price': None, 'price-units': 'cents per kilowatthour'}, {'period': '2021-11', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'RES', 'sectorName': 'residential', 'price': 13.65, 'price-units': 'cents per kilowatthour'}, {'period': '2021-11', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'TRA', 'sectorName': 'transportation', 'price': 8.16, 'price-units': 'cents per kilowatthour'}, {'period': '2021-11', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'ALL', 'sectorName': 'all sectors', 'price': 11.99, 'price-units': 'cents per kilowatthour'}, {'period': '2021-11', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'COM', 'sectorName': 'commercial', 'price': 10.81, 'price-units': 'cents per kilowatthour'}, {'period': '2021-10', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'ALL', 'sectorName': 'all sectors', 'price': 12.07, 'price-units': 'cents per kilowatthour'}, {'period': '2021-10', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'TRA', 'sectorName': 'transportation', 'price': 8.03, 'price-units': 'cents per kilowatthour'}, {'period': '2021-10', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'RES', 'sectorName': 'residential', 'price': 14.5, 'price-units': 'cents per kilowatthour'}, {'period': '2021-10', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'OTH', 'sectorName': 'other', 'price': None, 'price-units': 'cents per kilowatthour'}, {'period': '2021-10', 'stateid': 'MD', 'stateDescription': 'Maryland', 'sectorid': 'IND', 'sectorName': 'industrial', 'price': 8.91, 'price-units': 'cents per kilowatthour'}, {'period': '2021-10', 'stateid': 'MD', 'stateDescription': 'Mar

In [31]:
# Convert to dataframes
# Convert to dataframes

# Extract the data points
series_data = data['response']['data']

# Convert the data to a DataFrame
df = pd.DataFrame(series_data)
df['period'] = pd.to_datetime(df['period'])  # Convert 'period' column to datetime

# Filter to sectorName colume to residential
df = df[df['sectorName'] == 'residential']

# Extract electricity prices
electricity_prices = df[['period', 'price']]

# Rename the columns
electricity_prices.columns = ['date', 'resi_electricity_price']

# Filter to specific date range
electricity_prices = electricity_prices[(electricity_prices['date'] >= '2019-01-01') & (electricity_prices['date'] <= '2023-12-01')]

# Index by date
electricity_prices = electricity_prices.set_index('date')

electricity_prices

            resi_electricity_price
date
2023-04-01                   15.92
2023-03-01                   15.76
2023-02-01                   16.12
2023-01-01                   15.87
2022-12-01                   15.56
2022-11-01                   15.42
2022-10-01                   15.89
2022-09-01                   14.61
2022-08-01                   14.30
2022-07-01                   14.28
2022-06-01                   14.67
2022-05-01                   14.22
2022-04-01                   14.17
2022-03-01                   14.18
2022-02-01                   14.08
2022-01-01                   13.41
2021-12-01                   14.07
2021-11-01                   13.65
2021-10-01                   14.50
2021-09-01                   13.28
2021-08-01                   12.89
2021-07-01                   12.95
2021-06-01                   13.07
2021-05-01                   12.88
2021-04-01                   12.96
2021-03-01                   12.78
2021-02-01                   12.47
2021-01-01                   12.60
2020-12-01                   12.72
2020-11-01                   13.25
2020-10-01                   13.82
2020-09-01                   12.93
2020-08-01                   12.47
2020-07-01                   12.22
2020-06-01                   12.83
2020-05-01                   13.21
2020-04-01                   13.20
2020-03-01                   13.58
2020-02-01                   13.35
2020-01-01                   13.41
2019-12-01                   12.85
2019-11-01                   12.78
2019-10-01                   14.05
2019-09-01                   12.82
2019-08-01                   12.45
2019-07-01                   12.52
2019-06-01                   13.25
2019-05-01                   13.48
2019-04-01                   14.24
2019-03-01                   13.44
2019-02-01                   13.40
2019-01-01                   13.07

### Geospatial Data - Maps of Counties and Neigbborhoods

#### Gather Maryland County Coordinates and Locational Data

In [32]:
import requests

url = 'https://raw.githubusercontent.com/frankrowe/maryland-geojson/master/maryland-counties.geojson'
response = requests.get(url)

with open('maryland-counties.geojson', 'w') as file:
    file.write(response.text)

with open('maryland-counties.geojson', 'r') as file:
    maryland_counties = file.read()

counties = json.loads(maryland_counties)
counties = counties['features']
counties[0]

{'type': 'Feature',
 'properties': {'name': 'Allegany'},
 'geometry': {'type': 'Polygon',
  'coordinates': [[[-78.72247849700874, 39.72293680259466],
    [-78.34273160144357, 39.72245780651755],
    [-78.34603570538482, 39.72132852481378],
    [-78.34078320859582, 39.716239266427365],
    [-78.33828435426172, 39.716772506811225],
    [-78.3362139385028, 39.71990977860767],
    [-78.33356195554411, 39.71899928707819],
    [-78.33183831010778, 39.71446936687261],
    [-78.329167802137, 39.712280300846366],
    [-78.33420965187652, 39.71257069623337],
    [-78.33434352854464, 39.70990131981943],
    [-78.31836983766253, 39.702583041971636],
    [-78.3173195949011, 39.69930848103388],
    [-78.31985331880286, 39.69574118937848],
    [-78.31333257364668, 39.69239895921175],
    [-78.31663150625955, 39.68910520182264],
    [-78.32280614451973, 39.68900721927672],
    [-78.32202451617927, 39.68736973541037],
    [-78.314922794248, 39.685563439381646],
    [-78.3166051204736, 39.68316600240325],
    [-78.32169310344263, 39.68471191673257],
    [-78.32302688169108, 39.68376145856472],
    [-78.32238483191902, 39.682057138077305],
    [-78.31804832213604, 39.68153993629135],
    [-78.32161583745842, 39.6785847179325],
    [-78.32014613390587, 39.6762804621158],
    [-78.32453539296235, 39.67762374766562],
    [-78.326838156586, 39.676559637371824],
    [-78.3362911915986, 39.68064745497688],
    [-78.34304211613117, 39.67658803616527],
    [-78.34354574841034, 39.67543647196563],
    [-78.3400297581208, 39.671661749471106],
    [-78.3362215421021, 39.67076936240103],
    [-78.33536855304622, 39.66710241365768],
    [-78.33327018972088, 39.666428116124635],
    [-78.33385829178712, 39.66291293760856],
    [-78.33992473354296, 39.66415691401776],
    [-78.34962338378638, 39.66052191205508],
    [-78.35377984104788, 39.661489646678284],
    [-78.35652456996448, 39.66400148852158],
    [-78.35740737086299, 39.6632465630119],
    [-78.35499333911687, 39.660184824935],
    [-78.36130833639697, 39.6611710354387],
    [-78.36347337714085, 39.660072726781465],
    [-78.36216299731518, 39.65829654936742],
    [-78.35721763122986, 39.65777330134663],
    [-78.35340971841171, 39.655401999550996],
    [-78.34001770130097, 39.65274810238161],
    [-78.34068874264547, 39.64856319082198],
    [-78.34532701260858, 39.649868535597264],
    [-78.34618256415152, 39.648863296336486],
    [-78.34238037988615, 39.64406799584436],
    [-78.33445046521828, 39.6416354270812],
    [-78.33411812644874, 39.63702145443876],
    [-78.35613149209429, 39.64063178105563],
    [-78.35977561435845, 39.63799787138411],
    [-78.35394361207437, 39.63070387016217],
    [-78.35414783908358, 39.62765042474732],
    [-78.35604061243966, 39.626174869185476],
    [-78.36177834365124, 39.62599625924248],
    [-78.37343561813267, 39.630375869354204],
    [-78.3822236207595, 39.62859086866566],
    [-78.38322862066296, 39.62216286735455],
    [-78.37267461673757, 39.612212865786304],
    [-78.37347061680957, 39.6094458652079],
    [-78.37620261758843, 39.60829786487634],
    [-78.3840116066746, 39.60922354305474],
    [-78.39609762428209, 39.61599286564193],
    [-78.42190250175962, 39.62434399375366],
    [-78.4296316352269, 39.623664865880855],
    [-78.43356563625015, 39.62048586510124],
    [-78.43389163620422, 39.61817586463147],
    [-78.42584963301687, 39.60751586282786],
    [-78.41313962846246, 39.598226861473016],
    [-78.3977406231476, 39.59014786045954],
    [-78.39535062206305, 39.58481685949425],
    [-78.39922462303059, 39.581044858598986],
    [-78.40779366329402, 39.57865890304337],
    [-78.41800712941644, 39.58099000240264],
    [-78.42368342471805, 39.58523149730166],
    [-78.44373528183597, 39.591530299315394],
    [-78.4520443650934, 39.59002986427808],
    [-78.45745564157778, 39.58729585761619],
    [-78.4587246415763, 39.58107385633509],
    [-78.45464463986897, 39.57423485513578],
    [-78.43768063386912, 39.563027853561884],
    [-78.42807763064538, 39.55939085320698],
    [-78.41998262765874, 39.55209285206831],
    [-78.41803462674476, 39.54726585118525],
    [-78.42101962752822, 39.5449568506136],
    [-78.42500517813872, 39.54540604681248],
    [-78.43039114910461, 39.55164440750491],
    [-78.43771063326565, 39.55339785165154],
    [-78.43954263366335, 39.550676851042105],
    [-78.43534763190539, 39.5435858497958],
    [-78.43567263179442, 39.54024584912102],
    [-78.4377106323334, 39.53873684874398],
    [-78.45085669715075, 39.5502248719141],
    [-78.46098035597335, 39.550893160411725],
    [-78.46235064062219, 39.54836384971371],
    [-78.46042963986649, 39.54589384929724],
    [-78.45047263661621, 39.543561849214576],
    [-78.448906635948, 39.54072584871186],
    [-78.45046455461382, 39.53813130724064],
    [-78.45809528368115, 39.53855513817152],
    [-78.4624946399058, 39.536400847336],
    [-78.46332063997987, 39.53351884673283],
    [-78.46122063884144, 39.525901845301995],
    [-78.46316863912108, 39.52075484420664],
    [-78.46890864065145, 39.51670384318412],
    [-78.47396944771066, 39.51621892730658],
    [-78.48347984233614, 39.519583593563375],
    [-78.48980990975552, 39.51781081612109],
    [-78.50305025250577, 39.51875496634068],
    [-78.5229001051512, 39.52503471689917],
    [-78.56578022742438, 39.51951670113857],
    [-78.57864904115739, 39.52692652074815],
    [-78.58734567824273, 39.527935840887025],
    [-78.59200662573762, 39.53153129635709],
    [-78.5898118264534, 39.53584645765932],
    [-78.59121045019754, 39.53698075767169],
    [-78.60318219055713, 39.53242641021377],
    [-78.60642826114852, 39.53500780276639],
    [-78.62267324170199, 39.539627003097436],
    [-78.6284788843871, 39.53945698574337],
    [-78.63101331132488, 39.53711213587322],
    [-78.65704958167098, 39.53515273771126],
    [-78.66417904903587, 39.53707761930583],
    [-78.66801076732102, 39.54031261926249],
    [-78.675572190897, 39.540357928295535],
    [-78.68121158635304, 39.54397674574081],
    [-78.68954707907162, 39.54599315615564],
    [-78.69483590835706, 39.55394469289532],
    [-78.70743630180253, 39.556041485704526],
    [-78.7138078763136, 39.56281337366109],
    [-78.72423139264221, 39.56394849192248],
    [-78.73148154168425, 39.574806126653655],
    [-78.73324885003149, 39.58658294667052],
    [-78.73974966916633, 39.58638238745911],
    [-78.7455669792112, 39.579763699895395],
    [-78.75122198552985, 39.58195103727415],
    [-78.75717590712657, 39.58108072196374],
    [-78.76673344931599, 39.58735421745457],
    [-78.77009829174247, 39.5947687268542],
    [-78.7779062760892, 39.60142983297856],
    [-78.77698311315449, 39.60391819826244],
    [-78.76831184010925, 39.60862996516193],
    [-78.75267673496626, 39.61008085078848],
    [-78.74732573301284, 39.60560985011141],
    [-78.73319766023972, 39.61462223069072],
    [-78.73670830556757, 39.622356575427084],
    [-78.747194460353, 39.62689521347861],
    [-78.76342163870005, 39.619046192843776],
    [-78.77798207610083, 39.6223025635673],
    [-78.77646420173714, 39.62890660527106],
    [-78.76532910523999, 39.6443831749904],
    [-78.76630761764243, 39.64843678838755],
    [-78.76900880821098, 39.64631464364955],
    [-78.77590800007941, 39.64531891836695],
    [-78.78151989252892, 39.636828739046926],
    [-78.79056587007281, 39.63841223078095],
    [-78.79620275026167, 39.63720785446433],
    [-78.79770275022348, 39.629407852866265],
    [-78.80200275143186, 39.627407852304955],
    [-78.7962867488217, 39.614543849985374],
    [-78.79611874827242, 39.606853848472596],
    [-78.79955002832983, 39.60513425417933],
    [-78.801743585689, 39.60705521033092],
    [-78.80960775254114, 39.60798284817413],
    [-78.81292227105317, 39.59715932200723],
    [-78.81868575446504, 39.59406684507345],
    [-78.8191597543685, 39.590289844308764],
    [-78.82439832806683, 39.59039468029288],
    [-78.82626975647987, 39.58874884372932],
    [-78.82662075584655, 39.57725184144334],
    [-78.82085275400343, 39.57648084151386],
    [-78.81377275123148, 39.567638840039265],
    [-78.81693430550321, 39.56190149329685],
    [-78.82133944568206, 39.56065789416927],
    [-78.83006767715669, 39.565232561318346],
    [-78.83960575922332, 39.567020838918715],
    [-78.84362114620913, 39.562702350109376],
    [-78.8472682538015, 39.56258087439784],
    [-78.85145576244395, 39.55984283704131],
    [-78.85219076215118, 39.551766835415826],
    [-78.86193476449185, 39.541101832929726],
    [-78.87052938419718, 39.53895314410874],
    [-78.869332966373, 39.53182125665287],
    [-78.87485465760938, 39.52275324911016],
    [-78.87951774197035, 39.52147693940016],
    [-78.88741774120389, 39.52343135277299],
    [-78.8891011224075, 39.52519368102314],
    [-78.89262709044827, 39.52445922372829],
    [-78.89139677214521, 39.51781082718275],
    [-78.89294776576692, 39.51323406180589],
    [-78.9051951838426, 39.51184016853128],
    [-78.90383877515404, 39.504522824071834],
    [-78.90891177622667, 39.49671482233019],
    [-78.91381877756335, 39.49380282156401],
    [-78.91755737772002, 39.48601766699065],
    [-78.92530010532926, 39.48736647043929],
    [-78.93444747932158, 39.48615255673104],
    [-78.94237433705734, 39.480830557137764],
    [-78.94237178542127, 39.47813481735772],
    [-78.93912478414772, 39.47401581666768],
    [-78.9466392509766, 39.46628079340542],
    [-78.9586316348177, 39.46320739566849],
    [-78.95928278950024, 39.45994481310128],
    [-78.95473678770769, 39.454019812103496],
    [-78.9606137893314, 39.45090181125847],
    [-78.95621078773556, 39.447338810722805],
    [-78.95617978731828, 39.44100080946823],
    [-78.96555966319936, 39.438423794029376],
    [-78.96946036722211, 39.44356074178765],
    [-78.97744531834331, 39.44836969525944],
    [-79.01038614805181, 39.46099297170505],
    [-79.01811422968036, 39.467838618377286],
    [-79.0284108112804, 39.464974811419864],
    [-79.0323545654253, 39.466259404155686],
    [-79.03608375317947, 39.47138024891643],
    [-79.03699236104647, 39.47681190151682],
    [-79.04354781692969, 39.4797128137494],
    [-79.04652781811332, 39.483716814425925],
    [-79.0526988199321, 39.48223081389228],
    [-79.05624382032674, 39.471317811595334],
    [-79.05836882097272, 39.47111181147206],
    [-79.06435023645948, 39.47899325505941],
    [-79.06698538818925, 39.47971387664887],
    [-78.91402639128512, 39.722736582347856],
    [-78.72247849700874, 39.72293680259466]]]}}

#### Gather Baltimore Neighborhood Coordinates and Locational Data

<a href="https://github.com/blackmad/neighborhoods">Link to Neighborhood JSON</a>

In [33]:
url = 'https://raw.githubusercontent.com/codeforgermany/click_that_hood/main/public/data/baltimore.geojson'
response = requests.get(url)

with open('baltimore.geojson', 'w') as file:
    file.write(response.text)

with open('baltimore.geojson', 'r') as file:
    baltimore_neighborhoods = file.read()

baltimore_neighborhoods = json.loads(baltimore_neighborhoods)
baltimore_neighborhoods = baltimore_neighborhoods['features']
baltimore_neighborhoods[0]

{'type': 'Feature',
 'properties': {'name': 'Armistead Gardens',
  'cartodb_id': 5,
  'created_at': '2013-11-12T15:45:44Z',
  'updated_at': '2013-11-12T15:45:44Z'},
 'geometry': {'type': 'MultiPolygon',
  'coordinates': [[[[-76.5588, 39.306457],
     [-76.55892, 39.306536],
     [-76.559181, 39.306711],
     [-76.559334, 39.306809],
     [-76.559387, 39.306847],
     [-76.55994, 39.307247],
     [-76.560362, 39.307539],
     [-76.56074, 39.307814],
     [-76.561224, 39.308173],
     [-76.56136, 39.308271],
     [-76.560687, 39.308707],
     [-76.560426, 39.308846],
     [-76.559794, 39.309183],
     [-76.55842, 39.309915],
     [-76.558332, 39.309966],
     [-76.558005, 39.310157],
     [-76.557638, 39.310351],
     [-76.557575, 39.31038],
     [-76.555834, 39.311363],
     [-76.555223, 39.311682],
     [-76.555006, 39.311834],
     [-76.5546, 39.312104],
     [-76.550387, 39.314907],
     [-76.549787, 39.315307],
     [-76.549164, 39.315691],
     [-76.549164, 39.31567],
     [-76.549164, 39.315641],
     [-76.549164, 39.31563],
     [-76.549168, 39.31562],
     [-76.549188, 39.315575],
     [-76.549207, 39.315535],
     [-76.549214, 39.315519],
     [-76.549215, 39.315507],
     [-76.549211, 39.315496],
     [-76.549208, 39.315485],
     [-76.549214, 39.315468],
     [-76.549236, 39.315439],
     [-76.549239, 39.315434],
     [-76.549239, 39.315427],
     [-76.549236, 39.315421],
     [-76.54923, 39.315395],
     [-76.549232, 39.315391],
     [-76.549242, 39.315387],
     [-76.549248, 39.315386],
     [-76.549253, 39.315383],
     [-76.549268, 39.315343],
     [-76.549268, 39.315338],
     [-76.549265, 39.315336],
     [-76.54926, 39.315332],
     [-76.549257, 39.315316],
     [-76.549257, 39.315309],
     [-76.549262, 39.315305],
     [-76.549282, 39.315306],
     [-76.54929, 39.315304],
     [-76.549294, 39.3153],
     [-76.549297, 39.31529],
     [-76.549294, 39.315288],
     [-76.549286, 39.315284],
     [-76.549282, 39.31528],
     [-76.54928, 39.315272],
     [-76.549284, 39.315251],
     [-76.549288, 39.315247],
     [-76.549295, 39.315243],
     [-76.5493, 39.315239],
     [-76.549326, 39.315178],
     [-76.549327, 39.315162],
     [-76.549325, 39.315149],
     [-76.549318, 39.315125],
     [-76.549309, 39.315098],
     [-76.549305, 39.31508],
     [-76.549307, 39.315065],
     [-76.549315, 39.315039],
     [-76.549326, 39.315006],
     [-76.549336, 39.314964],
     [-76.549356, 39.314922],
     [-76.549382, 39.314864],
     [-76.54941, 39.314809],
     [-76.549413, 39.314803],
     [-76.549436, 39.314751],
     [-76.549456, 39.314724],
     [-76.549466, 39.314713],
     [-76.549472, 39.31471],
     [-76.549489, 39.314704],
     [-76.549507, 39.314701],
     [-76.549513, 39.314698],
     [-76.549515, 39.314696],
     [-76.549517, 39.314693],
     [-76.549536, 39.31463],
     [-76.549568, 39.314557],
     [-76.549607, 39.314465],
     [-76.549635, 39.314396],
     [-76.549653, 39.314336],
     [-76.549667, 39.314274],
     [-76.549681, 39.314239],
     [-76.549684, 39.314221],
     [-76.549689, 39.314168],
     [-76.549693, 39.314125],
     [-76.549692, 39.314094],
     [-76.549685, 39.314055],
     [-76.549685, 39.314019],
     [-76.549683, 39.314005],
     [-76.549674, 39.313991],
     [-76.549658, 39.313959],
     [-76.549644, 39.313918],
     [-76.549623, 39.313879],
     [-76.549614, 39.313854],
     [-76.549605, 39.313797],
     [-76.549612, 39.313768],
     [-76.549611, 39.313737],
     [-76.549605, 39.313716],
     [-76.549609, 39.313713],
     [-76.549614, 39.313711],
     [-76.549623, 39.313712],
     [-76.549632, 39.313714],
     [-76.549651, 39.313716],
     [-76.549663, 39.313716],
     [-76.549682, 39.313709],
     [-76.549691, 39.313703],
     [-76.549708, 39.313697],
     [-76.549718, 39.313693],
     [-76.549723, 39.313685],
     [-76.549724, 39.313679],
     [-76.549721, 39.313676],
     [-76.549715, 39.313674],
     [-76.549704, 39.313673],
     [-76.549692, 39.313673],
     [-76.549675, 39.313669],
     [-76.549654, 39.313658],
     [-76.549627, 39.313638],
     [-76.549609, 39.313614],
     [-76.549597, 39.313595],
     [-76.549587, 39.313572],
     [-76.549575, 39.313533],
     [-76.549571, 39.313531],
     [-76.549563, 39.313528],
     [-76.549558, 39.313528],
     [-76.549553, 39.31353],
     [-76.549549, 39.313534],
     [-76.549547, 39.313539],
     [-76.549546, 39.313546],
     [-76.549559, 39.313604],
     [-76.549577, 39.3137],
     [-76.549589, 39.313771],
     [-76.549588, 39.313779],
     [-76.549583, 39.313784],
     [-76.549577, 39.313784],
     [-76.549569, 39.313781],
     [-76.549555, 39.313758],
     [-76.549538, 39.313739],
     [-76.549518, 39.313707],
     [-76.5495, 39.313685],
     [-76.549487, 39.313671],
     [-76.54947, 39.313656],
     [-76.549449, 39.313643],
     [-76.54941, 39.313628],
     [-76.549404, 39.313622],
     [-76.549402, 39.313617],
     [-76.549403, 39.313611],
     [-76.549414, 39.313577],
     [-76.549433, 39.313521],
     [-76.549452, 39.313477],
     [-76.549459, 39.313466],
     [-76.54948, 39.313451],
     [-76.549487, 39.313439],
     [-76.549493, 39.31343],
     [-76.549501, 39.313425],
     [-76.549511, 39.313425],
     [-76.549518, 39.313421],
     [-76.549554, 39.313378],
     [-76.5496, 39.313325],
     [-76.549645, 39.313272],
     [-76.549682, 39.31323],
     [-76.549708, 39.313191],
     [-76.549736, 39.313155],
     [-76.549759, 39.313131],
     [-76.5498, 39.313095],
     [-76.549907, 39.313019],
     [-76.549975, 39.312966],
     [-76.549984, 39.312962],
     [-76.549998, 39.312954],
     [-76.55001, 39.312944],
     [-76.550028, 39.312925],
     [-76.550039, 39.312916],
     [-76.550055, 39.312909],
     [-76.550069, 39.312903],
     [-76.550079, 39.312897],
     [-76.550084, 39.312891],
     [-76.550123, 39.312847],
     [-76.550128, 39.312843],
     [-76.550133, 39.312841],
     [-76.55015, 39.31284],
     [-76.55016, 39.312837],
     [-76.550169, 39.312831],
     [-76.550237, 39.312764],
     [-76.550259, 39.31273],
     [-76.550268, 39.312717],
     [-76.550276, 39.312707],
     [-76.550282, 39.312704],
     [-76.550292, 39.3127],
     [-76.550299, 39.312694],
     [-76.550361, 39.312646],
     [-76.550391, 39.312624],
     [-76.550417, 39.312601],
     [-76.550459, 39.312562],
     [-76.550474, 39.312543],
     [-76.550488, 39.312525],
     [-76.550499, 39.312504],
     [-76.550514, 39.312478],
     [-76.55057, 39.312402],
     [-76.550617, 39.312332],
     [-76.550651, 39.312278],
     [-76.550669, 39.312248],
     [-76.550681, 39.312223],
     [-76.55069, 39.312196],
     [-76.550701, 39.312174],
     [-76.550713, 39.312148],
     [-76.550729, 39.312112],
     [-76.550746, 39.312068],
     [-76.55076, 39.312025],
     [-76.550772, 39.311989],
     [-76.550789, 39.311956],
     [-76.550802, 39.31193],
     [-76.550813, 39.311915],
     [-76.550821, 39.311897],
     [-76.550834, 39.311855],
     [-76.550842, 39.311827],
     [-76.550851, 39.311811],
     [-76.550873, 39.311771],
     [-76.550881, 39.31175],
     [-76.550892, 39.311712],
     [-76.550905, 39.311646],
     [-76.550911, 39.311586],
     [-76.550911, 39.311551],
     [-76.550912, 39.311533],
     [-76.550911, 39.311514],
     [-76.550924, 39.311429],
     [-76.550916, 39.311415],
     [-76.550899, 39.311389],
     [-76.550865, 39.311363],
     [-76.550838, 39.311352],
     [-76.550816, 39.311351],
     [-76.550789, 39.311352],
     [-76.550766, 39.311354],
     [-76.55074, 39.311352],
     [-76.550691, 39.311336],
     [-76.550648, 39.311324],
     [-76.5506, 39.311311],
     [-76.550561, 39.311304],
     [-76.55051, 39.311304],
     [-76.550478, 39.311306],
     [-76.550429, 39.311308],
     [-76.550411, 39.31131],
     [-76.550397, 39.311313],
     [-76.550384, 39.311316],
     [-76.550367, 39.311321],
     [-76.550356, 39.31132],
     [-76.550348, 39.311317],
     [-76.550342, 39.31131],
     [-76.550337, 39.311307],
     [-76.550327, 39.311306],
     [-76.550317, 39.311306],
     [-76.550308, 39.311306],
     [-76.550296, 39.311305],
     [-76.550288, 39.311305],
     [-76.550279, 39.311305],
     [-76.550268, 39.311305],
     [-76.550258, 39.311305],
     [-76.550248, 39.311304],
     [-76.550237, 39.311304],
     [-76.550227, 39.311304],
     [-76.550218, 39.311304],
     [-76.550207, 39.311304],
     [-76.550197, 39.311304],
     [-76.550184, 39.311304],
     [-76.550173, 39.311304],
     [-76.550159, 39.311304],
     [-76.550145, 39.311304],
     [-76.550134, 39.311304],
     [-76.550122, 39.311304],
     [-76.550114, 39.311302],
     [-76.550103, 39.311301],
     [-76.550098, 39.311305],
     [-76.550089, 39.311312],
     [-76.550082, 39.311312],
     [-76.550071, 39.311312],
     [-76.550057, 39.311312],
     [-76.550042, 39.311312],
     [-76.550027, 39.311312],
     [-76.550011, 39.311314],
     [-76.549998, 39.311315],
     [-76.549984, 39.311315],
     [-76.549968, 39.311313],
     [-76.549953, 39.311309],
     [-76.549937, 39.311308],
     [-76.549925, 39.311303],
     [-76.549916, 39.311295],
     [-76.549904, 39.311289],
     [-76.549894, 39.311285],
     [-76.549879, 39.311283],
     [-76.549864, 39.311282],
     [-76.549848, 39.311281],
     [-76.549832, 39.311278],
     [-76.549817, 39.311278],
     [-76.549802, 39.311278],
     [-76.549786, 39.311277],
     [-76.549771, 39.311277],
     [-76.549758, 39.311277],
     [-76.549743, 39.311279],
     [-76.549728, 39.311281],
     [-76.549714, 39.311287],
     [-76.549703, 39.311294],
     [-76.549692, 39.311301],
     [-76.549677, 39.311302],
     [-76.549663, 39.311302],
     [-76.549646, 39.311302],
     [-76.54963, 39.311303],
     [-76.549609, 39.311305],
     [-76.549589, 39.311306],
     [-76.549566, 39.31131],
     [-76.549545, 39.311313],
     [-76.549525, 39.311314],
     [-76.549502, 39.311315],
     [-76.549481, 39.311315],
     [-76.549463, 39.311315],
     [-76.54944, 39.311313],
     [-76.549418, 39.31131],
     [-76.5494, 39.311309],
     [-76.549381, 39.311308],
     [-76.549365, 39.311308],
     [-76.549346, 39.311311],
     [-76.549329, 39.311313],
     [-76.549308, 39.311318],
     [-76.54929, 39.311322],
     [-76.549272, 39.311328],
     [-76.549252, 39.311334],
     [-76.549236, 39.311338],
     [-76.549218, 39.311343],
     [-76.549201, 39.311346],
     [-76.549182, 39.311349],
     [-76.549164, 39.311351],
     [-76.549146, 39.311354],
     [-76.549128, 39.311356],
     [-76.549109, 39.311358],
     [-76.549092, 39.311361],
     [-76.549074, 39.311362],
     [-76.549052, 39.311361],
     [-76.549032, 39.31136],
     [-76.549012, 39.311355],
     [-76.548993, 39.311349],
     [-76.548971, 39.311341],
     [-76.548954, 39.311334],
     [-76.548936, 39.311324],
     [-76.548918, 39.31131],
     [-76.548906, 39.311301],
     [-76.548889, 39.311289],
     [-76.548876, 39.311279],
     [-76.548864, 39.311269],
     [-76.548847, 39.311263],
     [-76.548828, 39.31126],
     [-76.548809, 39.31126],
     [-76.548792, 39.311258],
     [-76.548779, 39.311251],
     [-76.54877, 39.311235],
     [-76.548767, 39.311224],
     [-76.548765, 39.311202],
     [-76.548763, 39.311196],
     [-76.54875, 39.311194],
     [-76.548736, 39.311191],
     [-76.548727, 39.311187],
     [-76.548714, 39.311185],
     [-76.5487, 39.311183],
     [-76.548685, 39.311183],
     [-76.548669, 39.311185],
     [-76.548659, 39.31119],
     [-76.548646, 39.311192],
     [-76.548629, 39.311192],
     [-76.548611, 39.311192],
     [-76.548594, 39.311187],
     [-76.548583, 39.311182],
     [-76.548568, 39.31118],
     [-76.548549, 39.311177],
     [-76.548534, 39.311174],
     [-76.548518, 39.311172],
     [-76.548504, 39.311171],
     [-76.548489, 39.311172],
     [-76.548472, 39.311179],
     [-76.548457, 39.311187],
     [-76.548438, 39.311192],
     [-76.548417, 39.311198],
     [-76.548399, 39.311202],
     [-76.548381, 39.311206],
     [-76.54836, 39.311209],
     [-76.548338, 39.311212],
     [-76.548318, 39.311215],
     [-76.548297, 39.311219],
     [-76.548276, 39.311224],
     [-76.548261, 39.31123],
     [-76.54824, 39.311236],
     [-76.548217, 39.31124],
     [-76.548194, 39.311242],
     [-76.548174, 39.311242],
     [-76.548155, 39.311242],
     [-76.548132, 39.311237],
     [-76.548115, 39.311232],
     [-76.548095, 39.311226],
     [-76.548075, 39.311222],
     [-76.548054, 39.311219],
     [-76.548031, 39.311218],
     [-76.548011, 39.311214],
     [-76.547992, 39.311208],
     [-76.547974, 39.311201],
     [-76.547955, 39.31119],
     [-76.547937, 39.311181],
     [-76.547919, 39.311171],
     [-76.547903, 39.311161],
     [-76.547884, 39.311154],
     [-76.547856, 39.311141],
     [-76.547846, 39.311132],
     [-76.547833, 39.311117],
     [-76.547816, 39.311098],
     [-76.547793, 39.311067],
     [-76.547767, 39.311028],
     [-76.547736, 39.310983],
     [-76.547712, 39.310943],
     [-76.547694, 39.310919],
     [-76.547672, 39.310886],
     [-76.547655, 39.31085],
     [-76.547646, 39.310823],
     [-76.547633, 39.310799],
     [-76.547625, 39.310786],
     [-76.547617, 39.310771],
     [-76.547607, 39.310755],
     [-76.547597, 39.310735],
     [-76.547592, 39.310719],
     [-76.547581, 39.310703],
     [-76.547572, 39.310689],
     [-76.547562, 39.310675],
     [-76.547557, 39.310656],
     [-76.547552, 39.310638],
     [-76.547548, 39.310619],
     [-76.547541, 39.31059],
     [-76.547536, 39.310575],
     [-76.547533, 39.310558],
     [-76.547524, 39.310542],
     [-76.547519, 39.310527],
     [-76.547513, 39.31051],
     [-76.547507, 39.310492],
     [-76.547503, 39.310474],
     [-76.547495, 39.310455],
     [-76.547489, 39.310434],
     [-76.547483, 39.310419],
     [-76.547477, 39.310402],
     [-76.547471, 39.310381],
     [-76.547469, 39.310365],
     [-76.547459, 39.310336],
     [-76.547454, 39.310319],
     [-76.547445, 39.310295],
     [-76.547439, 39.310277],
     [-76.547434, 39.310269],
     [-76.547425, 39.310265],
     [-76.547416, 39.310255],
     [-76.547409, 39.310243],
     [-76.547409, 39.310231],
     [-76.547408, 39.310218],
     [-76.547405, 39.310206],
     [-76.547398, 39.310192],
     [-76.547384, 39.310177],
     [-76.547376, 39.310169],
     [-76.547374, 39.310161],
     [-76.547374, 39.310152],
     [-76.547374, 39.310143],
     [-76.547371, 39.310136],
     [-76.547366, 39.31012],
     [-76.547354, 39.310105],
     [-76.547344, 39.310097],
     [-76.547326, 39.310085],
     [-76.547322, 39.310078],
     [-76.54732, 39.310062],
     [-76.547317, 39.310041],
     [-76.547312, 39.310023],
     [-76.547304, 39.310005],
     [-76.547295, 39.309992],
     [-76.547285, 39.309979],
     [-76.547274, 39.309964],
     [-76.547265, 39.309946],
     [-76.547255, 39.309931],
     [-76.547245, 39.309914],
     [-76.547234, 39.309899],
     [-76.547221, 39.309885],
     [-76.547207, 39.30987],
     [-76.547196, 39.309854],
     [-76.547184, 39.309839],
     [-76.547174, 39.309824],
     [-76.547159, 39.30981],
     [-76.547149, 39.309797],
     [-76.547135, 39.309785],
     [-76.547122, 39.309772],
     [-76.547108, 39.30976],
     [-76.547095, 39.309748],
     [-76.54708, 39.309736],
     [-76.547068, 39.309726],
     [-76.547054, 39.309713],
     [-76.54704, 39.3097],
     [-76.547024, 39.309688],
     [-76.547008, 39.309676],
     [-76.546994, 39.309665],
     [-76.546976, 39.309651],
     [-76.54696, 39.309638],
     [-76.546945, 39.309625],
     [-76.54693, 39.309612],
     [-76.546913, 39.3096],
     [-76.546897, 39.309588],
     [-76.546882, 39.309576],
     [-76.546864, 39.309561],
     [-76.546847, 39.309549],
     [-76.546831, 39.309537],
     [-76.546813, 39.309525],
     [-76.546795, 39.309513],
     [-76.546777, 39.309502],
     [-76.546758, 39.309491],
     [-76.546739, 39.309481],
     [-76.546721, 39.30947],
     [-76.546707, 39.309459],
     [-76.546689, 39.309448],
     [-76.546674, 39.309438],
     [-76.546655, 39.309428],
     [-76.546636, 39.309417],
     [-76.546613, 39.309407],
     [-76.546559, 39.309381],
     [-76.546495, 39.309348],
     [-76.546464, 39.309331],
     [-76.546445, 39.309316],
     [-76.546421, 39.309303],
     [-76.54638, 39.309285],
     [-76.54634, 39.309264],
     [-76.546298, 39.309247],
     [-76.546252, 39.309224],
     [-76.546205, 39.309204],
     [-76.546163, 39.309184],
     [-76.546124, 39.30917],
     [-76.54608, 39.309153],
     [-76.546031, 39.309134],
     [-76.545977, 39.309116],
     [-76.545949, 39.309108],
     [-76.545932, 39.309108],
     [-76.545914, 39.30911],
     [-76.545899, 39.309108],
     [-76.545881, 39.309101],
     [-76.545865, 39.309095],
     [-76.545848, 39.30909],
     [-76.545833, 39.309084],
     [-76.54582, 39.309079],
     [-76.545818, 39.309073],
     [-76.545818, 39.309066],
     [-76.545821, 39.309061],
     [-76.545826, 39.309054],
     [-76.545829, 39.309048],
     [-76.545833, 39.309036],
     [-76.545826, 39.309029],
     [-76.545816, 39.309023],
     [-76.5458, 39.309018],
     [-76.545787, 39.309013],
     [-76.54577, 39.309002],
     [-76.545755, 39.308991],
     [-76.545746, 39.308992],
     [-76.545743, 39.308994],
     [-76.545734, 39.309005],
     [-76.545724, 39.309009],
     [-76.545712, 39.309007],
     [-76.545696, 39.309],
     [-76.54568, 39.308997],
     [-76.545662, 39.308995],
     [-76.54564, 39.308992],
     [-76.545621, 39.308988],
     [-76.545597, 39.30898],
     [-76.545578, 39.308971],
     [-76.545557, 39.308964],
     [-76.545535, 39.308957],
     [-76.545514, 39.308951],
     [-76.545497, 39.308946],
     [-76.54548, 39.30894],
     [-76.545462, 39.308934],
     [-76.545429, 39.308928],
     [-76.545412, 39.308926],
     [-76.545393, 39.308921],
     [-76.545373, 39.308916],
     [-76.545354, 39.308911],
     [-76.545334, 39.308903],
     [-76.545318, 39.308894],
     [-76.545304, 39.308886],
     [-76.545282, 39.308879],
     [-76.545266, 39.308874],
     [-76.545249, 39.308867],
     [-76.54523, 39.308861],
     [-76.545213, 39.308853],
     [-76.545197, 39.308847],
     [-76.545185, 39.308841],
     [-76.54517, 39.308835],
     [-76.545159, 39.308832],
     [-76.545102, 39.308817],
     [-76.545085, 39.308807],
     [-76.545076, 39.308801],
     [-76.545066, 39.308795],
     [-76.545056, 39.30879],
     [-76.545046, 39.308786],
     [-76.545036, 39.308783],
     [-76.545024, 39.308778],
     [-76.545014, 39.30877],
     [-76.545009, 39.308765],
     [-76.544999, 39.308756],
     [-76.54499, 39.308749],
     [-76.544979, 39.308741],
     [-76.544967, 39.308732],
     [-76.544958, 39.308725],
     [-76.544947, 39.308718],
     [-76.544936, 39.30871],
     [-76.544927, 39.308704],
     [-76.544915, 39.308697],
     [-76.544905, 39.308691],
     [-76.544895, 39.308685],
     [-76.544884, 39.308679],
     [-76.544873, 39.308673],
     [-76.544862, 39.308667],
     [-76.544849, 39.30866],
     [-76.544838, 39.308653],
     [-76.544828, 39.308646],
     [-76.544817, 39.308638],
     [-76.544809, 39.308631],
     [-76.544799, 39.308622],
     [-76.544788, 39.308614],
     [-76.544778, 39.308606],
     [-76.544766, 39.308598],
     [-76.544755, 39.308591],
     [-76.544745, 39.308585],
     [-76.544733, 39.308577],
     [-76.544722, 39.308571],
     [-76.54471, 39.308564],
     [-76.5447, 39.308558],
     [-76.544689, 39.308552],
     [-76.544677, 39.308545],
     [-76.544665, 39.308539],
     [-76.544654, 39.308533],
     [-76.544643, 39.308528],
     [-76.54463, 39.308523],
     [-76.544617, 39.308518],
     [-76.544604, 39.308513],
     [-76.54459, 39.308512],
     [-76.544577, 39.308512],
     [-76.544554, 39.308514],
     [-76.544545, 39.308515],
     [-76.544536, 39.308515],
     [-76.544524, 39.308514],
     [-76.544515, 39.308512],
     [-76.544503, 39.308508],
     [-76.544492, 39.308503],
     [-76.54448, 39.308497],
     [-76.544467, 39.308495],
     [-76.544454, 39.308493],
     [-76.544434, 39.30849],
     [-76.54442, 39.308487],
     [-76.544406, 39.308483],
     [-76.544393, 39.308479],
     [-76.544378, 39.308474],

In [34]:
baltimore_neighborhoods

[{'type': 'Feature',
  'properties': {'name': 'Armistead Gardens',
   'cartodb_id': 5,
   'created_at': '2013-11-12T15:45:44Z',
   'updated_at': '2013-11-12T15:45:44Z'},
  'geometry': {'type': 'MultiPolygon',
   'coordinates': [[[[-76.5588, 39.306457],
      [-76.55892, 39.306536],
      [-76.559181, 39.306711],
      [-76.559334, 39.306809],
      [-76.559387, 39.306847],
      [-76.55994, 39.307247],
      [-76.560362, 39.307539],
      [-76.56074, 39.307814],
      [-76.561224, 39.308173],
      [-76.56136, 39.308271],
      [-76.560687, 39.308707],
      [-76.560426, 39.308846],
      [-76.559794, 39.309183],
      [-76.55842, 39.309915],
      [-76.558332, 39.309966],
      [-76.558005, 39.310157],
      [-76.557638, 39.310351],
      [-76.557575, 39.31038],
      [-76.555834, 39.311363],
      [-76.555223, 39.311682],
      [-76.555006, 39.311834],
      [-76.5546, 39.312104],
      [-76.550387, 39.314907],
      [-76.549787, 39.315307],
      [-76.549164, 39.315691],
      [-76.549164, 39.31567],
      [-76.549164, 39.315641],
      [-76.549164, 39.31563],
      [-76.549168, 39.31562],
      [-76.549188, 39.315575],
      [-76.549207, 39.315535],
      [-76.549214, 39.315519],
      [-76.549215, 39.315507],
      [-76.549211, 39.315496],
      [-76.549208, 39.315485],
      [-76.549214, 39.315468],
      [-76.549236, 39.315439],
      [-76.549239, 39.315434],
      [-76.549239, 39.315427],
      [-76.549236, 39.315421],
      [-76.54923, 39.315395],
      [-76.549232, 39.315391],
      [-76.549242, 39.315387],
      [-76.549248, 39.315386],
      [-76.549253, 39.315383],
      [-76.549268, 39.315343],
      [-76.549268, 39.315338],
      [-76.549265, 39.315336],
      [-76.54926, 39.315332],
      [-76.549257, 39.315316],
      [-76.549257, 39.315309],
      [-76.549262, 39.315305],
      [-76.549282, 39.315306],
      [-76.54929, 39.315304],
      [-76.549294, 39.3153],
      [-76.549297, 39.31529],
      [-76.549294, 39.315288],
      [-76.549286, 39.315284],
      [-76.549282, 39.31528],
      [-76.54928, 39.315272],
      [-76.549284, 39.315251],
      [-76.549288, 39.315247],
      [-76.549295, 39.315243],
      [-76.5493, 39.315239],
      [-76.549326, 39.315178],
      [-76.549327, 39.315162],
      [-76.549325, 39.315149],
      [-76.549318, 39.315125],
      [-76.549309, 39.315098],
      [-76.549305, 39.31508],
      [-76.549307, 39.315065],
      [-76.549315, 39.315039],
      [-76.549326, 39.315006],
      [-76.549336, 39.314964],
      [-76.549356, 39.314922],
      [-76.549382, 39.314864],
      [-76.54941, 39.314809],
      [-76.549413, 39.314803],
      [-76.549436, 39.314751],
      [-76.549456, 39.314724],
      [-76.549466, 39.314713],
      [-76.549472, 39.31471],
      [-76.549489, 39.314704],
      [-76.549507, 39.314701],
      [-76.549513, 39.314698],
      [-76.549515, 39.314696],
      [-76.549517, 39.314693],
      [-76.549536, 39.31463],
      [-76.549568, 39.314557],
      [-76.549607, 39.314465],
      [-76.549635, 39.314396],
      [-76.549653, 39.314336],
      [-76.549667, 39.314274],
      [-76.549681, 39.314239],
      [-76.549684, 39.314221],
      [-76.549689, 39.314168],
      [-76.549693, 39.314125],
      [-76.549692, 39.314094],
      [-76.549685, 39.314055],
      [-76.549685, 39.314019],
      [-76.549683, 39.314005],
      [-76.549674, 39.313991],
      [-76.549658, 39.313959],
      [-76.549644, 39.313918],
      [-76.549623, 39.313879],
      [-76.549614, 39.313854],
      [-76.549605, 39.313797],
      [-76.549612, 39.313768],
      [-76.549611, 39.313737],
      [-76.549605, 39.313716],
      [-76.549609, 39.313713],
      [-76.549614, 39.313711],
      [-76.549623, 39.313712],
      [-76.549632, 39.313714],
      [-76.549651, 39.313716],
      [-76.549663, 39.313716],
      [-76.549682, 39.313709],
      [-76.549691, 39.313703],
      [-76.549708, 39.313697],
      [-76.549718, 39.313693],
      [-76.549723, 39.313685],
      [-76.549724, 39.313679],
      [-76.549721, 39.313676],
      [-76.549715, 39.313674],
      [-76.549704, 39.313673],
      [-76.549692, 39.313673],
      [-76.549675, 39.313669],
      [-76.549654, 39.313658],
      [-76.549627, 39.313638],
      [-76.549609, 39.313614],
      [-76.549597, 39.313595],
      [-76.549587, 39.313572],
      [-76.549575, 39.313533],
      [-76.549571, 39.313531],
      [-76.549563, 39.313528],
      [-76.549558, 39.313528],
      [-76.549553, 39.31353],
      [-76.549549, 39.313534],
      [-76.549547, 39.313539],
      [-76.549546, 39.313546],
      [-76.549559, 39.313604],
      [-76.549577, 39.3137],
      [-76.549589, 39.313771],
      [-76.549588, 39.313779],
      [-76.549583, 39.313784],
      [-76.549577, 39.313784],
      [-76.549569, 39.313781],
      [-76.549555, 39.313758],
      [-76.549538, 39.313739],
      [-76.549518, 39.313707],
      [-76.5495, 39.313685],
      [-76.549487, 39.313671],
      [-76.54947, 39.313656],
      [-76.549449, 39.313643],
      [-76.54941, 39.313628],
      [-76.549404, 39.313622],
      [-76.549402, 39.313617],
      [-76.549403, 39.313611],
      [-76.549414, 39.313577],
      [-76.549433, 39.313521],
      [-76.549452, 39.313477],
      [-76.549459, 39.313466],
      [-76.54948, 39.313451],
      [-76.549487, 39.313439],
      [-76.549493, 39.31343],
      [-76.549501, 39.313425],
      [-76.549511, 39.313425],
      [-76.549518, 39.313421],
      [-76.549554, 39.313378],
      [-76.5496, 39.313325],
      [-76.549645, 39.313272],
      [-76.549682, 39.31323],
      [-76.549708, 39.313191],
      [-76.549736, 39.313155],
      [-76.549759, 39.313131],
      [-76.5498, 39.313095],
      [-76.549907, 39.313019],
      [-76.549975, 39.312966],
      [-76.549984, 39.312962],
      [-76.549998, 39.312954],
      [-76.55001, 39.312944],
      [-76.550028, 39.312925],
      [-76.550039, 39.312916],
      [-76.550055, 39.312909],
      [-76.550069, 39.312903],
      [-76.550079, 39.312897],
      [-76.550084, 39.312891],
      [-76.550123, 39.312847],
      [-76.550128, 39.312843],
      [-76.550133, 39.312841],
      [-76.55015, 39.31284],
      [-76.55016, 39.312837],
      [-76.550169, 39.312831],
      [-76.550237, 39.312764],
      [-76.550259, 39.31273],
      [-76.550268, 39.312717],
      [-76.550276, 39.312707],
      [-76.550282, 39.312704],
      [-76.550292, 39.3127],
      [-76.550299, 39.312694],
      [-76.550361, 39.312646],
      [-76.550391, 39.312624],
      [-76.550417, 39.312601],
      [-76.550459, 39.312562],
      [-76.550474, 39.312543],
      [-76.550488, 39.312525],
      [-76.550499, 39.312504],
      [-76.550514, 39.312478],
      [-76.55057, 39.312402],
      [-76.550617, 39.312332],
      [-76.550651, 39.312278],
      [-76.550669, 39.312248],
      [-76.550681, 39.312223],
      [-76.55069, 39.312196],
      [-76.550701, 39.312174],
      [-76.550713, 39.312148],
      [-76.550729, 39.312112],
      [-76.550746, 39.312068],
      [-76.55076, 39.312025],
      [-76.550772, 39.311989],
      [-76.550789, 39.311956],
      [-76.550802, 39.31193],
      [-76.550813, 39.311915],
      [-76.550821, 39.311897],
      [-76.550834, 39.311855],
      [-76.550842, 39.311827],
      [-76.550851, 39.311811],
      [-76.550873, 39.311771],
      [-76.550881, 39.31175],
      [-76.550892, 39.311712],
      [-76.550905, 39.311646],
      [-76.550911, 39.311586],
      [-76.550911, 39.311551],
      [-76.550912, 39.311533],
      [-76.550911, 39.311514],
      [-76.550924, 39.311429],
      [-76.550916, 39.311415],
      [-76.550899, 39.311389],
      [-76.550865, 39.311363],
      [-76.550838, 39.311352],
      [-76.550816, 39.311351],
      [-76.550789, 39.311352],
      [-76.550766, 39.311354],
      [-76.55074, 39.311352],
      [-76.550691, 39.311336],
      [-76.550648, 39.311324],
      [-76.5506, 39.311311],
      [-76.550561, 39.311304],
      [-76.55051, 39.311304],
      [-76.550478, 39.311306],
      [-76.550429, 39.311308],
      [-76.550411, 39.31131],
      [-76.550397, 39.311313],
      [-76.550384, 39.311316],
      [-76.550367, 39.311321],
      [-76.550356, 39.31132],
      [-76.550348, 39.311317],
      [-76.550342, 39.31131],
      [-76.550337, 39.311307],
      [-76.550327, 39.311306],
      [-76.550317, 39.311306],
      [-76.550308, 39.311306],
      [-76.550296, 39.311305],
      [-76.550288, 39.311305],
      [-76.550279, 39.311305],
      [-76.550268, 39.311305],
      [-76.550258, 39.311305],
      [-76.550248, 39.311304],
      [-76.550237, 39.311304],
      [-76.550227, 39.311304],
      [-76.550218, 39.311304],
      [-76.550207, 39.311304],
      [-76.550197, 39.311304],
      [-76.550184, 39.311304],
      [-76.550173, 39.311304],
      [-76.550159, 39.311304],
      [-76.550145, 39.311304],
      [-76.550134, 39.311304],
      [-76.550122, 39.311304],
      [-76.550114, 39.311302],
      [-76.550103, 39.311301],
      [-76.550098, 39.311305],
      [-76.550089, 39.311312],
      [-76.550082, 39.311312],
      [-76.550071, 39.311312],
      [-76.550057, 39.311312],
      [-76.550042, 39.311312],
      [-76.550027, 39.311312],
      [-76.550011, 39.311314],
      [-76.549998, 39.311315],
      [-76.549984, 39.311315],
      [-76.549968, 39.311313],
      [-76.549953, 39.311309],
      [-76.549937, 39.311308],
      [-76.549925, 39.311303],
      [-76.549916, 39.311295],
      [-76.549904, 39.311289],
      [-76.549894, 39.311285],
      [-76.549879, 39.311283],
      [-76.549864, 39.311282],
      [-76.549848, 39.311281],
      [-76.549832, 39.311278],
      [-76.549817, 39.311278],
      [-76.549802, 39.311278],
      [-76.549786, 39.311277],
      [-76.549771, 39.311277],
      [-76.549758, 39.311277],
      [-76.549743, 39.311279],
      [-76.549728, 39.311281],
      [-76.549714, 39.311287],
      [-76.549703, 39.311294],
      [-76.549692, 39.311301],
      [-76.549677, 39.311302],
      [-76.549663, 39.311302],
      [-76.549646, 39.311302],
      [-76.54963, 39.311303],
      [-76.549609, 39.311305],
      [-76.549589, 39.311306],
      [-76.549566, 39.31131],
      [-76.549545, 39.311313],
      [-76.549525, 39.311314],
      [-76.549502, 39.311315],
      [-76.549481, 39.311315],
      [-76.549463, 39.311315],
      [-76.54944, 39.311313],
      [-76.549418, 39.31131],
      [-76.5494, 39.311309],
      [-76.549381, 39.311308],
      [-76.549365, 39.311308],
      [-76.549346, 39.311311],
      [-76.549329, 39.311313],
      [-76.549308, 39.311318],
      [-76.54929, 39.311322],
      [-76.549272, 39.311328],
      [-76.549252, 39.311334],
      [-76.549236, 39.311338],
      [-76.549218, 39.311343],
      [-76.549201, 39.311346],
      [-76.549182, 39.311349],
      [-76.549164, 39.311351],
      [-76.549146, 39.311354],
      [-76.549128, 39.311356],
      [-76.549109, 39.311358],
      [-76.549092, 39.311361],
      [-76.549074, 39.311362],
      [-76.549052, 39.311361],
      [-76.549032, 39.31136],
      [-76.549012, 39.311355],
      [-76.548993, 39.311349],
      [-76.548971, 39.311341],
      [-76.548954, 39.311334],
      [-76.548936, 39.311324],
      [-76.548918, 39.31131],
      [-76.548906, 39.311301],
      [-76.548889, 39.311289],
      [-76.548876, 39.311279],
      [-76.548864, 39.311269],
      [-76.548847, 39.311263],
      [-76.548828, 39.31126],
      [-76.548809, 39.31126],
      [-76.548792, 39.311258],
      [-76.548779, 39.311251],
      [-76.54877, 39.311235],
      [-76.548767, 39.311224],
      [-76.548765, 39.311202],
      [-76.548763, 39.311196],
      [-76.54875, 39.311194],
      [-76.548736, 39.311191],
      [-76.548727, 39.311187],
      [-76.548714, 39.311185],
      [-76.5487, 39.311183],
      [-76.548685, 39.311183],
      [-76.548669, 39.311185],
      [-76.548659, 39.31119],
      [-76.548646, 39.311192],
      [-76.548629, 39.311192],
      [-76.548611, 39.311192],
      [-76.548594, 39.311187],
      [-76.548583, 39.311182],
      [-76.548568, 39.31118],
      [-76.548549, 39.311177],
      [-76.548534, 39.311174],
      [-76.548518, 39.311172],
      [-76.548504, 39.311171],
      [-76.548489, 39.311172],
      [-76.548472, 39.311179],
      [-76.548457, 39.311187],
      [-76.548438, 39.311192],
      [-76.548417, 39.311198],
      [-76.548399, 39.311202],
      [-76.548381, 39.311206],
      [-76.54836, 39.311209],
      [-76.548338, 39.311212],
      [-76.548318, 39.311215],
      [-76.548297, 39.311219],
      [-76.548276, 39.311224],
      [-76.548261, 39.31123],
      [-76.54824, 39.311236],
      [-76.548217, 39.31124],
      [-76.548194, 39.311242],
      [-76.548174, 39.311242],
      [-76.548155, 39.311242],
      [-76.548132, 39.311237],
      [-76.548115, 39.311232],
      [-76.548095, 39.311226],
      [-76.548075, 39.311222],
      [-76.548054, 39.311219],
      [-76.548031, 39.311218],
      [-76.548011, 39.311214],
      [-76.547992, 39.311208],
      [-76.547974, 39.311201],
      [-76.547955, 39.31119],
      [-76.547937, 39.311181],
      [-76.547919, 39.311171],
      [-76.547903, 39.311161],
      [-76.547884, 39.311154],
      [-76.547856, 39.311141],
      [-76.547846, 39.311132],
      [-76.547833, 39.311117],
      [-76.547816, 39.311098],
      [-76.547793, 39.311067],
      [-76.547767, 39.311028],
      [-76.547736, 39.310983],
      [-76.547712, 39.310943],
      [-76.547694, 39.310919],
      [-76.547672, 39.310886],
      [-76.547655, 39.31085],
      [-76.547646, 39.310823],
      [-76.547633, 39.310799],
      [-76.547625, 39.310786],
      [-76.547617, 39.310771],
      [-76.547607, 39.310755],
      [-76.547597, 39.310735],
      [-76.547592, 39.310719],
      [-76.547581, 39.310703],
      [-76.547572, 39.310689],
      [-76.547562, 39.310675],
      [-76.547557, 39.310656],
      [-76.547552, 39.310638],
      [-76.547548, 39.310619],
      [-76.547541, 39.31059],
      [-76.547536, 39.310575],
      [-76.547533, 39.310558],
      [-76.547524, 39.310542],
      [-76.547519, 39.310527],
      [-76.547513, 39.31051],
      [-76.547507, 39.310492],
      [-76.547503, 39.310474],
      [-76.547495, 39.310455],
      [-76.547489, 39.310434],
      [-76.547483, 39.310419],
      [-76.547477, 39.310402],
      [-76.547471, 39.310381],
      [-76.547469, 39.310365],
      [-76.547459, 39.310336],
      [-76.547454, 39.310319],
      [-76.547445, 39.310295],
      [-76.547439, 39.310277],
      [-76.547434, 39.310269],
      [-76.547425, 39.310265],
      [-76.547416, 39.310255],
      [-76.547409, 39.310243],
      [-76.547409, 39.310231],
      [-76.547408, 39.310218],
      [-76.547405, 39.310206],
      [-76.547398, 39.310192],
      [-76.547384, 39.310177],
      [-76.547376, 39.310169],
      [-76.547374, 39.310161],
      [-76.547374, 39.310152],
      [-76.547374, 39.310143],
      [-76.547371, 39.310136],
      [-76.547366, 39.31012],
      [-76.547354, 39.310105],
      [-76.547344, 39.310097],
      [-76.547326, 39.310085],
      [-76.547322, 39.310078],
      [-76.54732, 39.310062],
      [-76.547317, 39.310041],
      [-76.547312, 39.310023],
      [-76.547304, 39.310005],
      [-76.547295, 39.309992],
      [-76.547285, 39.309979],
      [-76.547274, 39.309964],
      [-76.547265, 39.309946],
      [-76.547255, 39.309931],
      [-76.547245, 39.309914],
      [-76.547234, 39.309899],
      [-76.547221, 39.309885],
      [-76.547207, 39.30987],
      [-76.547196, 39.309854],
      [-76.547184, 39.309839],
      [-76.547174, 39.309824],
      [-76.547159, 39.30981],
      [-76.547149, 39.309797],
      [-76.547135, 39.309785],
      [-76.547122, 39.309772],
      [-76.547108, 39.30976],
      [-76.547095, 39.309748],
      [-76.54708, 39.309736],
      [-76.547068, 39.309726],
      [-76.547054, 39.309713],
      [-76.54704, 39.3097],
      [-76.547024, 39.309688],
      [-76.547008, 39.309676],
      [-76.546994, 39.309665],
      [-76.546976, 39.309651],
      [-76.54696, 39.309638],
      [-76.546945, 39.309625],
      [-76.54693, 39.309612],
      [-76.546913, 39.3096],
      [-76.546897, 39.309588],
      [-76.546882, 39.309576],
      [-76.546864, 39.309561],
      [-76.546847, 39.309549],
      [-76.546831, 39.309537],
      [-76.546813, 39.309525],
      [-76.546795, 39.309513],
      [-76.546777, 39.309502],
      [-76.546758, 39.309491],
      [-76.546739, 39.309481],
      [-76.546721, 39.30947],
      [-76.546707, 39.309459],
      [-76.546689, 39.309448],
      [-76.546674, 39.309438],
      [-76.546655, 39.309428],
      [-76.546636, 39.309417],
      [-76.546613, 39.309407],
      [-76.546559, 39.309381],
      [-76.546495, 39.309348],
      [-76.546464, 39.309331],
      [-76.546445, 39.309316],
      [-76.546421, 39.309303],
      [-76.54638, 39.309285],
      [-76.54634, 39.309264],
      [-76.546298, 39.309247],
      [-76.546252, 39.309224],
      [-76.546205, 39.309204],
      [-76.546163, 39.309184],
      [-76.546124, 39.30917],
      [-76.54608, 39.309153],
      [-76.546031, 39.309134],
      [-76.545977, 39.309116],
      [-76.545949, 39.309108],
      [-76.545932, 39.309108],
      [-76.545914, 39.30911],
      [-76.545899, 39.309108],
      [-76.545881, 39.309101],
      [-76.545865, 39.309095],
      [-76.545848, 39.30909],
      [-76.545833, 39.309084],
      [-76.54582, 39.309079],
      [-76.545818, 39.309073],
      [-76.545818, 39.309066],
      [-76.545821, 39.309061],
      [-76.545826, 39.309054],
      [-76.545829, 39.309048],
      [-76.545833, 39.309036],
      [-76.545826, 39.309029],
      [-76.545816, 39.309023],
      [-76.5458, 39.309018],
      [-76.545787, 39.309013],
      [-76.54577, 39.309002],
      [-76.545755, 39.308991],
      [-76.545746, 39.308992],
      [-76.545743, 39.308994],
      [-76.545734, 39.309005],
      [-76.545724, 39.309009],
      [-76.545712, 39.309007],
      [-76.545696, 39.309],
      [-76.54568, 39.308997],
      [-76.545662, 39.308995],
      [-76.54564, 39.308992],
      [-76.545621, 39.308988],
      [-76.545597, 39.30898],
      [-76.545578, 39.308971],
      [-76.545557, 39.308964],
      [-76.545535, 39.308957],
      [-76.545514, 39.308951],
      [-76.545497, 39.308946],
      [-76.54548, 39.30894],
      [-76.545462, 39.308934],
      [-76.545429, 39.308928],
      [-76.545412, 39.308926],
      [-76.545393, 39.308921],
      [-76.545373, 39.308916],
      [-76.545354, 39.308911],
      [-76.545334, 39.308903],
      [-76.545318, 39.308894],
      [-76.545304, 39.308886],
      [-76.545282, 39.308879],
      [-76.545266, 39.308874],
      [-76.545249, 39.308867],
      [-76.54523, 39.308861],
      [-76.545213, 39.308853],
      [-76.545197, 39.308847],
      [-76.545185, 39.308841],
      [-76.54517, 39.308835],
      [-76.545159, 39.308832],
      [-76.545102, 39.308817],
      [-76.545085, 39.308807],
      [-76.545076, 39.308801],
      [-76.545066, 39.308795],
      [-76.545056, 39.30879],
      [-76.545046, 39.308786],
      [-76.545036, 39.308783],
      [-76.545024, 39.308778],
      [-76.545014, 39.30877],
      [-76.545009, 39.308765],
      [-76.544999, 39.308756],
      [-76.54499, 39.308749],
      [-76.544979, 39.308741],
      [-76.544967, 39.308732],
      [-76.544958, 39.308725],
      [-76.544947, 39.308718],
      [-76.544936, 39.30871],
      [-76.544927, 39.308704],
      [-76.544915, 39.308697],
      [-76.544905, 39.308691],
      [-76.544895, 39.308685],
      [-76.544884, 39.308679],
      [-76.544873, 39.308673],
      [-76.544862, 39.308667],
      [-76.544849, 39.30866],
      [-76.544838, 39.308653],
      [-76.544828, 39.308646],
      [-76.544817, 39.308638],
      [-76.544809, 39.308631],
      [-76.544799, 39.308622],
      [-76.544788, 39.308614],
      [-76.544778, 39.308606],
      [-76.544766, 39.308598],
      [-76.544755, 39.308591],
      [-76.544745, 39.308585],
      [-76.544733, 39.308577],
      [-76.544722, 39.308571],
      [-76.54471, 39.308564],
      [-76.5447, 39.308558],
      [-76.544689, 39.308552],
      [-76.544677, 39.308545],
      [-76.544665, 39.308539],
      [-76.544654, 39.308533],

##### Function to gather neighborhood coordinates

In [35]:
# Function to gather neighborhood coordinates
def gather_coords(neighborhood_item):

    list_t = []

    # Iterate through neighborhood coordinates
    for coord in neighborhood_item:

        contains = (coord[0], coord[1])
        list_t.append(contains)

    return list_t
print("Ready")

Ready

##### Build neighborhood dictionary used for validating charger neighborhood location

In [36]:
# Build a dictionary from the Baltimore City GeoJSON consisting of neighborhood names and it's respective coordinates

# Set up target variables
neighborhood_array = []
neighborhood_dict = {'Name':'', 'Coords':[]}

# Initialize GeoJSON data target
# neighborhood_items = city_input['features']

# Iterate through JSON to pull neighborhood details
for items in baltimore_neighborhoods:
    
    # Capture name
    name = items['properties']['name']
    
    # Capture coords 
    coords = gather_coords(items['geometry']['coordinates'][0][0])
    
    # Update dictionary
    neighborhood_dict.update({'Name':name, 'Coords': coords})
    
    # Add to output list
    neighborhood_array.append(dict(neighborhood_dict))
print("Ready")

Ready

##### Generate neighborhood list with coordinates for use with Venues

In [37]:
from geographiclib.geodesic import Geodesic
from geographiclib.polygonarea import PolygonArea

geod = Geodesic.WGS84

def calculate_area(polygon_data):
    poly_area = PolygonArea(geod)
    for point in polygon_data:
        poly_area.AddPoint(point[1], point[0])

    _, _, area = poly_area.Compute()

    # If the area is negative, reverse the order of the coordinates and recompute the area
    if area < 0:
        polygon_data = polygon_data[::-1]
        poly_area = PolygonArea(geod)
        for point in polygon_data:
            poly_area.AddPoint(point[1], point[0])
        _, _, area = poly_area.Compute()

    return area

In [38]:
from shapely.geometry import Polygon

# Loop to find centroid
for neighborhood in neighborhood_array:
    
    # Assign neighborhood coordinates to polygon_data variable
    polygon_data = neighborhood['Coords']
    
    # Calculate centroid via Shapely
    ref_polygon = Polygon(polygon_data)
    
    # Assign center lat and lon points to neighborhood array
    neighborhood['Center Longitude'] = ref_polygon.centroid.x
    neighborhood['Center Latitude'] = ref_polygon.centroid.y
    neighborhood['Area'] = calculate_area(polygon_data) * 3.86102e-7 # Area is in Square Miles convert by using the constant 3.86102e-7

##### Build neighborhood dataframe from neighborhood array

In [39]:
# Initialize list variables
neighborhood_list = []
center_long = []
center_lat = []
area = []

# Loop to Build Neighborhood list
for items in neighborhood_array:
    neighborhood_list.append(items['Name'])
    center_long.append(items['Center Longitude'])
    center_lat.append(items['Center Latitude'])
    area.append(items['Area'])
    
# Convert Neighborhood list to dataframe for function loop
neighborhood_list = pd.DataFrame({"Neighborhood":neighborhood_list, 'Center Latitude':center_lat, 'Center Longitude':center_long, 'Area':area})
neighborhood_list

,Neighborhood,Center Latitude,Center Longitude,Area
0,Armistead Gardens,39.307342,-76.551451,0.472803
1,Wyman Park,39.331961,-76.626138,0.110365
2,Canton,39.282043,-76.575227,0.570498
3,Canton Industrial Area,39.268608,-76.555621,2.488602
4,Fairfield Area,39.238180,-76.581335,2.404451
5,Fells Point,39.283240,-76.593627,0.288077
6,Frankford,39.329278,-76.544633,2.124897
7,Franklintown,39.305836,-76.701453,0.595389
8,Garwyn Oaks,39.317854,-76.679329,0.131365
9,Heritage Crossing,39.296259,-76.628428,0.085181
10,Medfield,39.340262,-76.643263,0.260206
11,Carroll - Camden Industrial Area,39.273218,-76.633785,0.703049
12,Carroll Park,39.276280,-76.646509,0.343985
13,Johns Hopkins Homewood,39.329348,-76.621295,0.256512
14,Lauraville,39.346550,-76.572702,0.591334
15,Loch Raven,39.361416,-76.581829,0.570470
16,Locust Point Industrial Area,39.267836,-76.591802,0.932510
17,Carrollton Ridge,39.282321,-76.648857,0.222885
18,Concerned Citizens Of Forest Park,39.323143,-76.683686,0.079893
19,Lakeland,39.255107,-76.647388,0.548122
20,Middle Branch/Reedbird Parks,39.243087,-76.610931,0.059826
21,Millhill,39.279278,-76.656826,0.209804
22,South Baltimore,39.271290,-76.614250,0.129811
23,Spring Garden Industrial Area,39.267671,-76.618404,0.270242
24,Lower Edmondson Village,39.292915,-76.674056,0.022585
25,Edgewood,39.295990,-76.676774,0.103848
26,Cedonia,39.328539,-76.532510,0.282211
27,Curtis Bay Industrial Area,39.223597,-76.583393,0.418798
28,Dundalk Marine Terminal,39.248177,-76.533404,0.428103
29,Evergreen Lawn,39.296688,-76.656618,0.053408
30,Mt Pleasant Park,39.366358,-76.575674,0.253007
31,Gwynns Falls,39.277819,-76.667201,0.178755
32,Gwynns Falls/Leakin Park,39.304165,-76.683608,0.745410
33,Hampden,39.331137,-76.634046,0.614485
34,Hawkins Point,39.207697,-76.555664,1.865394
35,Holabird Industrial Park,39.266056,-76.536280,0.564166
36,Inner Harbor,39.283565,-76.606302,0.241417
37,Irvington,39.278406,-76.683712,0.888894
38,Morgan State University,39.346087,-76.582013,0.263775
39,Callaway-Garrison,39.331562,-76.679626,0.190315
40,Port Covington,39.263019,-76.609710,0.331950
41,Pulaski Industrial Area,39.301070,-76.539881,1.967803
42,Remington,39.320151,-76.622826,0.245421
43,Roland Park,39.349947,-76.635994,0.957531
44,Rosebank,39.362896,-76.611739,0.066140
45,Saint Agnes,39.274480,-76.674654,0.083309
46,Saint Paul,39.268102,-76.643328,0.103688
47,Sharp-Leadenhall,39.276817,-76.617689,0.069072
48,West Hills,39.297361,-76.706623,0.335099
49,Westport,39.262861,-76.635277,0.497772
50,Yale Heights,39.276124,-76.690565,0.192136
51,Wilhelm Park,39.271915,-76.662282,0.445600
52,Arcadia,39.333854,-76.567736,0.226065
53,Abell,39.325947,-76.611394,0.072984
54,Boyd-Booth,39.287145,-76.649817,0.038736
55,Arlington,39.348631,-76.682737,0.180609
56,Allendale,39.289926,-76.681545,0.406308
57,Barre Circle,39.284981,-76.627881,0.023948
58,Ashburton,39.328230,-76.671701,0.352450
59,Baltimore Highlands,39.293417,-76.566100,0.151518
60,Patterson Park Neighborhood,39.292689,-76.574706,0.168933
61,Barclay,39.314716,-76.612328,0.140554
62,Beechfield,39.276693,-76.700051,0.402982
63,Milton-Montford,39.300616,-76.583116,0.056788
64,Belair-Parkside,39.330136,-76.567917,0.032216
65,Bellona-Gittings,39.369164,-76.622010,0.162564
66,Forest Park,39.323802,-76.677157,0.155081
67,Berea,39.309608,-76.578013,0.340037
68,Biddle Street,39.303672,-76.578999,0.112852
69,Better Waverly,39.324388,-76.605172,0.281793
70,Beverly Hills,39.339108,-76.569112,0.104166
71,Blythewood,39.351148,-76.625257,0.075897
72,Burleith-Leighton,39.319247,-76.660712,0.084533
73,Oaklee,39.268319,-76.685097,0.040750
74,Bolton Hill,39.307821,-76.625730,0.227730
75,Brewers Hill,39.284168,-76.564620,0.089160
76,Bridgeview/Greenlawn,39.301508,-76.654659,0.283318
77,Butcher's Hill,39.291857,-76.586934,0.077647
78,CARE,39.296266,-76.587595,0.084745
79,Broadway East,39.308464,-76.588816,0.346360
80,Dolfield,39.337721,-76.680307,0.170060
81,Broening Manor,39.274239,-76.537831,0.162598
82,Cameron Village,39.356665,-76.599577,0.103842
83,Carroll-South Hilton,39.285794,-76.666912,0.485126
84,Cedarcroft,39.369831,-76.613769,0.133725
85,Brooklyn,39.232753,-76.603346,0.853367
86,Cedmont,39.346679,-76.534522,0.376000
87,Central Forest Park,39.326770,-76.688334,0.149346
88,Central Park Heights,39.343678,-76.671058,0.442864
89,Charles North,39.310578,-76.617093,0.138803
90,Coppin Heights/Ash-Co-East,39.307001,-76.657253,0.191966
91,Cherry Hill,39.248893,-76.628353,1.171278
92,Madison-Eastend,39.300768,-76.576908,0.104298
93,Cheswolde,39.367618,-76.680411,0.855299
94,Chinquapin Park,39.363143,-76.602283,0.114734
95,Darley Park,39.315429,-76.593741,0.051963
96,Forest Park Golf Course,39.323675,-76.695066,0.103018
97,Cross Country,39.366121,-76.697968,0.592421
98,Mount Winans,39.261822,-76.644757,0.076568
99,Orchard Ridge,39.313242,-76.558280,0.277596
100,Franklintown Road,39.297375,-76.667581,0.122906
101,Clifton Park,39.320061,-76.584239,0.560314
102,Locust Point,39.269452,-76.592038,0.134303
103,Coldspring,39.350528,-76.653504,0.649890
104,Edmondson Village,39.297830,-76.683426,0.185842
105,Dickeyville,39.316039,-76.707715,0.213132
106,Coldstream Homestead Montebello,39.322941,-76.595473,0.514762
107,Cross Keys,39.352868,-76.645602,0.278216
108,Gay Street,39.301235,-76.596827,0.109600
109,Curtis Bay,39.223642,-76.590749,0.511127
110,East Arlington,39.331472,-76.668479,0.129354
111,Cylburn,39.347616,-76.664084,0.220954
112,Dorchester,39.331779,-76.686324,0.190583
113,East Baltimore Midway,39.314845,-76.603227,0.299832
114,Eastwood,39.290155,-76.530618,0.028052
115,Downtown,39.291065,-76.615179,0.407368
116,Druid Heights,39.308297,-76.637077,0.090522
117,Easterwood,39.307441,-76.650293,0.077243
118,Wrenlane,39.345216,-76.606596,0.028848
119,Greenspring,39.337056,-76.660224,0.173862
120,Greenmount West,39.308743,-76.611598,0.100136
121,Druid Hill Park,39.322998,-76.644012,0.974759
122,Dunbar-Broadway,39.296015,-76.595200,0.171569
123,Ednor Gardens-Lakeside,39.333138,-76.596704,0.510712
124,Ellwood Park/Monument,39.297165,-76.572190,0.139451
125,Fallstaff,39.364060,-76.706960,0.295542
126,Franklin Square,39.290403,-76.642771,0.172123
127,Evergreen,39.346594,-76.629159,0.057552
128,New Southwest/Mount Clare,39.283029,-76.641734,0.118243
129,Grove Park,39.340417,-76.702575,0.343314
130,Federal Hill,39.278273,-76.611612,0.148922
131,Fairmont,39.308575,-76.679375,0.165667
132,Glen,39.356325,-76.690664,0.747268
133,Glenham-Belhar,39.350027,-76.548576,0.749461
134,Hollins Market,39.287335,-76.633190,0.106956
135,Glen Oaks,39.364828,-76.596474,0.269264
136,Graceland Park,39.281189,-76.533140,0.312555
137,Ridgely's Delight,39.284158,-76.624929,0.049053
138,Greektown,39.285422,-76.554245,0.224460
139,Greenmount Cemetery,39.308834,-76.606503,0.106900
140,Guilford,39.339503,-76.615642,0.552747
141,Taylor Heights,39.368879,-76.533417,0.191238
142,Hanlon-Longwood,39.318211,-76.669459,0.435187
143,Pleasant View Gardens,39.293541,-76.602026,0.046001
144,Little Italy,39.286566,-76.600823,0.050038
145,Hamilton Hills,39.362770,-76.565051,1.141965
146,Kresson,39.296052,-76.557025,0.267960
147,Harlem Park,39.295973,-76.640104,0.312193
148,Harwood,39.320785,-76.611251,0.070935
149,Herring Run Park,39.330419,-76.572782,0.240804
150,Highlandtown,39.288419,-76.567802,0.142113
151,Hillen,39.341875,-76.590189,0.168714
152,Hoes Heights,39.340472,-76.637070,0.077524
153,Homeland,39.359601,-76.618628,0.615755
154,Hopkins Bayview,39.292221,-76.544525,0.415309
155,Radnor-Winston,39.349687,-76.612137,0.078593
156,Howard Park,39.329743,-76.701502,1.057508
157,Purnell,39.320518,-76.707360,0.038755
158,Hunting Ridge,39.296732,-76.698141,0.261836
159,Idlewood,39.369430,-76.588562,0.208014
160,Johnston Square,39.303482,-76.606237,0.170885
161,Lake Evesham,39.366432,-76.614035,0.071092
162,Jones Falls Area,39.319516,-76.629318,0.280019
163,Medford,39.278722,-76.547333,0.154015
164,Jonestown,39.290857,-76.603658,0.134464
165,Bayview,39.288950,-76.541626,0.093418
166,Kenilworth Park,39.349769,-76.601136,0.145033
167,Kernewood,39.346357,-76.613281,0.071956
168,Keswick,39.343374,-76.630397,0.079977
169,Levindale,39.352958,-76.664662,0.147818
170,Liberty Square,39.321886,-76.658001,0.117025
171,Lake Walker,39.369614,-76.604344,0.202958
172,Langston Hughes,39.343551,-76.680250,0.060472
173,Lower Herring Run Park,39.321210,-76.558377,0.086972
174,Lucille Park,39.340008,-76.675817,0.104817
175,Loyola/Notre Dame,39.349296,-76.621162,0.300790
176,Madison Park,39.304486,-76.627222,0.159101
177,Mayfield,39.328681,-76.579896,0.130035
178,McElderry Park,39.296860,-76.580465,0.126470
179,Mid-Govans,39.357428,-76.605818,0.128843
180,Mid-Town Belvedere,39.304064,-76.616591,0.220906
181,Middle East,39.301512,-76.589824,0.198026
182,Midtown-Edmondson,39.296271,-76.650140,0.149577
183,Mondawmin,39.313627,-76.653918,0.382794
184,Panway/Braddish Avenue,39.312866,-76.662670,0.081152
185,Montebello,39.334701,-76.583202,0.464176
186,Moravia-Walther,39.340321,-76.564716,0.131016
187,Mount Holly,39.312138,-76.678642,0.123931
188,Morgan Park,39.347528,-76.579156,0.072613
189,Morrell Park,39.263950,-76.655973,0.838690
190,Mosher,39.297348,-76.662403,0.115270
191,York-Homeland,39.353009,-76.611124,0.023431
192,Mount Vernon,39.297842,-76.616082,0.226679
193,Northwest Community Action,39.306474,-76.665290,0.115959
194,Mount Washington,39.363060,-76.662887,1.241076
195,Tremont,39.283221,-76.694487,0.035219
196,New Northwood,39.348830,-76.594959,0.320897
197,North Harford Road,39.366172,-76.546117,0.639884
198,O'Donnell Heights,39.278424,-76.538989,0.157911
199,Oakenshawe,39.330341,-76.612461,0.062509
200,North Roland Park/Poplar Hill,39.366942,-76.639623,0.613144
201,Oldtown,39.298187,-76.602964,0.167386
202,Orangeville,39.301943,-76.560211,0.369534
203,Oliver,39.308025,-76.599299,0.262937
204,Upper Fells Point,39.287960,-76.588882,0.127298
205,Orangeville Industrial Area,39.306436,-76.568684,0.445395
206,Patterson Park,39.288938,-76.579266,0.225898
207,Original Northwood,39.339815,-76.596779,0.172441
208,Otterbein,39.281952,-76.616144,0.102520
209,Patterson Place,39.293761,-76.583397,0.038011
210,Overlea,39.361925,-76.534396,0.304313
211,Penn North,39.312119,-76.642593,0.135208
212,Park Circle,39.328771,-76.660127,0.310566
213,Saint Josephs,39.285354,-76.675164,0.139754
214,Parklane,39.342676,-76.662244,0.123858
215,Pen Lucy,39.339740,-76.604978,0.171581
216,Parkside,39.323107,-76.556278,0.117504
217,Parkview/Woodbrook,39.316803,-76.648047,0.098552
218,Penn-Fallsway,39.297534,-76.608667,0.134471
219,Poppleton,39.291096,-76.632929,0.182154
220,Penrose/Fayette Street Outreach,39.291119,-76.657394,0.352940
221,Perkins Homes,39.287791,-76.596551,0.037063
222,Perring Loch,39.352694,-76.584779,0.218704
223,Pimlico Good Neighbors,39.353230,-76.675333,0.295720
224,Ramblewood,39.363590,-76.590335,0.155857
225,Reisterstown Station,39.353114,-76.703330,0.453308
226,Seton Business Park,39.345854,-76.706497,0.391049
227,Reservoir Hill,39.313633,-76.633158,0.304620
228,Richnor Springs,39.346796,-76.606895,0.033401
229,Riverside,39.272518,-76.606875,0.295223
230,Rognel Heights,39.296343,-76.690008,0.169931
231,Rosemont,39.304425,-76.670542,0.174186
232,Shipley Hill,39.286306,-76.657114,0.182367
233,Rosemont East,39.355575,-76.538408,0.252101
234,Rosemont Homeowners/Tenants,39.294337,-76.657592,0.063023
235,Sabina-Mattfeldt,39.366313,-76.649378,0.118150
236,Saint Helena,39.260518,-76.531076,0.056711
237,Union Square,39.286682,-76.641543,0.066315
238,Sandtown-Winchester,39.303762,-76.642582,0.406536
239,Woodbourne-McCabe,39.353724,-76.606137,0.075156
240,Seton Hill,39.296715,-76.623704,0.074560
241,South Clifton Park,39.313409,-76.589970,0.094379
242,Stadium Area,39.280253,-76.621623,0.164171
243,University Of Maryland,39.290370,-76.625286,0.151014
244,Ten Hills,39.287680,-76.700835,0.333209
245,Uplands,39.289939,-76.692884,0.197860
246,Walbrook,39.311402,-76.668923,0.199447
247,Stonewood-Pentwood-Winston,39.348035,-76.588850,0.093271
248,Upton,39.301491,-76.631522,0.293017
249,Villages Of Homeland,39.352782,-76.614252,0.031677
250,Violetville,39.266268,-76.673803,0.592838
251,Towanda-Grantley,39.336018,-76.668584,0.139823
252,The Orchards,39.367629,-76.628720,0.211153
253,Tuscany-Canterbury,39.337842,-76.621498,0.145524
254,Downtown West,39.286077,-76.617998,0.109705
255,Westfield,39.359170,-76.551481,0.428936
256,Wakefield,39.312793,-76.699707,0.273003
257,Waltherson,39.341992,-76.557804,0.739215
258,Winston-Govans,39.350057,-76.606515,0.113267
259,Washington Hill,39.291518,-76.594665,0.157207
260,Waverly,39.332020,-76.606764,0.154612
261,Washington Village/Pigtown,39.281657,-76.632299,0.326819
262,Winchester,39.301950,-76.664267,0.083130
263,West Arlington,39.339439,-76.690158,0.272720
264,West Forest Park,39.318578,-76.694122,0.372431
265,Windsor Hills,39.317106,-76.685996,0.234228
266,Westgate,39.284453,-76.706726,0.332907
267,Wilson Park,39.343505,-76.605394,0.093746
268,Four By Four,39.315437,-76.576929,0.070813
269,Woodberry,39.336710,-76.650588,0.531845
270,Woodbourne Heights,39.357408,-76.592479,0.134567
271,Belvedere,39.361495,-76.606720,0.103644
272,Woodmere,39.345432,-76.689104,0.258394
273,Evesham Park,39.365963,-76.604943,0.073435
274,Wyndhurst,39.357396,-76.630030,0.303793
275,Old Goucher,39.316017,-76.617438,0.057931
276,Belair-Edison,39.320670,-76.567779,0.824993
277,Charles Village,39.323801,-76.616122,0.263365

### Supplement EV Charger Data with Neighborhood Data

#### Function to check whether or not a charging station falls within the boundaries of a neighborhood

In [40]:
def check_coords(long_t, lat_t, coords):
#     print('Made it here')
    point = Point(long_t, lat_t)
    polygon = Polygon(coords)

    return polygon.contains(point)
print("Ready")

Ready

#### Function to add neighborhood assignments to EV charging station data

In [41]:
def define_neighborhoods(dataframe):
    # Create an explicit copy of the input DataFrame
    dataframe = dataframe.copy()

    # Loop to generate a unique unit ID
    for i, j in dataframe.iterrows():

        # Capture latitude and longitude values from dataframe row
        longitude = j["Longitude"]
        latitude = j["Latitude"]

        # Iterate through neighborhood coordinates to check whether the coordinates are within a neighborhood
        for neighborhood in neighborhood_array:
            coords = neighborhood['Coords']
            name = neighborhood['Name']
            if check_coords(longitude, latitude, coords):
                dataframe.at[i, 'Neighborhood'] = name
                break
                
    # Output updated dataframe with Unit IDs
    return dataframe
print("Ready")

Ready

In [42]:
ev_data_baltimore = define_neighborhoods(ev_baltimore)
ev_data_baltimore.head()

,ID,Status,Open Date,Name,EV Network,Owner Type,Pricing,Renewable Source,Access Type,Access Details,Access Times,Level 1 Chargers Count,Level 2 Chargers Count,DC Fast Chargers Count,Other Charger Count,NEMA 14-50,NEMA 5-15,NEMA 5-20,J1772,CCS,CHAdeMO,Tesla,Facility Type,Street Address,City,State,Zip Code,Latitude,Longitude,Expected Date,Neighborhood
474,40012,Available,2011-08-15,Municipal Garage,Non-Networked,LG,Free,NA,public,Public,24 hours daily; Drivers must bring their own J...,1,2,0,0,0,0,1,1,0,0,0,FLEET_GARAGE,200 N Holliday St,Baltimore,MD,21202,39.291785,-76.610539,NA,Downtown
653,43190,Available,2012-01-15,UM PTS GRAND,ChargePoint Network,NA,NA,NA,public,Public,24 hours daily,0,2,0,0,0,0,0,1,0,0,0,None,5 N Paca St,Baltimore,MD,21201,39.290036,-76.621894,NA,Downtown
654,43191,Available,2012-01-15,UM PTS PEARL #3,ChargePoint Network,NA,NA,NA,public,Public,24 hours daily,0,2,0,0,0,0,0,1,0,0,0,None,622 W Fayette St,Baltimore,MD,21201,39.290764,-76.624390,NA,University Of Maryland
655,43195,Available,2012-01-15,UM PTS PRATT,ChargePoint Network,NA,NA,NA,public,Public,24 hours daily,0,2,0,0,0,0,0,1,0,0,0,None,646 West Pratt Street,Baltimore,MD,21201,39.286510,-76.624935,NA,University Of Maryland
656,43196,Available,2012-01-15,UM PTS PLAZA #1,ChargePoint Network,NA,NA,NA,public,Public,24 hours daily,0,2,0,0,0,0,0,1,0,0,0,None,500 West Redwood Street,Baltimore,MD,21201,39.288080,-76.622679,NA,University Of Maryland

#### Drop Non-Batlimore Chargers

In [43]:
print(ev_data_baltimore.shape)

# Create a new DataFrame without rows containing NaN in the "Neighborhood" column
ev_data_baltimore = ev_data_baltimore.dropna(subset=["Neighborhood"], axis=0)

# Reset index, because we dropped rows
ev_data_baltimore.reset_index(drop=True, inplace=True)

print(ev_data_baltimore.shape)
ev_data_baltimore

(313, 31)
(269, 31)

,ID,Status,Open Date,Name,EV Network,Owner Type,Pricing,Renewable Source,Access Type,Access Details,Access Times,Level 1 Chargers Count,Level 2 Chargers Count,DC Fast Chargers Count,Other Charger Count,NEMA 14-50,NEMA 5-15,NEMA 5-20,J1772,CCS,CHAdeMO,Tesla,Facility Type,Street Address,City,State,Zip Code,Latitude,Longitude,Expected Date,Neighborhood
0,40012,Available,2011-08-15,Municipal Garage,Non-Networked,LG,Free,NA,public,Public,24 hours daily; Drivers must bring their own J...,1,2,0,0,0,0,1,1,0,0,0,FLEET_GARAGE,200 N Holliday St,Baltimore,MD,21202,39.291785,-76.610539,NA,Downtown
1,43190,Available,2012-01-15,UM PTS GRAND,ChargePoint Network,NA,NA,NA,public,Public,24 hours daily,0,2,0,0,0,0,0,1,0,0,0,None,5 N Paca St,Baltimore,MD,21201,39.290036,-76.621894,NA,Downtown
2,43191,Available,2012-01-15,UM PTS PEARL #3,ChargePoint Network,NA,NA,NA,public,Public,24 hours daily,0,2,0,0,0,0,0,1,0,0,0,None,622 W Fayette St,Baltimore,MD,21201,39.290764,-76.624390,NA,University Of Maryland
3,43195,Available,2012-01-15,UM PTS PRATT,ChargePoint Network,NA,NA,NA,public,Public,24 hours daily,0,2,0,0,0,0,0,1,0,0,0,None,646 West Pratt Street,Baltimore,MD,21201,39.286510,-76.624935,NA,University Of Maryland
4,43196,Available,2012-01-15,UM PTS PLAZA #1,ChargePoint Network,NA,NA,NA,public,Public,24 hours daily,0,2,0,0,0,0,0,1,0,0,0,None,500 West Redwood Street,Baltimore,MD,21201,39.288080,-76.622679,NA,University Of Maryland
5,43440,Available,2012-01-31,EVSP WALGREENS STORE 5623,ChargePoint Network,NA,NA,NA,public,Public,24 hours daily,0,1,0,0,0,0,0,1,0,0,0,None,3801 Liberty Heights Ave,Baltimore,MD,21215,39.326834,-76.681801,NA,Forest Park
6,48038,Available,2012-05-31,MTA LTR MT WASHNGTN,ChargePoint Network,NA,NA,NA,public,Public,24 hours daily,0,2,0,0,0,0,0,1,0,0,0,None,5701 Smith Ave,Baltimore,MD,21209,39.368244,-76.652339,NA,Mount Washington
7,63262,Available,2014-09-12,OAK CREST TOWN CENTER,ChargePoint Network,NA,NA,NA,public,Public,24 hours daily,0,2,0,0,0,0,0,1,0,0,0,None,3700 E Northern Pkwy,Baltimore,MD,21206,39.358460,-76.536562,NA,Overlea
8,63824,Available,2014-10-21,UM PTS PLAZA #2,ChargePoint Network,NA,NA,NA,public,Public,24 hours daily,0,2,0,0,0,0,0,1,0,0,0,None,500-598 W Redwood St,Baltimore,MD,21201,39.288696,-76.623385,NA,University Of Maryland
9,66639,Available,2015-01-12,Maryland Institute College of Art - Commons Hall,Non-Networked,P,Free,NA,public,Public,24 hours daily,0,2,0,0,0,0,0,1,0,0,0,COLLEGE_CAMPUS,130 McMechen St,Baltimore,MD,21217,39.308846,-76.625419,NA,Bolton Hill
10,66640,Available,2015-01-12,Maryland Institute College of Art - Lazarus Ce...,Non-Networked,P,Free,NA,public,Public,8am-5pm daily,0,4,0,0,0,0,0,1,0,0,0,COLLEGE_CAMPUS,131 W North Ave,Baltimore,MD,21201,39.310740,-76.618931,NA,Charles North
11,66641,Available,2015-04-01,University of Baltimore - Maryland Avenue Garage,Non-Networked,P,Free,NA,public,Public,Garage business hours,0,3,0,0,0,0,0,1,0,0,0,COLLEGE_CAMPUS,1104 Maryland Ave,Baltimore,MD,21201,39.302352,-76.617606,NA,Mid-Town Belvedere
12,66642,Available,2015-02-27,Mayflower Properties,Non-Networked,P,Free,NA,public,Public - Call ahead,9am-5pm daily,0,1,0,0,0,0,0,1,0,0,0,OFFICE_BLDG,1110 Morton St,Baltimore,MD,21201,39.302460,-76.616698,NA,Mid-Town Belvedere
13,68278,Available,2015-07-02,First United Evangelical and Reformed Church,Non-Networked,P,Free,NA,public,Public - Call ahead,8am-5pm daily,0,1,0,0,0,0,0,1,0,0,0,STANDALONE_STATION,6115 O'Donnell St,Baltimore,MD,21224,39.281321,-76.542569,NA,O'Donnell Heights
14,68577,Available,2015-08-01,Marriott Garage,Non-Networked,P,Free,NA,public,Public,24 hours daily,0,3,0,0,0,0,0,1,0,0,0,PARKING_GARAGE,101 S Paca St,Baltimore,MD,21201,39.287168,-76.621895,NA,Downtown West
15,69011,Available,2015-08-14,EVSP WALGREENS STORE 5409,ChargePoint Network,NA,NA,NA,public,Public,24 hours daily,0,1,0,0,0,0,0,1,0,0,0,None,4020 Eastern Ave,Baltimore,MD,21224,39.287182,-76.563048,NA,Highlandtown
16,69736,Available,2015-10-01,Redwood Garage,Non-Networked,P,Free,NA,public,Public,24 hours daily,0,4,0,0,0,0,0,1,0,0,0,PARKING_GARAGE,11 S Eutaw St,Baltimore,MD,21201,39.288504,-76.620394,NA,Downtown
17,69942,Available,2015-10-15,Fleet & Eden Garage,Non-Networked,P,Free,NA,public,Public,Garage business hours,0,4,0,0,0,0,0,1,0,0,0,PAY_GARAGE,501 S Eden St,Baltimore,MD,21231,39.285366,-76.598315,NA,Fells Point
18,70442,Available,2015-10-12,Signet Garage,Non-Networked,P,Free,NA,public,Public,24 hours daily,0,8,0,0,0,0,0,1,0,0,0,PARKING_GARAGE,210 Guilford Ave,Baltimore,MD,21202,39.291950,-76.611345,NA,Downtown
19,70535,Available,2015-10-16,Cathedral Garage,Non-Networked,P,Free,NA,public,Public,24 hours daily,0,4,0,0,0,0,0,1,0,0,0,PARKING_GARAGE,320 Cathedral St,Baltimore,MD,21201,39.293793,-76.616977,NA,Downtown
20,70606,Available,2015-10-20,Arena Garage,Non-Networked,P,Free,NA,public,Public,24 hours daily,0,2,0,0,0,0,0,1,0,0,0,PARKING_GARAGE,201 W Baltimore St,Baltimore,MD,21201,39.289385,-76.618742,NA,Downtown
21,70964,Available,2015-11-01,Ivy Car Barn,Non-Networked,P,Free,NA,private,Private,NA,0,2,0,0,0,0,0,1,0,0,0,PARKING_GARAGE,311 E Chase St,Baltimore,MD,21202,39.302532,-76.610935,NA,Johnston Square
22,71142,Available,2015-12-01,Department of General Services - Parking Lot,Non-Networked,P,Free,NA,private,Private,Employee use only,0,8,0,0,0,0,0,1,0,0,0,PARKING_LOT,3800 E Biddle St,Baltimore,MD,21213,39.305588,-76.566117,NA,Orangeville Industrial Area
23,71143,Available,2015-11-15,Water Street Garage,Non-Networked,P,Free,NA,public,Public,24 hours daily,0,6,0,0,0,0,0,1,0,0,0,PARKING_GARAGE,22 S Gray St,Baltimore,MD,21201,39.288514,-76.611444,NA,Downtown
24,71490,Available,2015-11-24,Maryland Institute of College and Art,Non-Networked,P,NA,NA,private,Private,Employee and student use only,0,1,0,0,0,0,0,1,0,0,0,COLLEGE_CAMPUS,1601 W North Ave,Baltimore,MD,21217,39.309895,-76.642505,NA,Penn North
25,72427,Available,2016-01-09,EVSP WALGREENS STORE 7573,ChargePoint Network,NA,NA,NA,public,Public,24 hours daily,0,1,0,0,0,0,0,1,0,0,0,None,6301 York Rd,Baltimore,MD,21212,39.371322,-76.609294,NA,Lake Walker
26,72428,Available,2016-01-09,EVSP WALGREENS STORE 5408,ChargePoint Network,NA,NA,NA,public,Public,24 hours daily,0,1,0,0,0,0,0,1,0,0,0,None,1300 E North Ave,Baltimore,MD,21213,39.312348,-76.599668,NA,East Baltimore Midway
27,72526,Available,2016-01-01,Carrollton Inn,Non-Networked,P,Free,NA,public,Public,8am-5pm daily,0,2,0,0,0,0,0,1,0,0,0,B_AND_B,50 Albermarle St,Baltimore,MD,21202,39.288678,-76.604209,NA,Jonestown
28,72688,Available,2013-10-01,War Memorial Plaza,Non-Networked,LG,Free,NA,public,Public,24 hours daily,0,2,0,0,0,0,0,1,0,0,0,PARKING_LOT,400 E Lexington St,Baltimore,MD,21202,39.291177,-76.609390,NA,Downtown
29,73224,Available,2016-01-23,Fox and Bunting Building,Non-Networked,P,Free,NA,public,Public,8am-5pm M-F,0,2,0,0,0,0,0,1,0,0,0,OFFICE_BLDG,1303 W Mount Royal Ave,Baltimore,MD,21217,39.308041,-76.621291,NA,Bolton Hill
30,73514,Available,2016-02-16,Baltimore City,Non-Networked,LG,Free,NA,public,Public,24 hours daily,0,0,1,0,0,0,0,0,1,1,0,PARKING_LOT,400 E Lexington St,Baltimore,MD,21202,39.291205,-76.609313,NA,Downtown
31,73608,Available,2016-02-11,Hotel Indigo,Non-Networked,P,Free,NA,public,Public,8am-5pm daily,0,4,0,0,0,0,0,1,0,0,0,HOTEL,24 W Franklin St,Baltimore,MD,21201,39.295255,-76.616480,NA,Mount Vernon
32,74037,Available,2016-02-26,Montebello Filtration Plant,Non-Networked,P,Free,NA,public,Public,8am-5pm daily,0,4,0,0,0,0,0,1,0,0,0,MUNI_GOV,3901 Hillen Rd,Baltimore,MD,21218,39.336584,-76.588301,NA,Montebello
33,74345,Available,2016-03-22,Conservatory and Botanic Gardens,Non-Networked,P,Free,NA,public,Public,24 hours daily,0,0,1,0,0,0,0,0,1,1,0,PARK,3100 Swann Dr,Baltimore,MD,21217,39.318709,-76.647197,NA,Druid Hill Park
34,74346,Available,2016-03-14,Patterson Park,Non-Networked,P,Free,NA,public,Public,24 hours daily,0,0,1,0,0,0,0,0,1,1,0,PARK,200 S Linwood Ave,Baltimore,MD,21224,39.288621,-76.576047,NA,Patterson Park
35,74347,Available,2016-03-11,Maryland Center for Veterans Education and Tra...,Non-Networked,P,Free,NA,public,Public,24 hours daily,0,4,0,0,0,0,0,1,0,0,0,OFFICE_BLDG,301 N High St,Baltimore,MD,21202,39.293619,-76.606356,NA,Jonestown
36,74845,Available,2016-04-01,Baltimore Public Works Museum,Non-Networked,P,Free,NA,public,Public,24 hours daily,0,2,0,0,0,0,0,1,0,0,0,MUSEUM,751 Eastern Ave,Baltimore,MD,21202,39.284815,-76.603415,NA,Inner Harbor
37,75526,Available,2016-05-04,EXELON LOWERLEVELGRG4,ChargePoint Network,NA,NA,NA,public,Public,24 hours daily,0,2,0,0,0,0,0,1,0,0,0,None,1401 Dock St,Baltimore,MD,21231,39.280910,-76.598317,NA,Fells Point
38,77180,Available,2016-05-23,City of Baltimore - Department of Public Works,Non-Networked,LG,Free,NA,private,Private - Government only,Key card required; Call 410-685-1109 for more ...,0,6,0,0,0,0,0,1,0,0,0,MUNI_GOV,2331 N Fulton Ave,Baltimore,MD,21217,39.315293,-76.643737,NA,Penn North
39,77181,Available,2016-05-16,City of Baltimore - Parks Maintenance and Fore...,Non-Networked,LG,Free,NA,private,Private,NA,0,3,0,0,0,0,0,1,0,0,0,MUNI_GOV,3100 Shop Rd,Baltimore,MD,21211,39.322334,-76.641002,NA,Druid Hill Park
40,77182,Available,2016-06-13,City of Baltimore - Ashburton Pumping Station,Non-Networked,LG,Free,NA,private,Private,NA,0,4,0,0,0,0,0,1,0,0,0,MUNI_GOV,3099 Liberty Heights Ave,Baltimore,MD,21216,39.322918,-76.667630,NA,Hanlon-Longwood
41,77207,Available,2016-07-15,M&T Bank Stadium,Non-Networked,P,Parking fee,NA,public,Public,Parking lot hours,0,2,1,0,0,0,0,1,1,1,0,ARENA,1101 Russell St,Baltimore,MD,21230,39.279829,-76.622383,NA,Stadium Area
42,79819,Available,2016-11-15,Hamilton Library,Non-Networked,LG,Free,NA,public,Public,Parking lot hours,0,4,1,0,0,0,0,1,1,1,0,LIBRARY,5910 Harford Rd,Baltimore,MD,21214,39.356533,-76.558482,NA,Hamilton Hills
43,79820,Available,2016-07-01,Orleans Street Library,Non-Networked,LG,Free,NA,public,Public,Parking lot hours,0,0,1,0,0,0,0,0,1,1,0,LIBRARY,1303 Orleans St,Baltimore,MD,21231,39.294470,-76.599243,NA,Dunbar-Broadway
44,79821,Available,2016-10-01,Reisterstown Road Library,Non-Networked,LG,Free,NA,public,Public,Parking lot hours,0,2,1,0,0,0,0,1,1,1,0,LIBRARY,6310 Reisterstown Rd,Baltimore,MD,21215,39.354424,-76.700634,NA,Reisterstown Station
45,79822,Available,2016-10-01,Light Street Library,Non-Networked,LG,Free,NA,public,Public,Parking lot hours,0,0,1,0,0,0,0,0,1,1,0,LIBRARY,1251 Light St,Baltimore,MD,21230,39.275068,-76.611912,NA,Federal Hill
46,79944,Available,2016-11-18,Roland Park Library,Non-Networked,P,Free,NA,public,Public,24 hours daily,0,0,1,0,0,0,0,0,1,1,0,LIBRARY,5108 Roland Ave,Baltimore,MD,21210,39.355737,-76.635104,NA,Roland Park
47,80542,Available,2016-12-01,Clifton Park Golf Course,Non-Networked,LG,Free,NA,public,Public,24 hours daily,0,4,0,0,0,0,0,1,0,0,0,REC_SPORTS_FACILITY,2701 St Lo Dr,Baltimore,MD,21213,39.321598,-76.587835,NA,Clifton Park
48,80543,Available,2016-12-01,Carroll Park Golf Course,Non-Networked,LG,Free,NA,public,Public,24 hours daily,0,4,0,0,0,0,0,1,0,0,0,REC_SPORTS_FACILITY,2100 Washington Blvd,Baltimore,MD,21230,39.272670,-76.648655,NA,Carroll Park
49,80545,Available,2016-10-18,Cylburn Arboretum,Non-Networked,P,Free,NA,public,Public,24 hours daily,0,4,0,0,0,0,0,1,0,0,0,PARK,4975 Greenspring Ave,Baltimore,MD,21209,39.352944,-76.659878,NA,Coldspring
50,80546,Available,2016-10-20,Camden Yards,Non-Networked,P,Free,NA,public,Public,24 hours daily,0,4,0,0,0,0,0,1,0,0,0,ARENA,333 W Camden St,Baltimore,MD,21201,39.284664,-76.619604,NA,Stadium Area
51,80550,Available,2016-11-01,Mount Pleasant Ice Arena,Non-Networked,P,Free,NA,public,Public,24 hours daily,0,4,0,0,0,0,0,1,0,0,0,ARENA,6101 Hillen Rd,Baltimore,MD,21239,39.368847,-76.577788,NA,Mt Pleasant Park
52,81373,Available,2017-02-06,Herring Run Library Branch,Non-Networked,LG,Free,NA,public,Public,24 hours daily,0,0,1,0,0,0,0,0,1,1,0,LIBRARY,3801 Erdman Ave,Baltimore,MD,21213,39.315122,-76.569243,NA,Belair-Edison
53,82161,Available,2017-03-08,Canton Waterfront Park,Non-Networked,P,Free,NA,public,Public,24 hours daily,0,2,1,0,0,0,0,1,1,1,0,PARK,3001 Boston St,Baltimore,MD,21224,39.277178,-76.572417,NA,Canton
54,82162,Available,2017-03-09,Gwynns Falls Park,Non-Networked,P,Free,NA,public,Public,24 hours daily,0,0,1,0,0,0,0,0,1,1,0,PARK,4999 Windsor Mill Rd,Baltimore,MD,21207,39.309277,-76.701150,NA,Franklintown
55,82220,Available,2017-03-31,City of Baltimore - Garage,Non-Networked,LG,Free,NA,public,Public,Garage business hours,0,0,1,0,0,0,0,0,1,1,0,PARKING_GARAGE,101 W Dickman St,Baltimore,MD,21230,39.262573,-76.616256,NA,Spring Garden Industrial Area
56,82530,Available,2017-05-10,UM PTS PEARL,ChargePoint Network,NA,NA,NA,public,Public,24 hours daily,0,2,0,0,0,0,0,1,0,0,0,None,626-628 W Fayette St,Baltimore,MD,21201,39.290314,-76.624899,NA,University Of Maryland
57,82531,Available,2017-05-10,UM PTS PRATT 2,ChargePoint Network,NA,NA,NA,public,Public,24 hours daily,0,2,0,0,0,0,0,1,0,0,0,None,646 W Pratt St,Baltimore,MD,21201,39.286369,-76.624740,NA,University Of Maryland
58,85744,Available,2017-03-01,Under Armour - Tide Point Campus,Non-Networked,P,NA,NA,private,Private,NA,0,2,0,0,0,0,0,1,0,0,0,OFFICE_BLDG,1020 Hull St,Baltimore,MD,21230,39.274092,-76.590789,NA,Locust Point Industrial Area
59,86081,Available,2017-07-07,Baltimore Police Department - Western District,Non-Networked,LG,Free,NA,public,Public,24 hours daily,0,2,0,0,0,0,0,1,0,0,0,MUNI_GOV,1034 N Mount St,Baltimore,MD,21217,39.300619,-76.644695,NA,Sandtown-Winchester
60,86084,Available,2017-07-01,Mount Pleasant Golf Course,Non-Networked,P,Free,NA,public,Public,24 hours daily,0,4,0,0,0,0,0,1,0,0,0,REC_SPORTS_FACILITY,6001 Hillen Rd,Baltimore,MD,21239,39.363692,-76.577699,NA,Mt Pleasant Park
61,86085,Available,2017-07-01,Electric Vehicle Institute,Non-Networked,P,Free,NA,public,Public,24 hours daily,0,4,0,0,0,0,0,1,0,0,0,PARK,1120 N Charles St,Baltimore,MD,21201,39.303044,-76.616255,NA,Mid-Town Belvedere
62,86086,Available,2017-07-01,City of Baltimore - Health Department,Non-Networked,P,Free,NA,public,Public,24 hours daily,0,2,0,0,0,0,0,1,0,0,0,MUNI_GOV,1001 E Fayette St,Baltimore,MD,21201,39.291285,-76.603515,NA,Jonestown
63,86230,Available,2017-08-03,100 E. PRATT 100 E PRATT,ChargePoint Network,NA,NA,NA,public,Public,24 hours daily,0,2,0,0,0,0,0,1,0,0,0,None,100 E Pratt St,Baltimore,MD,21202,39.287367,-76.612522,NA,Inner Harbor
64,86709,Available,2015-10-01,Municipal Garage,Non-Networked,LG,Free,NA,private,Private,NA,0,2,0,0,0,0,0,1,0,0,0,FLEET_GARAGE,200 N Holliday St,Baltimore,MD,21202,39.291785,-76.610539,NA,Downtown
65,86713,Available,2017-08-09,West Street Garage,Non-Networked,P,Free,NA,public,Public,24 hours daily,0,1,0,0,0,0,0,1,0,0,0,PARKING_GARAGE,40 E West St,Baltimore,MD,21230,39.276065,-76.613202,NA,Federal Hill
66,86844,Available,2017-08-19,UM PTS LEXINGTON#2,ChargePoint Network,NA,NA,NA,public,Public,24 hours daily,0,2,0,0,0,0,0,1,0,0,0,None,680 W Lexington St,Baltimore,MD,21201,39.292177,-76.626670,NA,University Of Maryland
67,86862,Available,2017-08-01,C.C. Jackson Recreation Center,Non-Networked,LG,Free,NA,public,Public,24 hours daily,0,4,0,0,0,0,0,1,0,0,0,MUNI_GOV,4910 Park Heights Ave,Baltimore,MD,21215,39.347048,-76.673296,NA,Central Park Heights
68,88040,Available,2017-10-01,War Memorial Plaza,Non-Networked,P,Free,NA,public,Public,24 hours daily,0,2,0,0,0,0,0,1,0,0,0,PARK,441-499 E Lexington St,Baltimore,MD,21202,39.291217,-76.609467,NA,Downtown
69,88041,Available,2017-10-01,Baltimore Street Garage,Non-Networked,P,Free,NA,public,Public,24 hours daily,0,8,0,0,0,0,0,1,0,0,0,PARKING_GARAGE,15 Guilford Ave,Baltimore,MD,21202,39.290084,-76.610788,NA,Downtown
70,88341,Available,2017-10-30,Museum of Industry,Non-Networked,P,Free,NA,public,Public,24 hours daily,0,2,0,0,0,0,0,1,0,0,0,MUSEUM,1415 Key Hwy,Baltimore,MD,21230,39.273755,-76.601727,NA,Locust Point Industrial Area
71,88428,Available,2017-11-01,Clifton Mansion,Non-Networked,P,Free,NA,public,Public,24 hours daily,0,2,0,0,0,0,0,1,0,0,0,PARK,2701 Saint Lo Dr,Baltimore,MD,21213,39.319173,-76.587403,NA,Clifton Park
72,88636,Available,2017-11-15,Latrobe Park,Non-Networked,LG,Free,NA,public,Public,24 hours daily,0,4,0,0,0,0,0,1,0,0,0,PARK,1627 E Fort Ave,Baltimore,MD,21230,39.268278,-76.591693,NA,Locust Point Industrial Area
73,91986,Available,2018-02-01,Arena Garage - South Howard Street,Non-Networked,P,Free,NA,public,Public,24 hours daily,0,4,0,0,0,0,0,1,0,0,0,PARKING_GARAGE,99 S Howard St,Baltimore,MD,21201,39.287914,-76.619205,NA,Downtown
74,91987,Available,2018-02-01,Caroline Street Garage,Non-Networked,P,Free,NA,public,Public,24 hours daily,0,4,0,0,0,0,0,1,0,0,0,PARKING_GARAGE,805 S Caroline St,Baltimore,MD,21231,39.282302,-76.596315,NA,Fells Point
75,92011,Available,2018-02-01,Baltimore City Recreation and Parks,Non-Networked,LG,Free,NA,public,Public,24 hours daily,0,3,0,0,0,0,0,1,0,0,0,MUNI_GOV,3201 Boston St,Baltimore,MD,21224,39.276811,-76.570849,NA,Canton Industrial Area
76,92012,Available,2018-02-01,Tidewater Marina,Non-Networked,LG,Free,NA,public,Public,24 hours daily,0,3,0,0,0,0,0,1,0,0,0,MUNI_GOV,321 E Cromwell St,Baltimore,MD,21230,39.264924,-76.606390,NA,Port Covington
77,94729,Available,2018-03-01,Charles Plaza Garage,Non-Networked,P,Free,NA,public,Public,24 hours daily,0,2,0,0,0,0,0,1,0,0,0,PARKING_GARAGE,211 N Liberty Rd,Baltimore,MD,21201,39.291834,-76.616799,NA,Downtown
78,96857,Available,2018-04-01,Atrium Garage,Non-Networked,P,Free,NA,public,Public,24 hours daily,0,3,0,0,0,0,0,1,0,0,0,PARKING_GARAGE,308 W Fayette St,Baltimore,MD,21201,39.290600,-76.620429,NA,Downtown
79,98417,Available,2018-05-18,UM PTS PENN GARAGE,ChargePoint Network,NA,NA,NA,public,Public,24 hours daily,0,2,0,0,0,0,0,1,0,0,0,None,150 south Penn St,Baltimore,MD,21201,39.286503,-76.625567,NA,University Of Maryland
80,98544,Available,2018-05-23,Southway Builders,Non-Networked,P,Free,NA,public,Public,24 hours daily,0,2,0,0,0,0,0,1,0,0,0,OFFICE_BLDG,1318 E Fort Ave,Baltimore,MD,21230,39.269901,-76.595658,NA,Locust Point Industrial Area
81,98835,Available,2018-06-04,Villages at Homeland,Non-Networked,P,Free,NA,public,Public,24 hours daily,0,2,0,0,0,0,0,1,0,0,0,STREET_PARKING,357 Homeland Southway,Baltimore,MD,21212,39.352912,-76.614600,NA,Villages Of Homeland
82,99433,Available,2018-06-22,Villages at Homeland,Non-Networked,P,Free,NA,public,Public,24 hours daily,0,2,0,0,0,0,0,1,0,0,0,STREET_PARKING,313 Homeland Southway,Baltimore,MD,21212,39.353249,-76.614846,NA,Villages Of Homeland
83,99667,Available,2018-07-01,Baltimore Gas & Electric - Spring Gardens,Non-Networked,T,NA,NA,private,Private,NA,0,4,0,0,0,0,0,1,0,0,0,UTILITY,1899 Leadenhall St,Baltimore,MD,21230,39.267809,-76.618086,NA,Spring Garden Industrial Area
84,100326,Available,2018-08-08,Mercy Medical Center - Bunting Garage,Non-Networked,P,Free,NA,public,Public,24 hours daily,0,4,0,0,0,0,0,1,0,0,0,HOSPITAL,301 Saint Paul Pl,Baltimore,MD,21202,39.292550,-76.613550,NA,Downtown
85,100480,Available,2018-07-18,Inter Sign National,Non-Networked,P,NA,NA,private,Private,NA,0,1,0,0,0,0,0,1,0,0,0,OFFICE_BLDG,1123 E Baltimore St,Baltimore,MD,21201,39.290886,-76.600847,NA,Jonestown
86,102762,Available,2018-08-15,Penn Station Garage,Non-Networked,P,Free,NA,public,Public,24 hours daily,0,2,0,0,0,0,0,1,0,0,0,PARKING_GARAGE,1500 N Charles St,Baltimore,MD,21201,39.306655,-76.616222,NA,Mid-Town Belvedere
87,102785,Available,2018-09-01,Old Town - Fire Station,Non-Networked,P,Free,NA,public,Public,24 hours daily,0,4,0,0,0,0,0,1,0,0,0,FIRE_STATION,1110 Hillen St,Baltimore,MD,21202,39.297285,-76.605258,NA,Oldtown
88,104305,Available,2018-10-16,Downunder Garage,Non-Networked,P,NA,NA,public,Public,24 hours daily,0,4,0,0,0,0,0,1,0,0,0,PARKING_GARAGE,110 W Lombard St,Baltimore,MD,21201,39.287861,-76.616633,NA,Downtown
89,104335,Available,2018-10-22,One Light Street,Non-Networked,P,NA,NA,public,Public,Garage business hours,0,2,0,0,0,0,0,1,0,0,0,PARKING_GARAGE,1 Light St,Baltimore,MD,21201,39.289496,-76.613588,NA,Downtown

#### Create a Total Chargers column in the EV charging station data

In [44]:
ev_data_baltimore['Total Chargers'] = ev_data_baltimore.loc[:,chargers].sum(axis=1)
ev_data_baltimore['Total Chargers'].sum()

759

#### Split EV Charging Data into Public and Private Charging Station Dataframes

In [45]:
public_chargers_baltimore = ev_data_baltimore[ev_data_baltimore['Access Type']=='public'].groupby(['Neighborhood','Access Type'])[['Total Chargers']].sum()
public_chargers_baltimore.reset_index(drop=False, inplace=True)
public_chargers_baltimore.rename(columns = {'Total Chargers':'Total Public Chargers'}, inplace = True)

# Use ev_data_baltimore instead of ev_data
private_chargers_baltimore = ev_data_baltimore[ev_data_baltimore['Access Type']=='private'].groupby(['Neighborhood','Access Type'])[['Total Chargers']].sum()
private_chargers_baltimore.reset_index(drop=False, inplace=True)
private_chargers_baltimore.rename(columns = {'Total Chargers':'Total Private Chargers'}, inplace = True)
print("Total Private Chargers: {} in Baltimore".format(private_chargers_baltimore['Total Private Chargers'].sum()))
print("Total Public Chargers: {} in Baltimore".format(public_chargers_baltimore['Total Public Chargers'].sum()))

Total Private Chargers: 64 in Baltimore
Total Public Chargers: 695 in Baltimore

### Vehicle Registrations | USA | All Vehicles by Type

#### Use BeautifulSoup to pull data from the US Registrations by type website
<a href="https://afdc.energy.gov/vehicle-registration">Source</a>

In [46]:
# Specify the URL
url = 'https://afdc.energy.gov/vehicle-registration'

# Send a GET request
response = requests.get(url)

# Parse the HTML content of the page with BeautifulSoup
soup = BeautifulSoup(response.content, 'html.parser')

# Find the table on the page
table = soup.find('table')

# Get the headers of the table but skip the first header because it's blank
headers = [header.text.strip() for header in table.find_all('th')][1:]

# Get the rows of the table
rows = table.find_all('tr')

# Get the data from each row
data = []
for row in rows[1:]:  # Skip the first row because it's the headers
    cols = row.find_all('td')
    cols = [col.text.strip() for col in cols]
    data.append(cols)

# Create a pandas DataFrame from the data
us_vehicle_registrations = pd.DataFrame(data, columns=headers)

# Drop the first row
us_vehicle_registrations = us_vehicle_registrations.drop(0)

# Remove commas from the all columns except for the first column
us_vehicle_registrations.iloc[:, 1:] = us_vehicle_registrations.iloc[:, 1:].replace(',', '', regex=True)

# Set all columns except for the first column to integer type
us_vehicle_registrations.iloc[:, 1:] = us_vehicle_registrations.iloc[:, 1:].astype(int)

us_vehicle_registrations.head()

,State,Electric (EV),Plug-In Hybrid Electric (PHEV),Hybrid Electric (HEV),Biodiesel,Ethanol/Flex (E85),Compressed Natural Gas (CNG),Propane,Hydrogen,Methanol,Gasoline,Diesel
1,Alabama,4700,3300,42500,40500,449500,500,100,0,0,4051000,123500
2,Alaska,1300,500,7300,7600,50100,100,0,0,0,464200,31700
3,Arizona,40700,15500,132200,51000,460400,900,900,0,0,5395300,191800
4,Arkansas,2400,1800,26100,28700,290200,300,0,0,0,2241600,88800
5,California,563100,315300,1355900,163600,1343200,12600,1500,11800,0,30512600,710500

#### Save the Total USA Vehicle Registrations data to an Excel file

In [47]:
# Save dataframe using the save_data function
save_data(us_vehicle_registrations, 'Total_USA_Vehicle_Registration_by_State')

Saving data Total_USA_Vehicle_Registration_by_State.csv
File saved at C:\Users\ChrisPeoples\OneDrive - Peoples Partners and Associates, LLC\PP&A Working Directory\70_Studies_and_Reports\2023_EV_Infrastructure_Trends\data\Total_USA_Vehicle_Registration_by_State.csv/Total_USA_Vehicle_Registration_by_State.csv

### Vehicle Registrations | USA By State | Electric Vehicles
At present, no U.S.-level API data source exists. As such, the data is pulled from the Department of Energy: Alternative Fuels Data Center website: <a href="https://afdc.energy.gov/data/10962">US EV Registrations</a>
After downloading the data, it is uploaded into the notebook from an Excel file. Name the file "US_EV_Registration_Data.xlsx" and save it in the data folder the main project directory.

In [48]:
# Define path to Excel file using output_directory variable
excel_file = os.path.join(output_directory, 'US_EV_Registration_Data.xlsx')

# Read in EV registration data from Excel file. the header is in row 3, and the data is in columns 2 and 3
us_ev_registrations = pd.read_excel(excel_file, sheet_name='EV Registration Counts', header=2, usecols="B:C")

# Set Registration Count column to integer type
us_ev_registrations['Registration Count'] = us_ev_registrations['Registration Count'].astype(int)

us_ev_registrations.head()

        State  Registration Count
0     Alabama                4750
1      Alaska                1290
2     Arizona               40740
3    Arkansas                2390
4  California              563070

### Vehicle Registrations | Maryland by County | All Vehicles (Annual)
<div>Total number of vehicles with active MD registrations by county as of each month end from July 2020 to most recent</div>
<div>Data is pulled from <span><a href="https://opendata.maryland.gov/Transportation/MVA-VEHICLE-REGISTRATION-by-COUNTY-from-2010-to-20/kqkd-4fx8">Maryland Open Data</a></span></div>

In [49]:
# Unauthenticated client only works with public data sets. Note 'None'
# in place of application token, and no username or password:
client = Socrata("opendata.maryland.gov", None)

# Initialize variables
results = []
limit = 2000
offset = 0

# Loop through the dataset using the offset parameter
while True:
    batch = client.get("kqkd-4fx8", limit=limit, offset=offset)
    if not batch:
        break
    results.extend(batch)
    offset += limit

# Convert to pandas DataFrame
total_reg_zip = pd.DataFrame.from_records(results)
total_reg_zip.head()

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

,fiscal_year,allegany,anne_arundel,baltimore,baltimore_city,calvert,caroline,carroll,cecil,charles,dorchester,frederick,garrett,harford,howard,kent,montgomery,prince_george_s,queen_anne_s,somerset,st_mary_s,talbot,washington,wicomico,worcester
0,FY 2010,62813,513278,660553,280793,91108,36699,176842,94305,138672,31742,226529,33303,235366,251713,21453,754641,626009,53779,20570,104488,42116,136894,86553,57117
1,FY 2011,62512,533106,663514,285394,91768,36667,177125,94563,140423,31672,227672,33202,237096,255497,21397,752503,633920,53938,20382,105942,42380,137204,88153,56627
2,FY 2012,62574,537670,669052,289229,93222,36728,177603,95254,141965,32416,230727,33459,236024,258164,21651,755353,643710,54159,20021,108276,42344,137716,87294,57767
3,FY 2013,61390,538501,669201,297990,92699,35749,176281,93408,141107,32056,228442,32942,234421,258498,21191,758413,640226,53259,19495,107802,41680,135787,86735,56148
4,FY 2014,61481,542768,680074,303542,93322,36019,178086,94146,143729,32553,231390,33231,236667,261320,21397,763346,653111,53842,20125,108794,42110,137007,87766,56655

In [50]:
# Save dataframe using the save_data function
save_data(total_reg_zip, 'MD_Total_Vehicle_Registration')

Saving data MD_Total_Vehicle_Registration.csv
File saved at C:\Users\ChrisPeoples\OneDrive - Peoples Partners and Associates, LLC\PP&A Working Directory\70_Studies_and_Reports\2023_EV_Infrastructure_Trends\data\MD_Total_Vehicle_Registration.csv/MD_Total_Vehicle_Registration.csv

### Vehicle Registrations | Maryland by Zip Code | Electric Vehicles (Monthly)

<div>Total number of electric and plug-in hybrid vehicles with active MD registrations by zip code as of each month end from July 2020 to most recent</div>
<div>Data is pulled from <span><a href="https://opendata.maryland.gov/Transportation/MD-MDOT-MVA-Electric-and-Plug-in-Hybrid-Vehicle-Re/tugr-unu9">Maryland Open Data</a></span></div>

In [51]:
# Unauthenticated client only works with public data sets. Note 'None'
# in place of application token, and no username or password:
client = Socrata("opendata.maryland.gov", None)

# Initialize variables
results = []
limit = 2000
offset = 0

# Loop through the dataset using the offset parameter
while True:
    batch = client.get("tugr-unu9", limit=limit, offset=offset)
    if not batch:
        break
    results.extend(batch)
    offset += limit

# Convert to pandas DataFrame
ev_reg_zip = pd.DataFrame.from_records(results)
ev_reg_zip.head()

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

  year_month fuel_category zip_code count
0    2020/07      Electric    19973     1
1    2020/07      Electric    20601    21
2    2020/07      Electric    20602    26
3    2020/07      Electric    20603    54
4    2020/07      Electric    20607    35

### Vehicle Registrations | Maryland by County | Electric Vehicles (Monthly)
<div>Total number of electric and plug-in hybrid vehicles with active MD registrations by county as of each month end from July 2020 to February 2023</div>
<div>Data is pulled from <span><a href="https://opendata.maryland.gov/Transportation/MDOT-MVA-Electric-and-Plug-in-Hybrid-Vehicle-Regis/qtcv-n3tc">Maryland Open Data</a></span></div>

In [52]:
client = Socrata("opendata.maryland.gov", None)

# Initialize variables
results = []
limit = 2000
offset = 0

# Loop through the dataset using the offset parameter
while True:
    batch = client.get("qtcv-n3tc", limit=limit, offset=offset)
    if not batch:
        break
    results.extend(batch)
    offset += limit

# Convert to pandas DataFrame
ev_reg_county = pd.DataFrame.from_records(results)
ev_reg_county.head()

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

  year_month fuel_category          county count
0    2020/07      Electric        ALLEGANY    29
1    2020/07      Electric    ANNE ARUNDEL  1587
2    2020/07      Electric       BALTIMORE  1508
3    2020/07      Electric  BALTIMORE CITY   770
4    2020/07      Electric         CALVERT   140

#### Clean Data
Clean County Total Registration Data

In [53]:
# Create a new dataframe to clean without changing the original dataframe
total_md_reg_counties = total_reg_zip.copy()

# Remove FY from the fiscal_year column
total_md_reg_counties['fiscal_year'] = total_md_reg_counties['fiscal_year'].str.replace('FY','')

# Rename the fiscal_year column to year
total_md_reg_counties.rename(columns = {'fiscal_year':'year'}, inplace = True)

# Set year to index
total_md_reg_counties.set_index('year', inplace=True)

# Convert all columns to numeric
total_md_reg_counties = total_md_reg_counties.apply(pd.to_numeric)

# Create a new dataframe from the sum of all columns
total_md_reg = pd.DataFrame(total_md_reg_counties.sum(axis=1))

# Rename the column to total_registrations
total_md_reg.rename(columns = {0:'total_registrations'}, inplace = True)

total_md_reg.head()

       total_registrations
year
 2010              4737336
 2011              4782657
 2012              4822378
 2013              4813421
 2014              4872481

###### Clean County EV and Plugin Registration Data

In [54]:
# Split the year_month column into year and month columns
ev_reg_county[['year', 'month']] = ev_reg_county['year_month'].str.split('/', expand=True)

# Drop the original year_month column if no longer needed
ev_reg_county.drop('year_month', axis=1, inplace=True)

# Convert the count column to an integer
ev_reg_county['count'] = ev_reg_county['count'].astype(int)

ev_reg_county.head()

  fuel_category          county  count  year month
0      Electric        ALLEGANY     29  2020    07
1      Electric    ANNE ARUNDEL   1587  2020    07
2      Electric       BALTIMORE   1508  2020    07
3      Electric  BALTIMORE CITY    770  2020    07
4      Electric         CALVERT    140  2020    07

<div style="text-decoration: underline;">Build Maryland EV Registration Datasets by County</div>
<ol>
<li>Total MD Cumulative EV and Plugin Registrations by Month</li>
<li>MD Cumulative Electric Vehicle Registrations by Month</li>
<li>MD Cumulative Plug-in Hybrids by Month</li>
</ol>

In [55]:
# Group by county, year, and month and sum the count column
md_ev_reg_count_all_vehicles = ev_reg_county.groupby(['county', 'year', 'month'])['count'].sum().reset_index()

print("Total Electric / Plugin Vehicles: {}".format(md_ev_reg_count_all_vehicles.shape))

md_ev_reg_count_all_vehicles.head()

Total Electric / Plugin Vehicles: (1585, 4)

  county  year month  count
0     AE  2022    06      1
1     AE  2022    07      1
2     AE  2022    08      1
3     AE  2022    09      1
4     AK  2022    08      1

In [56]:
# Group by fuel category
md_ev_reg_count_electric_vehicles = ev_reg_county[ev_reg_county['fuel_category'].isin(['Electric'])].reset_index(drop=True)

print("Electric Vehicles: {}".format(md_ev_reg_count_electric_vehicles.shape))

md_ev_reg_count_electric_vehicles.head()

Electric Vehicles: (1356, 5)

  fuel_category          county  count  year month
0      Electric        ALLEGANY     29  2020    07
1      Electric    ANNE ARUNDEL   1587  2020    07
2      Electric       BALTIMORE   1508  2020    07
3      Electric  BALTIMORE CITY    770  2020    07
4      Electric         CALVERT    140  2020    07

In [57]:
# Group by fuel category plug-in hybrid
md_ev_reg_count_plugin_vehicles = ev_reg_county[ev_reg_county['fuel_category'].isin(['Plug-in Hybrid', 'Plug-In Hybrid'])].reset_index(drop=True)

print("Plug-in Vehicles: {}".format(md_ev_reg_count_plugin_vehicles.shape))

md_ev_reg_count_plugin_vehicles.head()

Plug-in Vehicles: (1482, 5)

    fuel_category          county  count  year month
0  Plug-in Hybrid        ALLEGANY     32  2020    07
1  Plug-in Hybrid    ANNE ARUNDEL   1124  2020    07
2  Plug-in Hybrid       BALTIMORE   1230  2020    07
3  Plug-in Hybrid  BALTIMORE CITY    585  2020    07
4  Plug-in Hybrid         CALVERT    160  2020    07

<div style="text-decoration: underline;">Convert data set from MoM to cumulative data</div>

Function to calculate month-over-month change

In [58]:
def calculate_mom_change(df, group_col, year_col, month_col, value_col, new_col):
    # Convert the 'count' column to integer
    df[value_col] = df[value_col].astype(int)

    # Sort the DataFrame by year and month
    df = df.sort_values([group_col, year_col, month_col])

    # Reset the index before performing the calculation
    df = df.reset_index(drop=True)

    # Create a temporary DataFrame for holding the shifted values
    temp_df = df.groupby(group_col)[value_col].shift(1).fillna(0)

    # Calculate the MoM change and store it in the new column
    df[new_col] = df[value_col] - temp_df

    # Reset the index after performing the calculation
    df = df.reset_index(drop=True)

    return df

print("Done")

Done

##### Calculate Month-over-Month Change

1. Total MD Cumulative EV Registrations by Month

In [59]:
# Calculate month-over-month change for Total EVs
md_ev_reg_count_all_vehicles = calculate_mom_change(md_ev_reg_count_all_vehicles, 'county', 'year', 'month', 'count', 'MoM Change')

md_ev_reg_count_all_vehicles.head()

  county  year month  count  MoM Change
0     AE  2022    06      1         1.0
1     AE  2022    07      1         0.0
2     AE  2022    08      1         0.0
3     AE  2022    09      1         0.0
4     AK  2022    08      1         1.0

2. MD Cumulative Electric Vehicle Registrations by Month

In [60]:
# Calculate month-over-month change for Electric Only
md_ev_reg_count_electric_vehicles = calculate_mom_change(md_ev_reg_count_electric_vehicles, 'county', 'year', 'month', 'count', 'MoM Change')

md_ev_reg_count_electric_vehicles.head()

  fuel_category county  count  year month  MoM Change
0      Electric     AE      1  2022    06         1.0
1      Electric     AE      1  2022    07         0.0
2      Electric     AE      1  2022    08         0.0
3      Electric     AE      1  2022    09         0.0
4      Electric     AK      2  2022    09         2.0

3. MD Cumulative Plug-in Hybrids by Month

In [61]:
# Calculate month-over-month change for Plug-in Hybrid Only
md_ev_reg_count_plugin_vehicles = calculate_mom_change(md_ev_reg_count_plugin_vehicles, 'county', 'year', 'month', 'count', 'MoM Change')

md_ev_reg_count_plugin_vehicles.head()

    fuel_category county  count  year month  MoM Change
0  Plug-In Hybrid     AK      1  2022    08         1.0
1  Plug-In Hybrid     AK      2  2022    09         1.0
2  Plug-In Hybrid     AK      3  2022    10         1.0
3  Plug-In Hybrid     AK      2  2022    11        -1.0
4  Plug-In Hybrid     AK      2  2022    12         0.0

##### Save Data to CSV Files

In [62]:
# Save Total EVs DataFrame to a CSV file
md_ev_reg_count_all_vehicles.to_csv(os.path.join(output_directory, 'md_ev_reg_count_all_vehicles.csv'), index=False)

# Save Electric Only DataFrame to a CSV file
md_ev_reg_count_electric_vehicles.to_csv(os.path.join(output_directory, 'md_ev_reg_count_electric_vehicles.csv'), index=False)

# Save Plug-in Hybrid Only DataFrame to a CSV file
md_ev_reg_count_plugin_vehicles.to_csv(os.path.join(output_directory, 'md_ev_reg_count_plugin_vehicles.csv'), index=False)

In [63]:
# Total count and MoM changes for both vehicle types
total_count_all = md_ev_reg_count_all_vehicles.groupby(['year', 'month']).agg({'count': 'sum', 'MoM Change': 'sum'}).reset_index()

# Total count and MoM changes for "Electric" vehicles
total_count_electric = md_ev_reg_count_electric_vehicles.groupby(['year', 'month', 'fuel_category']).agg({'count': 'sum', 'MoM Change': 'sum'}).reset_index()

# Total count and MoM changes for "Plug-in Hybrid" vehicles
total_count_plugin_hybrid = md_ev_reg_count_plugin_vehicles.groupby(['year', 'month', 'fuel_category']).agg({'count': 'sum', 'MoM Change': 'sum'}).reset_index()
print("Done")

Done

In [64]:
total_count_all.to_csv(output_directory / 'total_count_all.csv', index=False)
total_count_electric.to_csv(output_directory / 'total_count_electric.csv', index=False)
total_count_plugin_hybrid.to_csv(output_directory / 'total_count_plugin_hybrid.csv', index=False)

#### Pull Historic EV data from NREL

In [65]:
import requests
import json

# Define the API endpoint
url = "https://developer.nrel.gov/api/vehicles/v1/vehicles.json"

# Define the headers for the API request
headers = {
    "Accept": "application/json",
    "X-Api-Key": NREL_ID  # Replace with your NREL API key
}

# Make the API request
response = requests.get(url, headers=headers)

# Print the first 1000 characters of the raw response data
print(str(data)[:1000])

# Parse the response
data = response.json()

# Filter the vehicles for electric vehicles in Maryland
filtered_vehicles = [vehicle for vehicle in data if vehicle['fuel_type'] == 'ELEC' and vehicle['state'] == 'MD']

# Print the filtered vehicles
print(json.dumps(filtered_vehicles, indent=4))

[[], ['Alabama', '4,700', '3,300', '42,500', '40,500', '449,500', '500', '100', '0', '0', '4,051,000', '123,500'], ['Alaska', '1,300', '500', '7,300', '7,600', '50,100', '100', '0', '0', '0', '464,200', '31,700'], ['Arizona', '40,700', '15,500', '132,200', '51,000', '460,400', '900', '900', '0', '0', '5,395,300', '191,800'], ['Arkansas', '2,400', '1,800', '26,100', '28,700', '290,200', '300', '0', '0', '0', '2,241,600', '88,800'], ['California', '563,100', '315,300', '1,355,900', '163,600', '1,343,200', '12,600', '1,500', '11,800', '0', '30,512,600', '710,500'], ['Colorado', '37,000', '16,100', '113,600', '53,800', '346,700', '600', '100', '0', '0', '4,456,600', '208,400'], ['Connecticut', '13,300', '9,200', '55,400', '8,800', '140,700', '400', '0', '0', '0', '2,578,400', '44,300'], ['Delaware', '3,000', '2,000', '16,700', '4,100', '67,400', '100', '0', '0', '0', '796,400', '14,600'], ['District of Columbia', '3,700', '2,500', '16,100', '300', '17,400', '100', '0', '0', '0', '278,900',

TypeError: string indices must be integers

### Vehicle Sales | USA | All Vehicles
Due to limited public data on EV sales, we must use the following <a href="https://www.autosinnovate.org/resources/electric-vehicle-sales-dashboard">Autosinnovate Website</a>.
Sourcing of the data is as follows:

In [ ]:
# Build a function to pull annual vehicle sales data from the St. Louis Federal Reserve API
def get_vehicle_sales(api_key):
    # Define the endpoint URL
    url = "https://api.stlouisfed.org/fred/series/observations"

    # Define the parameters
    params = {
        "series_id": "TOTALSA",
        "api_key": api_key,
        "file_type": "json",
        "frequency": "m",  # Fetch monthly data
        "observation_start": "2020-01-01",
        "observation_end": "2023-12-31"
    }

    # Send the HTTP request
    response = requests.get(url, params=params)

    # Check if the request was successful
    if response.status_code == 200:
        # Parse the JSON response
        data = response.json()["observations"]

        # Create a dataframe from the data
        df = pd.DataFrame(data)

        # Convert 'date' column to datetime and 'value' column to float
        df['date'] = pd.to_datetime(df['date'])
        df['value'] = df['value'].astype(float)

        # Group by year and calculate the sum for each year
        df = df.groupby(df['date'].dt.year)['value'].sum().reset_index()

        # Return the dataframe
        return df
    else:
        print(f"Error occurred: {response.status_code}")
        print(response.text)

# Replace "YOUR_API_KEY" with your actual FRED API key
us_vehicle_sales = get_vehicle_sales(FRED_Key)

print(us_vehicle_sales)

#### Save the data to a csv file

In [ ]:
# Save data using the save_data() function
save_data(us_vehicle_sales, "USA_vehicle_sales.csv")

### Vehicle Sales | USA | Electric Vehicles

<p>This notebook includes data on the sales of electric vehicles (EVs) in the United States for the years 2020 to 2023. The data is gathered from multiple sources and is embedded within the text of various web pages.</p>

<p>The sales data for each year is as follows:</p>

<ul>
  <li><strong>2020</strong>: The sales of electric vehicles in 2020 were reported to be 308,000 units (<a href="https://www.energy.gov/eere/vehicles/articles/fotw-1172-january-24-2022-sales-new-light-duty-plug-electric-vehicles-united">source</a>).</li>
  <li><strong>2021</strong>: In 2021, the sales nearly doubled from the previous year, reaching a total of 608,000 units (<a href="https://www.energy.gov/eere/vehicles/articles/fotw-1172-january-24-2022-sales-new-light-duty-plug-electric-vehicles-united">source</a>).</li>
  <li><strong>2022</strong>: The EV market continued to grow in 2022, breaking records with an estimated 918,500 light electric vehicle sales (<a href="https://www.statista.com/statistics/200002/international-car-sales-since-1990/">source</a>).</li>
  <li><strong>2023</strong>: As of April 2023, the cumulative sales of EVs for the year were reported to be 401,135 units (<a href="https://www.anl.gov/es/light-duty-electric-drive-vehicles-monthly-sales-updates">source</a>).</li>
</ul>

<p>The data was manually extracted from the text of these sources and is subject to the accuracy of the reporting by these sources.</p>

In [ ]:
# Creating a dictionary with the EV sales data
data = {
    "Year": [2020, 2021, 2022, 2023],
    "EV Sales": [308000, 608000, 918500, 401135]  # Note: The 2023 data is as of April
}

# Creating a pandas DataFrame from the dictionary
df = pd.DataFrame(data)

# Set year to inded
df.set_index('Year', inplace=True)

# Displaying the DataFrame
df

#### Save the data to a csv file

In [ ]:
# Save data using the save_data() function
save_data(df, "USA_ev_sales.csv")

### Vehicle Sales | Maryland | All Vehicles

In [ ]:
# Unauthenticated client only works with public data sets. Note 'None'
# in place of application token, and no username or password:
client = Socrata("opendata.maryland.gov", None)

# Initialize variables
results = []
limit = 2000
offset = 0

# Loop through the dataset using the offset parameter
while True:
    batch = client.get("un65-7ipd", limit=limit, offset=offset)
    if not batch:
        break
    results.extend(batch)
    offset += limit

# Convert to pandas DataFrame
total_md_sales_zip = pd.DataFrame.from_records(results)
total_md_sales_zip.head()

#### Clean the data

In [ ]:
# Save new datafram
total_md_sales = total_md_sales_zip

# Convert new and used to int
total_md_sales['new'] = total_md_sales['new'].astype(int)
total_md_sales['used'] = total_md_sales['used'].astype(int)

# Sum monthly new and used sales by year
total_md_sales = total_md_sales.groupby(['year'])[['new', 'used']].sum().reset_index()

# Create a total sales column
total_md_sales['total'] = total_md_sales['new'] + total_md_sales['used']

total_md_sales

#### Save the data to a csv file

In [ ]:
# Save to csv file with the save_data() function
save_data(total_md_sales_zip, "MD_vehicle_sales.csv")

### Vehicle Sales | Maryland | Electric Vehicles

At present, it is difficult to find accurate sales data about electric vehicle sales in Maryland. As such, we will develop an estimate using the earlier vehicle sales data points and registration data.

According to the following <a href="https://www.surfky.com/electric-car-sales-maryland">source</a>, electric vehicle sales in Maryland were:
- 2016: 2185
- 2017: 3244
- 2018: 6299
- 2019: 6105
- 2020: 6033

In [ ]:
# Save the data to a dictionary
data = {
    "Year": [2016, 2017, 2018, 2019, 2020],
    "EV Sales": [2185, 3244, 6299, 6105, 6033]
}

# Create a pandas DataFrame from the dictionary
df = pd.DataFrame(data)

# Set year to index
df.set_index('Year', inplace=True)

# Create new dataframe from total_reg_zip
md_reg = total_reg_zip.copy()

# Remove FY from fiscal_year column
md_reg['fiscal_year'] = md_reg['fiscal_year'].str.replace('FY ', '')

# Convert fiscal_year to int
md_reg['fiscal_year'] = md_reg['fiscal_year'].astype(int)

# Rename fiscal_year to year
md_reg.rename(columns={'fiscal_year': 'year'}, inplace=True)

# Set year to index
md_reg.set_index('year', inplace=True)

# Convert all columns to int
md_reg = md_reg.astype(int)

# Sum columns to get total registrations
md_reg['total'] = md_reg.sum(axis=1)

# Keep total column only
md_reg = md_reg[['total']]

md_reg.head()

#### Prepare Maryland registration data and combine with EV sales data

In [ ]:
# Filter to 2015-2020
md_reg = md_reg.loc[2015:2020]

# Create a new column showing the YoY change in number of registrations
md_reg['change'] = md_reg['total'].diff()

# Remove 2015 data
md_reg = md_reg.loc[2016:2020]

md_reg.head()

In [ ]:
# Add total EV sales to the dataframe
md_reg['EV Sales'] = df['EV Sales']
md_reg.head()

In [ ]:
# Calculate the percentage of EV sales
md_reg['% EV Sales'] = md_reg['EV Sales'] / md_reg['total'] * 100
md_reg.head()

#### Save the data to a csv file

## US EV Market Analyis

### Present current state of the EV market in terms of vehicle registrations by state

#### Total US EV Registrations vs. Total US Vehicle Registrations

In [ ]:
# Edit total vehicle data frame to keep the EV column and sum the rest
total_vehicles = to[['State', 'EVs', 'Total']].groupby('State').sum().reset_index()
total_vehicles.head()

## Registration Forecast Modeling

In [ ]:
# Ensure the data has a datetime index
ev_reg_county['date'] = pd.to_datetime(ev_reg_county[['year', 'month']].assign(day=1))
ev_monthly = ev_reg_county.groupby(['fuel_category', 'date']).agg({'count': 'sum'}).reset_index()

# Pivot the data for separate time series for each fuel category
consolidated_ev_data = ev_monthly.pivot_table(index='date', columns='fuel_category', values='count').fillna(0)

if 'Plug-In Hybrid' in consolidated_ev_data.columns and 'Plug-in Hybrid' in consolidated_ev_data.columns:
    consolidated_ev_data['Total Plug-In Hybrid'] = consolidated_ev_data['Plug-In Hybrid'] + consolidated_ev_data['Plug-in Hybrid']

ev_timeseries = consolidated_ev_data['Electric']
plugin_timeseries = consolidated_ev_data['Total Plug-In Hybrid']
print(consolidated_ev_data)
print(ev_timeseries)
print(plugin_timeseries)

Combine Data Sets

In [ ]:
# Combine the EV, Plugin, electricity price, and gas price data sets
combined_data = pd.merge(consolidated_ev_data, gas_prices, left_index=True, right_on='date', how='left')

# Set the index to the date
combined_data = combined_data.set_index('date')

# Consolidate duplicate Plugin Hybrid columns
combined_data['Total Plug-In Hybrid'] = combined_data['Plug-In Hybrid'] + combined_data['Plug-in Hybrid']

# Drop the duplicate Plugin Hybrid columns and rename Total Plug-In Hybrid to Plug-In Hybrid
combined_data = combined_data.drop(columns=['Plug-In Hybrid', 'Plug-in Hybrid'])

# Rename the Electric column to EV
combined_data = combined_data.rename(columns={'Electric': 'ev_registrations'})

# Rename Total Plug-In Hybrid to plugin_hybrid
combined_data = combined_data.rename(columns={'Total Plug-In Hybrid': 'plugin_hybrid_registrations'})

# Index by date
# combined_data = combined_data.set_index('date')

# Add the electricity price data
combined_data = pd.merge(combined_data, electricity_prices, left_index=True, right_on='date', how='left')

# remove rows with missing values or nan
combined_data = combined_data.dropna()

# Set the index to the date
combined_data = combined_data.set_index('date')

combined_data
print(combined_data)

#### Support Formulas

##### Calculate CAGR

In [ ]:
# Function to calculate CAGR
def CAGR(first, last, periods):
    # Monthly periods to annual
    periods = periods / 12
    return (last / first) ** (1 / periods) - 1

##### Plot Forecast Line Connector

In [ ]:
def forecast_plt_connector(hist_df, forecast_df):
    # Get the last date of the historical data
    last_date = hist_df.index[-1]

    # Create new forecast series that includes the last date of the historical data
    new_index = pd.date_range(start=last_date, periods=len(forecast_df.index) + 1, freq='MS')
    connected_forecast = pd.Series(data=np.append(hist_df[-1], forecast_df.values), index=new_index)
    return connected_forecast

### Plot Historic Vehicle Registrations for EVs and Plug-in Hybrids

In [ ]:
# Check the data
print(combined_data.isna().sum())

In [ ]:
# Check for variation
print(combined_data.describe())

In [ ]:
# Check for collinearity
print(combined_data.corr())

In [ ]:
# Check for cointegration
from statsmodels.tsa.vector_ar.vecm import coint_johansen

johansen_test = coint_johansen(combined_data, det_order=0, k_ar_diff=1)

print(johansen_test.lr1)  # Test statistic
print(johansen_test.cvt)  # Critical values

In [ ]:
from statsmodels.tsa.vector_ar.vecm import VECM

vecm_model = VECM(combined_data, coint_rank=1)
vecm_fit = vecm_model.fit()

print(vecm_fit.summary())

In [ ]:
# Suppose 'vecm' is your fitted model, 'lagged_values' are your most recent observations
forecast = vecm_fit.predict(combined_data['ev_registrations'], steps=5)

### Prepare for Time Series Forecasting by checking for Stationarity

In [ ]:
from statsmodels.tsa.api import VAR

# Check for stationarity
model = VAR(combined_data)

# Check for stationarity
for i in range(1, 13):
    result = model.fit(i)
    print('Lag Order =', i)
    print('AIC : ', result.aic)
    print('BIC : ', result.bic)
    print('FPE : ', result.fpe)
    print('HQIC: ', result.hqic, '\n')

### Check for Multicollinearity
Multicollinearity is a phenomenon in which one predictor variable in a multiple regression model can be linearly predicted from the others with a substantial degree of accuracy.

In [ ]:
!pip install seaborn
import seaborn as sns
import matplotlib.pyplot as plt
from statsmodels.stats.outliers_influence import variance_inflation_factor

# Create a correlation matrix
correlation_matrix = combined_data.corr()

# Use seaborn to create a heatmap of the correlation matrix
plt.figure(figsize=(12,8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm')
plt.title('Correlation Matrix')
plt.show()

# Calculate the Variance Inflation Factor (VIF) for each variable
vif_data = pd.DataFrame()
vif_data["feature"] = combined_data.columns
vif_data["VIF"] = [variance_inflation_factor(combined_data.values, i) for i in range(len(combined_data.columns))]
print(vif_data)

### Apply the ADF Test to Check for Stationarity
The Augmented Dickey-Fuller test (ADF test) is a type of statistical test called a unit root test. The null hypothesis of the test is that the time series can be represented by a unit root, that is, it is not stationary (has some time-dependent structure).

The p-value of the ADF test is interpreted as follows:

A small p-value (typically ≤ 0.05) indicates strong evidence against the null hypothesis, so you reject the null hypothesis (which means the data is stationary).
A large p-value (> 0.05) indicates weak evidence against the null hypothesis, so you fail to reject the null hypothesis (which means the data is not stationary).


The ADF statistic needs to be compared with the critical values. If the ADF statistic is less than the critical value, you reject the null hypothesis and can say that the time series is stationary. If the ADF statistic is greater than the critical value, you fail to reject the null hypothesis and can say that the time series is non-stationary.

In [ ]:
from statsmodels.tsa.stattools import adfuller

# Apply the ADF test to each column
for name, column in combined_data.items():
    adf_result = adfuller(column)
    print(f'ADF Statistic for {name}: {adf_result[0]}')
    print(f'p-value: {adf_result[1]}')
    print(f'n_lags: {adf_result[2]}')
    print(f'Num Observations used: {adf_result[3]}')
    print('Critical Values:')
    for key, value in adf_result[4].items():
        print('\t%s: %.3f' % (key, value))
    print('\n')

### Difference the Series to Make it Stationary
Differencing the series is a way to remove the trend and make the series stationary. You can difference the series by subtracting the previous observation from the current observation. You can also difference the series by subtracting the series from itself with a time lag. The lag value is called the order of differencing. The order of differencing is the number of times you have to difference the series to make it stationary.

In [ ]:
# Differencing the series
combined_data_diff = combined_data.diff().dropna()

# Then you can check stationarity again
for name, column in combined_data_diff.items():
    adf_result = adfuller(column)
    print(f'ADF Statistic for {name}: {adf_result[0]}')
    print(f'p-value: {adf_result[1]}')
    print(f'n_lags: {adf_result[2]}')
    print(f'Num Observations used: {adf_result[3]}')
    print('Critical Values:')
    for key, value in adf_result[4].items():
        print('\t%s: %.3f' % (key, value))
    print('\n')

In [ ]:
# Second order differencing
combined_data_diff_2 = combined_data_diff.diff().dropna()

# Then check stationarity again
for name, column in combined_data_diff_2.items():
    adf_result = adfuller(column)
    print(f'ADF Statistic for {name}: {adf_result[0]}')
    print(f'p-value: {adf_result[1]}')
    print(f'n_lags: {adf_result[2]}')
    print(f'Num Observations used: {adf_result[3]}')
    print('Critical Values:')
    for key, value in adf_result[4].items():
        print('\t%s: %.3f' % (key, value))
    print('\n')

In [ ]:
# Plot the differenced series
plt.figure(figsize=(12,8))
plt.plot(combined_data_diff)
plt.title('Differenced Series')
plt.show()

In [ ]:
# Create a boxplot for each variable
plt.figure(figsize=(12,8))
sns.boxplot(data=combined_data)
plt.title('Boxplot of Variables')
plt.show()

In [ ]:
# Define the start date of the forecast period using the last date in the EV timeseries data and adding one
start_date = ev_timeseries.index[-1] + pd.DateOffset(months=1)

# Define the end date of the forecast period by adding a specified number of years to the start date
end_date = start_date + pd.DateOffset(years=5)
# end_date = '2027-12'
print(f'The forecast period goes from {start_date.year}-{start_date.month} to {end_date.year}-{end_date.month}')

In [ ]:
from statsmodels.tsa.api import VAR

model = VAR(combined_data_diff_2)
results = model.fit(5) # Use the optimal lag order found earlier or use a new one.

# To view model summary
print(results.summary())

In [ ]:
# Forecasting
lag_order = results.k_ar
forecast_input = combined_data_diff_2.values[-lag_order:]
forecast_steps = 5 # Number of steps to forecast

# Forecast
forecast_output = results.forecast(y=forecast_input, steps=forecast_steps)
print(forecast_output)

In [ ]:
# Place the forecasted output into a DataFrame
forecast_df = pd.DataFrame(forecast_output, columns=combined_data.columns)

# Reverse the second order differencing (Take a cumulative sum)
forecast_df_cumsum = forecast_df.cumsum()

# Add the last value from the original series
forecast_df_cumsum += combined_data_diff.iloc[-1]

# Now reverse the first order differencing
forecast_df_cumsum = forecast_df_cumsum.cumsum()

# Add the last value from the shifted series
forecast_df_cumsum += combined_data.iloc[-1]

print(forecast_df_cumsum)

In [ ]:
import matplotlib.pyplot as plt

# Plot historic data
plt.figure(figsize=(12,8))
for i in combined_data.columns:
    plt.plot(combined_data.index, combined_data[i], label=i)
plt.title("Historic Data")
plt.xlabel("Time")
plt.ylabel("Value")
plt.legend()
plt.show()

# Plot forecasted data
# First, make sure that your forecasted DataFrame has a DateTime index
forecast_start_date = combined_data.index[-1] + pd.DateOffset(months=1)
forecast_end_date = forecast_start_date + pd.DateOffset(months=forecast_steps-1)
forecast_dates = pd.date_range(forecast_start_date, forecast_end_date, freq='M')

forecast_df_cumsum.index = forecast_dates

plt.figure(figsize=(12,8))
for i in forecast_df_cumsum.columns:
    plt.plot(forecast_df_cumsum.index, forecast_df_cumsum[i], label=i)
plt.title("Forecasted Data")
plt.xlabel("Time")
plt.ylabel("Value")
plt.legend()
plt.show()

In [ ]:
forecast_steps = 62

# Fit the VAR model and forecast
model = VAR(endog=combined_data_diff_2)
model_fit = model.fit(maxlags=12)

# Getting the last lag order number of observations
lag_order = model_fit.k_ar
last_observations = combined_data_diff_2.values[-lag_order:]

# Create the forecast
forecast = model_fit.forecast(y=last_observations, steps=forecast_steps)

# Convert forecast array into dataframe
forecast_df = pd.DataFrame(forecast, columns=combined_data_diff_2.columns)

# Undo the second differentiation (add first_diff_df's last value)
for col in forecast_df.columns:
    forecast_df[col] = forecast_df[col].cumsum() + combined_data_diff[col].iloc[-1]

# Undo the first differentiation
forecast_df_cumsum = forecast_df.cumsum() + combined_data.iloc[-1]

# Select only ev_registrations column
forecast_ev_registrations = forecast_df_cumsum['ev_registrations']

# Create a date range for the forecast data
forecast_start_date = combined_data.index[-1] + pd.DateOffset(months=1)
forecast_dates = pd.date_range(start=forecast_start_date, periods=forecast_steps, freq='M')

# Assign the new date range to the forecast
forecast_ev_registrations.index = forecast_dates

# Plot the historic and forecast results
plt.figure(figsize=(12,8))
plt.plot(combined_data['ev_registrations'], label='Historic')
plt.plot(forecast_ev_registrations, label='Forecast')
plt.legend(loc='upper left')
plt.title('EV Registrations: Historic vs Forecast')
plt.show()

In [ ]:
# Calculate CAGRs
ev_cagr = CAGR(ev_timeseries[0], ev_timeseries[-1], len(ev_timeseries) - 1)
plugin_cagr = CAGR(plugin_timeseries[0], plugin_timeseries[-1], len(plugin_timeseries) - 1)

plt.figure(figsize=(14, 7))

# Plotting the Electric Vehicles forecast
plt.plot(ev_timeseries.index, ev_timeseries, label='Registered Electric Vehicles')

# Plotting the Plug-in Hybrids forecast
plt.plot(plugin_timeseries.index, plugin_timeseries, label='Registered Plug-in Hybrids')

plt.text(0.01, 0.95, f'Historical EV CAGR: {ev_cagr * 100:.2f}%', transform=plt.gca().transAxes)
plt.text(0.01, 0.90, f'Historical Plugin Hybrid CAGR: {plugin_cagr * 100:.2f}%', transform=plt.gca().transAxes)

# Formatting the x-axis to display years only
years = mdates.YearLocator()   # Every year
years_fmt = mdates.DateFormatter('%Y')
ax = plt.gca()
ax.xaxis.set_major_locator(years)
ax.xaxis.set_major_formatter(years_fmt)

# Adding title and labels
plt.title('Historic Electric Vehicles and Plug-in Hybrids Vehicle Registrations in Maryland')
plt.xlabel('Year')
plt.ylabel('Vehicle Registrations')
plt.legend()
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')

# Display the plot
plt.tight_layout()
plt.show()

## Forecasting Vehicle Registrations | Approach 1 - SARIMAX No Policy

This forecast takes a simple view of the data and assumes that the growth rate of the last year will continue into the future. This is a very simple approach and does not take into account any seasonality or other factors that may affect the growth rate of the data.

The model used to do this is the SARIMAX model from the statsmodels library. The model is fit to the data and then used to forecast the next 5 years of data. The SARIMAX model is a seasonal ARIMA model that takes into account the seasonality of the data.

Predictions are made for both the EV and Plugin Hybrid data. The predictions are then plotted against the historic data to see how well the model fits the data. The model does a good job of fitting the data, but it does not take into account any seasonality or other factors that may affect the growth rate of the data.

### Build and Prep SARIMAX model

#### Understanding SARIMAX Parameters

The `order` and `seasonal_order` parameters in the SARIMAX model refer to the orders of different components of the model. These components include:

- AR (AutoRegressive) - In the context of time series forecasting, an autoregressive model predicts future values based on past values. It's called "autoregressive" because it regresses the variable on itself. In simpler terms, it uses previous data points to predict the next data point. For instance, in an AR model of order 1 (AR(1)), the current value is based on the immediately preceding one.
- I (Integrated) - Integrated is the I in ARIMA, which stands for AutoRegressive Integrated Moving Average. It refers to the differencing of raw observations to allow for the time series to become stationary, i.e., data values are replaced by the difference between the data values and the previous values. A time series that has been made stationary through differencing is said to be integrated.
- MA (Moving Average) - In the context of time series forecasting, a moving average model uses past forecast errors in a regression-like model. It takes a set of observations, calculates the mean of those observations and uses this to forecast future values. In this model, the value of a variable at a given time is based on a linear combination of past errors.
- Seasonality - In time series analysis, seasonality refers to predictable and repeating patterns or cycles of behavior that occur over the course of the year, or over any other fixed period in the data. For instance, in retail, sales might regularly peak in December due to holiday shopping and be at their lowest in January, post-holiday season. This is a pattern that repeats every year and is thus a seasonal effect. Models like SARIMAX can handle seasonality.

For `order=(p, d, q)`, the parameters represent:
- `p`: The order of the autoregressive part (AR). This specifies the number of lags of the series to include in the AR part of the model.
- `d`: The degree of differencing (I). This specifies the number of times the series should be differenced to make it stationary.
- `q`: The order of the moving average part (MA). This specifies the number of lagged forecast errors to include in the MA part of the model.

For `seasonal_order=(P, D, Q, s)`, the parameters represent:
- `P`: The order of the seasonal part of the autoregressive model (SAR).
- `D`: The degree of seasonal differencing.
- `Q`: The order of the seasonal part of the moving average model (SMA).
- `s`: The length of the seasonal cycle.

So in the given model, `SARIMAX(df, order=(1, 1, 1), seasonal_order=(1, 1, 1, 12))`, we have:
- An AR order of 1, meaning the model uses one prior value (lag=1) in the autoregressive part.
- An I order of 1, meaning the model applies first order differencing to make the time series stationary.
- An MA order of 1, meaning the model uses one lagged forecast error in the moving average part.
- Seasonal components with the same AR, I, and MA orders of 1, with a seasonal cycle of 12 periods (indicating a yearly cycle, assuming the data is monthly).

#### Define SARIMAX No Policy Forecast Function

In [ ]:
# Function to forecast EV sales
def forecast_ev_sales(df, start_date, end_date):
    # Ensure frequency of index is monthly start (MS)
    df.index = pd.DatetimeIndex(df.index, freq='MS')

    # Calculate the first order difference of the data to make it stationary, if necessary
    df_diff = df.diff().dropna()

    # Initiate SARIMAX model with orders (1, 1, 1) for AR, I, and MA and seasonal orders (1, 1, 1, 12)
    model = SARIMAX(df, order=(1, 1, 1), seasonal_order=(1, 1, 1, 12))

    # Fit the SARIMAX model
    results = model.fit()

    # Get the forecast for the specified period, using the fitted model
    forecast = results.get_prediction(start=pd.to_datetime(start_date), end=pd.to_datetime(end_date), dynamic=False)

    # Return the predicted mean values
    return forecast.predicted_mean

# Function to run the forecast with no policy
def run_forecast_no_policy(df, end_date):
    # Define the start date as the month after the last date in the provided dataframe
    start_date = df.index[-1] + pd.DateOffset(months=1)

    # Print the forecast start date
    print(f"Forecast start date: {start_date}")

    # Generate the forecast using the forecast_ev_sales function
    forecast = forecast_ev_sales(df, start_date, end_date)

    # Return the forecast
    return forecast

#### Set Forecast Parameters

### Forecast Results for MD EVs and Plugin Hybrids

In [ ]:
# Run the forecast on EV time series data
ev_forecast_no_policy = run_forecast_no_policy(ev_timeseries, end_date)

# Run the forecast on Plugin Hybrid time series data
plugin_forecast_no_policy = run_forecast_no_policy(plugin_timeseries, end_date)

# Print the historical and forecasted EV data
print("EV Hist and Forecast")
print(ev_timeseries)
print(ev_forecast_no_policy)

# Print the historical and forecasted Plugin Hybrid data
print("Plugin Hist and Forecast")
print(plugin_timeseries)
print(plugin_forecast_no_policy)

### Plot the Forecasted EV and Plugin Hybrid Sales

#### Define Forecast Plotting Functions

##### Function to Connect the Forecasted Series to the Original Series for line plotting

In [ ]:
# Function to connect the forecasted series to the original series
def forecast_plt_connector(hist_df, forecast_df):
    # Get the last date of the historical data
    last_date = hist_df.index[-1]

    # Create new forecast series that includes the last date of the historical data
    new_index = pd.date_range(start=last_date, periods=len(forecast_df.index) + 1, freq='MS')
    connected_forecast = pd.Series(data=np.append(hist_df[-1], forecast_df.values), index=new_index)
    return connected_forecast

##### Function to line plot the Forecasted Series

In [ ]:
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from matplotlib.gridspec import GridSpec

def plot_forecasts_line(forecast_dict, title):
    # Define the grid layout
    num_categories = len(forecast_dict)
    num_rows = num_categories // 3 + (num_categories % 3 > 0)
    gs = GridSpec(num_rows + 2, 3)  # +2 for the plot and increased space for table

    fig = plt.figure(figsize=(14, num_rows * 9))  # Adjust the figure size based on the number of rows
    ax = fig.add_subplot(gs[:num_rows + 1, :])  # The plot occupies the first num_rows+1 rows

    colors = ['darkblue', 'lightblue', 'darkgreen', 'lightgreen']
    color_index = 0

    for forecast_type, forecast_data in forecast_dict.items():
        timeseries = forecast_data['timeseries']
        forecast = forecast_data['forecast']

        # Plot historic data
        ax.plot(timeseries.index, timeseries, color=colors[color_index], label=f'{forecast_type} Historic')

        # Connect and plot forecast
        connected_forecast = forecast_plt_connector(timeseries, forecast)
        ax.plot(connected_forecast.index, connected_forecast, color=colors[(color_index+1)], label=f'{forecast_type} Forecast')

        # Compute and display CAGR
        connected_cagr = CAGR(timeseries[0], connected_forecast[-1], len(timeseries) + len(connected_forecast) - 1)

        # Additional descriptors
        total_added = round(connected_forecast[-1] - timeseries[0])
        descriptors = f'{forecast_type} Registrations:\nStarting of Historic: {round(timeseries[0]):,} EVs as of {timeseries.index[0].year}/{timeseries.index[0].month}\nEnd of Historic: {round(timeseries[-1]):,} EVs as of {timeseries.index[-1].year}/{timeseries.index[-1].month}\nEnd of Forecast: {round(connected_forecast[-1]):,} EVs as of {connected_forecast.index[-1].year}/{connected_forecast.index[-1].month}\nTotal vehicles added: {total_added:,}\nTotal % growth over period: {((connected_forecast[-1] - timeseries[0])/timeseries[0])*100:,.2f}%\nCAGR ({timeseries.index[0].year}/{timeseries.index[0].month} - {connected_forecast.index[-1].year}/{connected_forecast.index[-1].month}) - {connected_cagr * 100:.2f}%'

        # Create a subplot for the descriptors and add the descriptors as text to the subplot
        ax_desc = fig.add_subplot(gs[num_rows + 1 + color_index // 3, color_index % 3])
        ax_desc.text(0, 1, descriptors, horizontalalignment='left', verticalalignment='top', fontsize=10, bbox=dict(facecolor='white', alpha=0.8))
        ax_desc.axis('off')  # Hide the axes

        color_index += 2

    # Formatting the x-axis to display years only
    years = mdates.YearLocator()   # Every year
    years_fmt = mdates.DateFormatter('%Y')
    ax.xaxis.set_major_locator(years)
    ax.xaxis.set_major_formatter(years_fmt)

    # Adding title and labels
    ax.set_title(title)
    ax.set_xlabel('Year')
    ax.set_ylabel('Vehicle Registrations')
    ax.legend(bbox_to_anchor=(1.05, 1), loc='upper left')

    # Display the plot
    plt.tight_layout()
    plt.show()


plot_forecasts_line(forecast_data, '5-Year Forecasted Electric Vehicles and Plug-in Hybrid Registrations in Maryland (No Policy)')

#### Electric Vehicle Historic and Forecast Plot functions

In [ ]:
# Function to plot the forecasted data
def plot_forecast_bar(timeseries, forecast, type):
    # Calculate CAGRs
    timeseries_cagr = CAGR(timeseries[0], timeseries[-1], len(timeseries) - 1)
    forecast_cagr = CAGR(forecast[0], forecast[-1], len(forecast) - 1)

    # Plotting the forecasts
    plt.figure(figsize=(14, 7))

    # Plotting the historical Electric Vehicles data
    plt.bar(timeseries.index, timeseries, color='blue', label=f'Historical {type} Data', width=20)

    # Plotting the forecasted Electric Vehicles data
    plt.bar(forecast.index, forecast, color='lightblue', label=f'Forecasted {type} Data', width=20)

    # Adding CAGR text
    plt.text(0.01, 0.95, f'Historical {type} CAGR: {timeseries_cagr * 100:.2f}%', transform=plt.gca().transAxes)
    plt.text(0.01, 0.90, f'Forecasted {type} CAGR: {forecast_cagr * 100:.2f}%', transform=plt.gca().transAxes)

    # Formatting the x-axis to display years only
    years = mdates.YearLocator()   # Every year
    years_fmt = mdates.DateFormatter('%Y')
    ax = plt.gca()
    ax.xaxis.set_major_locator(years)
    ax.xaxis.set_major_formatter(years_fmt)

    # Adding title and labels
    plt.title(f'Sales for {type}s in Maryland')
    plt.xlabel('Year')
    plt.ylabel('Sales')
    plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')

    # Display the plot
    plt.tight_layout()
    plt.show()

In [ ]:
forecast_data = {
    'Registered Electric Vehicles': {'timeseries': ev_timeseries, 'forecast': ev_forecast_no_policy},
    'Registered Plug-in Hybrids': {'timeseries': plugin_timeseries, 'forecast': plugin_forecast_no_policy},
    'Total Registered Vehicles': {'timeseries': total_timeseries, 'forecast': total_forecast_no_policy}
}

plot_forecasts_line(forecast_data, '5-Year Forecasted Electric Vehicles and Plug-in Hybrid Registrations in Maryland (No Policy)')

In [ ]:
plot_forecast_bar(ev_timeseries, ev_forecast_no_policy, 'Electric Vehicle')

In [ ]:
plot_forecast_bar(plugin_timeseries, plugin_forecast_no_policy, 'Plug-in Hybrid')

#### Electric Vehicle Historic and Forecast

In [ ]:
print("EV Historic Data")
print(ev_timeseries)
print("EV Forecast Data")
print(ev_forecast_no_policy)
print("PHV Historic Data")
print(plugin_timeseries)
print("PHV Forecast Data")
print(plugin_forecast_no_policy)

### Forecasting Policy Scenarios

#### Electric Vehicle Policy Scenario

In [ ]:
import statsmodels.api as sm
import pandas as pd

# Assuming df is your DataFrame and it has the columns mentioned above
X = df[['Ownership Tax Benefits', 'Charger Density', 'Household Disposable Income', 'Purchase Subsidies', 'Registration Tax Benefits', 'Value Added Tax Benefits', 'Charging Density', 'Road Priority', 'Waiver on Fee', 'Gasoline Price', 'Household Electricity Price']]
y = df['EV Market Share']

# Add a constant to the independent value
X = sm.add_constant(X)

# Make the Panel Regression model
model = sm.OLS(y, X)

# fit the model and print results
results = model.fit()
print(results.summary())

In [ ]:
import statsmodels.api as sm

def create_policy_impact(time_series, policy_start_date, ev_impact, phv_impact):
    policy_start_period = pd.Period(policy_start_date, freq='M')
    policy_impact = np.zeros(len(time_series))
    policy_impact[time_series.index >= policy_start_period] = 1

    return policy_impact * ev_impact, policy_impact * phv_impact

policy_start_date = '2024-01'
ev_impact = 0.20
phv_impact = 0.15

ev_policy_impact, phv_policy_impact = create_policy_impact(ev_time_series, policy_start_date, ev_impact, phv_impact)

def forecast_ev_sales_with_policy(df, exog, end_date, future_exog):
    model = sm.tsa.statespace.SARIMAX(df, order=(1, 1, 1), seasonal_order=(1, 1, 0, 12), exog=exog)
    results = model.fit(disp=0)

    forecast_start_period = pd.Period(df.index[-1], freq='M') + 1
    forecast_end_period = pd.Period(end_date, freq='M')

    print(f"Forecast Start Period: {forecast_start_period}")
    print(f"Forecast End Period: {forecast_end_period}")

    # Select only out-of-sample exog data
    out_of_sample_exog = future_exog[-(forecast_end_period - forecast_start_period).n - 1:]  # Adjusted here

    required_periods = (forecast_end_period - forecast_start_period).n
    print(f"Required periods: {required_periods}, Provided periods: {len(out_of_sample_exog)}")

    print(f"Shape of out_of_sample_exog: {out_of_sample_exog.shape}")

    forecast = results.get_prediction(start=forecast_start_period, end=forecast_end_period, dynamic=False, exog=out_of_sample_exog)
    return forecast.predicted_mean


def create_future_exog(start_period, end_period, last_policy_impact, policy_start_date, new_policy_impact):
    # Create a new DataFrame to hold the future exog data
    future_exog = pd.DataFrame(index=pd.period_range(start=start_period, end=end_period, freq='M'))

    # Assume that the policy impact remains the same as the last known impact before the future period
    future_exog['Policy Impact'] = last_policy_impact

    policy_start_period = pd.Period(policy_start_date, freq='M')
    if policy_start_period >= start_period:
        # Calculate the remaining policy impact after the policy_start_period
        remaining_policy_impact = new_policy_impact[(policy_start_period - start_period).n:]

        # Extend the remaining_policy_impact to match the length of the future period if needed
        if len(remaining_policy_impact) < len(future_exog.loc[policy_start_period:]):
            remaining_policy_impact = np.pad(remaining_policy_impact, (0, len(future_exog.loc[policy_start_period:]) - len(remaining_policy_impact)), 'edge')

        # Assign the remaining policy impact to the future exog data
        future_exog.loc[policy_start_period:, 'Policy Impact'] = remaining_policy_impact

    # Add one additional month to the future exog array
    next_month = pd.Period(end_period + 1, freq='M')
    future_exog.loc[next_month] = future_exog.iloc[-1]


    print(f"Size of future_exog: {len(future_exog)}")
    print(future_exog)
    return future_exog

policy_start_date = '2024-01'
start_date = '2022-01'  # Update the start_date to '2022-01' instead of '2023-12'
end_date = '2027-12'


# Calculate the number of periods between start_date and end_date
start_period = pd.Period(start_date, freq='M')
end_period = pd.Period(end_date, freq='M')

# Create the future exog arrays with the correct size
ev_future_exog = create_future_exog(start_period, end_period, ev_policy_impact[-1], policy_start_date, ev_policy_impact)

electric_forecast_with_policy = forecast_ev_sales_with_policy(ev_time_series, ev_policy_impact, end_date, ev_future_exog)

print("Electric Forecast with Policy Impact:")
print(electric_forecast_with_policy)

In [ ]:
import matplotlib.pyplot as plt


historic_data = ev_time_series
forecast_with_policy = electric_forecast_with_policy

plt.figure(figsize=(10, 6))

# plot the actual data
plt.plot(historic_data, label='Actual Sales')

# plot the forecasted data
plt.plot(forecast_with_policy, label='Forecasted Sales with Policy Impact')
plt.plot(electric_forecast_series, label='Forecasted Sales with no Policy Impact')

plt.title('EV Sales Forecast with Policy Impact')
plt.xlabel('Time')
plt.ylabel('Sales')
plt.legend()

plt.show()

#### EV and PHEV Sales Forecast with Complex Policy Scenarios
In this notebook, we aim to forecast the sales of electric vehicles (EVs) and plug-in hybrid vehicles (PHEVs) while incorporating the impact of various policy scenarios. Our approach utilizes the SARIMAX model to predict future sales, accounting for policy impacts as exogenous variables.

Approach
Load and preprocess the EV and PHEV time series data.
Forecast the baseline sales of EVs and PHEVs without considering any policy impacts.
Create a function to generate policy impact arrays based on given policy start dates, durations, and impact percentages.
Develop complex policy scenarios by combining multiple policy impacts.
Modify the SARIMAX model to include policy impacts as exogenous variables.
Forecast EV and PHEV sales under the defined complex policy scenarios.
Compare the forecasts with and without policy impacts.
Policy Scenarios
We will analyze the following policy scenarios:

Scenario A: A policy is implemented starting in January 2024, lasting for 24 months. It has a 25% impact on EV sales and a 20% impact on PHEV sales.
Scenario B: A policy is implemented starting in July 2024, lasting for 36 months. It has a 15% impact on EV sales and a 10% impact on PHEV sales.
Scenario C: A policy is implemented starting in January 2025, with no specified end date. It has a 10% impact on EV sales and a 5% impact on PHEV sales.
We will create combined policy impacts for EV and PHEV sales by summing the impacts of the individual scenarios. Then, we will use the SARIMAX model to forecast sales for the complex policy scenarios and compare the results with the baseline forecasts without policy impacts.

This analysis will provide insights into the potential effects of policy interventions on EV and PHEV sales, helping policymakers and industry stakeholders make informed decisions.

In [ ]:
import statsmodels.api as sm
import warnings

# Ignore specific warnings
warnings.filterwarnings('ignore', 'Non-stationary starting autoregressive parameters')
warnings.filterwarnings('ignore', 'Non-stationary starting seasonal autoregressive')

# Your code here

# Function to create policy impact arrays
def create_policy_impact(time_series, policy_start_date, ev_impact, phv_impact):
    policy_start_period = pd.Period(policy_start_date, freq='M')
    policy_impact = np.zeros((len(time_series), 1))
    policy_impact[time_series.index >= policy_start_period] = 1

    return policy_impact * ev_impact, policy_impact * phv_impact

# Define policy impact parameters
policy_start_date = '2024-01'
ev_impact = 0.20
phv_impact = 0.15

# Calculate policy impacts for EV and PHV
ev_policy_impact, phv_policy_impact = create_policy_impact(ev_time_series, policy_start_date, ev_impact, phv_impact)

# Function to forecast EV sales with policy impact
def forecast_ev_sales_with_policy(df, exog, end_date, future_exog, time_series_start_date):
    model = sm.tsa.statespace.SARIMAX(df, exog=exog, order=(1, 1, 1), seasonal_order=(0, 1, 1, 12))
    results = model.fit()

    # Calculate the start and end periods for the forecasting range
    forecast_start_period = pd.Period(time_series_start_date, freq='M') + len(df)
    forecast_end_period = pd.Period(end_date, freq='M')

    # Perform the forecast
    forecast = results.get_prediction(start=forecast_start_period, end=forecast_end_period, dynamic=False, exog=future_exog)
    return forecast.predicted_mean

# Function to create future exogenous arrays
# Function to forecast EV sales with policy impact
def forecast_ev_sales_with_policy(df, exog, end_date, future_exog):
    model = sm.tsa.statespace.SARIMAX(df, order=(1, 1, 1), seasonal_order=(1, 1, 0, 12), exog=exog)
    results = model.fit(disp=0)

    forecast_start_period = pd.Period(df.index[-1], freq='M') + 1
    forecast_end_period = pd.Period(end_date, freq='M')

    required_periods = (forecast_end_period - forecast_start_period).n + 1
    out_of_sample_exog = future_exog[:required_periods]

    print(f"Required periods: {required_periods}, Provided periods: {len(out_of_sample_exog)}")

    forecast = results.get_prediction(start=forecast_start_period, end=forecast_end_period, dynamic=False, exog=out_of_sample_exog)
    return forecast.predicted_mean

# Define date range for forecasting
start_date = '2022-01'
end_date = '2027-12'

# Calculate the number of periods between start_date and end_date
start_period = pd.Period(start_date, freq='M')
end_period = pd.Period(end_date, freq='M')

# Create the future exog arrays with the correct size
ev_future_exog = create_future_exog(start_period, end_period, ev_policy_impact[-1], policy_start_date)
phv_future_exog = create_future_exog(start_period, end_period, phv_policy_impact[-1], policy_start_date)

# Forecast EV and PHV sales with policy impact
electric_forecast_with_policy = forecast_ev_sales_with_policy(ev_time_series, ev_policy_impact, end_date, ev_future_exog)
plugin_hybrid_forecast_with_policy = forecast_ev_sales_with_policy(plugin_time_series, phv_policy_impact, end_date, phv_future_exog)



# Define additional scenarios
scenario_a_start = '2024-01'
scenario_a_duration = 24
scenario_a_ev_impact = 0.25

scenario_a_phv_impact = 0.20

scenario_b_start = '2024-07'
scenario_b_duration = 36
scenario_b_ev_impact = 0.15
scenario_b_phv_impact = 0.10

scenario_c_start = '2025-01'
scenario_c_duration = None
scenario_c_ev_impact = 0.10
scenario_c_phv_impact = 0.05

# Create policy impact arrays for each scenario
ev_policy_impact_scenario_a, _ = create_policy_impact(ev_time_series, scenario_a_start, scenario_a_ev_impact, 0)
ev_policy_impact_scenario_b, _ = create_policy_impact(ev_time_series, scenario_b_start, scenario_b_ev_impact, 0)
ev_policy_impact_scenario_c, _ = create_policy_impact(ev_time_series, scenario_c_start, scenario_c_ev_impact, 0)

print(ev_policy_impact_scenario_a)
print(ev_policy_impact_scenario_b)

_, phv_policy_impact_scenario_a = create_policy_impact(plugin_time_series, scenario_a_start, 0, scenario_a_phv_impact)
_, phv_policy_impact_scenario_b = create_policy_impact(plugin_time_series, scenario_b_start, 0, scenario_b_phv_impact)
_, phv_policy_impact_scenario_c = create_policy_impact(plugin_time_series, scenario_c_start, 0, scenario_c_phv_impact)

# Create the future exog arrays with the correct size for each scenario
ev_future_exog_scenario_a = create_future_exog(start_period, end_period, ev_policy_impact_scenario_a[-1], scenario_a_start)
ev_future_exog_scenario_b = create_future_exog(start_period, end_period, ev_policy_impact_scenario_b[-1], scenario_b_start)
ev_future_exog_scenario_c = create_future_exog(start_period, end_period, ev_policy_impact_scenario_c[-1], scenario_c_start)

phv_future_exog_scenario_a = create_future_exog(start_period, end_period, phv_policy_impact_scenario_a[-1], scenario_a_start)
phv_future_exog_scenario_b = create_future_exog(start_period, end_period, phv_policy_impact_scenario_b[-1], scenario_b_start)
phv_future_exog_scenario_c = create_future_exog(start_period, end_period, phv_policy_impact_scenario_c[-1], scenario_c_start)

# Calculate forecasts for each scenario separately
electric_forecast_scenario_a = forecast_ev_sales_with_policy(ev_time_series, ev_policy_impact_scenario_a, end_date, ev_future_exog_scenario_a)
electric_forecast_scenario_b = forecast_ev_sales_with_policy(ev_time_series, ev_policy_impact_scenario_b, end_date, ev_future_exog_scenario_b)
electric_forecast_scenario_c = forecast_ev_sales_with_policy(ev_time_series, ev_policy_impact_scenario_c, end_date, ev_future_exog_scenario_c)

plugin_hybrid_forecast_scenario_a = forecast_ev_sales_with_policy(plugin_time_series, phv_policy_impact_scenario_a, end_date, phv_future_exog_scenario_a)
plugin_hybrid_forecast_scenario_b = forecast_ev_sales_with_policy(plugin_time_series, phv_policy_impact_scenario_b, end_date, phv_future_exog_scenario_b)
plugin_hybrid_forecast_scenario_c = forecast_ev_sales_with_policy(plugin_time_series, phv_policy_impact_scenario_c, end_date, phv_future_exog_scenario_c)

# Print forecasts for each scenario
print("Electric Forecast for Scenario A:")
print(electric_forecast_scenario_a)

print("\nPlug-in Hybrid Forecast for Scenario A:")
print(electric_forecast_scenario_b)

print("\nElectric Forecast for Scenario B:")
print(electric_forecast_scenario_c)

In [ ]:
electric_forecast_scenario_a

In [ ]:
# Combine the baseline and three scenarios into one DataFrame
combined_forecasts = pd.DataFrame({
    'scenario_a': electric_forecast_scenario_a,
    'scenario_b': electric_forecast_scenario_b,
    'scenario_c': electric_forecast_scenario_c
})

# Reset the index
combined_forecasts.reset_index(inplace=True)

# Create separate columns for year and month
combined_forecasts['year'] = combined_forecasts['index'].dt.year
combined_forecasts['month'] = combined_forecasts['index'].dt.month

# Drop the original 'index' column
combined_forecasts.drop('index', axis=1, inplace=True)

# Display the combined DataFrame
combined_forecasts

In [ ]:
# Save Electric Only DataFrame to a CSV file
combined_forecast_df.to_csv(os.path.join(output_directory, 'combined_forecast_df.csv'), index=False)

#### Import MVA vehicle registration by county
These figures represent the total number of vehicles registered in each county as of the end of each fiscal year.

In [ ]:
# MVA Vehicle Registration Counts Summarized by County for FY 2010 to FY 2022. Counts are total number of registrations 'as of' the end of each year.
path = 'https://opendata.maryland.gov/resource/kqkd-4fx8.csv'

ev_ye_reg = pd.read_csv(path)
ev_ye_reg.set_index('fiscal_year', inplace = True)
ev_ye_reg = ev_ye_reg.transpose()
ev_ye_reg = ev_ye_reg.reset_index()
ev_ye_reg.columns.name = None
ev_ye_reg.rename(columns = {'index':'County'}, inplace = True)
ev_ye_reg.head()

In [ ]:
# Filter the DataFrame for December 2022
december_2022_df = ev_reg_county[(ev_reg_county['year'] == '2022') & (ev_reg_county['month'] == '12')]

# Group by county and fuel_category, then sum the count
grouped_df = december_2022_df.groupby(['county', 'fuel_category']).agg({'count': 'sum'}).reset_index()

# Pivot the DataFrame to show fuel categories as columns
pivoted_df = grouped_df.pivot_table(index='county', columns='fuel_category', values='count', fill_value=0).reset_index()

# Calculate the total count for each county
pivoted_df['count'] = pivoted_df['Electric'] + pivoted_df['Plug-In Hybrid']

# Rename the index to 'county'
pivoted_df.index.name = 'county'

# Display the result
pivoted_df.head()

## U.S. EV Infrastructure Market

### EV Infrastructure Chargers Added by Year

In [ ]:
ev_data_us = ev_data

# Convert the 'Open Date' column to datetime format
ev_data_us['Open Date'] = pd.to_datetime(ev_data_us['Open Date'])

# Extract the year from the 'Open Date' column and create a new column called 'Open Year'
ev_data_us['Open Year'] = ev_data_us['Open Date'].dt.year

# Filter the data to only include "Public" access type
ev_data_us = ev_data_us[ev_data_us['Access Type'] == 'public']

# Define the charger categories
charger_categories = ['Level 1', 'Level 2', 'DC Fast']

# Prepare a dictionary to store the DataFrames for each category
output_dataframes = {}

# Determine the range of years to include
min_year = int(ev_data_us['Open Year'].min())
max_year = int(ev_data_us['Open Year'].max())

# Create an empty DataFrame to store the total chargers added from all three categories
total_chargers_df = pd.DataFrame(index=range(min_year, max_year + 1)).fillna(0)

# Loop through each charger category and create a chart for that category
for category in charger_categories:
    # Filter the data to only include the current charger category
    ev_data_us_cat = ev_data_us[ev_data_us[category + ' Chargers Count'] > 0]

    # Group the data by year and sum the charger counts
    cols_to_sum = [category + ' Chargers Count']
    ev_data_us_summed = ev_data_us_cat.groupby(['Open Year']).sum()[cols_to_sum]

    # Fill in missing years with zero counts
    ev_data_us_summed = ev_data_us_summed.reindex(range(min_year, max_year + 1), fill_value=0)

    # Update the total chargers DataFrame
    total_chargers_df[category] = ev_data_us_summed[cols_to_sum[0]]

    # Save the DataFrame to the dictionary
    output_dataframes[category] = ev_data_us_summed

    # Calculate the CAGR for the charger type
    if ev_data_us_summed.shape[0] >= 2:
        cagr = (ev_data_us_summed.iloc[-1] / ev_data_us_summed.iloc[0])**(1/(ev_data_us_summed.shape[0]-1)) - 1
    else:
        cagr = [0]

    # Create a bar chart for the current charger category
    fig, ax = plt.subplots()
    ev_data_us_summed.plot(kind='bar', ax=ax)
    ax.set_title('Total ' + category + ' chargers by year')
    ax.set_xlabel('Year')
    ax.set_ylabel('Total chargers')

    # Set the lower limit of the y-axis to 0
    ax.set_ylim(bottom=0)

    # Add a trendline to the bar chart
    x = ev_data_us_summed.index
    y = ev_data_us_summed[cols_to_sum[0]]
    if ev_data_us_summed.shape[0] >= 2:
        z = np.polyfit(x, y, 1)
        p = np.poly1d(z)
        ax.plot(x, p(x), linestyle='--', linewidth=2, color='red', label='CAGR: ' + '{:.1%}'.format(cagr[0]))
    else:
        ax.plot(x, y, linestyle='--', linewidth=2, color='red', label='CAGR: N/A')

# Display the chart and legend
ax.legend()
plt.show()

# Create a bar chart for the total chargers added from all three categories together
fig, ax = plt.subplots()
total_chargers_df.plot(kind='bar', stacked=True, ax=ax)
ax.set_title('Total chargers by year (all categories)')
ax.set_xlabel('Year')
ax.set_ylabel('Total chargers')
plt.show()

# Save the total chargers DataFrame to the dictionary
output_dataframes['Total'] = total_chargers_df

# Access the DataFrame output variables for each charger category
level_1_df = output_dataframes['Level 1']
level_2_df = output_dataframes['Level 2']
dc_fast_df = output_dataframes['DC Fast']
total_df = output_dataframes['Total']

### EV Infrastructure Chargers Cumulative by Year

In [ ]:
ev_data_us = ev_data

# Convert the 'Open Date' column to datetime format
ev_data_us['Open Date'] = pd.to_datetime(ev_data_us['Open Date'])

# Extract the year from the 'Open Date' column and create a new column called 'Open Year'
ev_data_us['Open Year'] = ev_data_us['Open Date'].dt.year

# Filter the data to only include "Public" access type
ev_data_us = ev_data_us[ev_data_us['Access Type'] == 'public']

# Define the charger categories
charger_categories = ['Level 1', 'Level 2', 'DC Fast']

# Prepare a dictionary to store the DataFrames for each category
output_dataframes = {}

# Determine the range of years to include
min_year = int(ev_data_us['Open Year'].min())
max_year = int(ev_data_us['Open Year'].max())

# Create an empty DataFrame to store the total chargers added from all three categories
total_chargers_df = pd.DataFrame(index=range(min_year, max_year + 1)).fillna(0)

# Loop through each charger category and create a chart for that category
for category in charger_categories:
    # Filter the data to only include the current charger category
    ev_data_us_cat = ev_data_us[ev_data_us[category + ' Chargers Count'] > 0]

    # Group the data by year and sum the charger counts
    cols_to_sum = [category + ' Chargers Count']
    ev_data_us_summed = ev_data_us_cat.groupby(['Open Year']).sum()[cols_to_sum]

    # Fill in missing years with zero counts
    ev_data_us_summed = ev_data_us_summed.reindex(range(min_year, max_year + 1), fill_value=0)

    # Update the total chargers DataFrame
    total_chargers_df[category] = ev_data_us_summed[cols_to_sum[0]]

    # Save the DataFrame to the dictionary
    output_dataframes[category] = ev_data_us_summed

    # Calculate the cumulative sum for the current charger category
    ev_data_us_cumulative = ev_data_us_summed.cumsum()

    # Save the DataFrame to the dictionary
    output_dataframes[category + '_cumulative'] = ev_data_us_cumulative

    # Create a bar chart for the cumulative chargers
    fig, ax = plt.subplots()
    ev_data_us_cumulative.plot(kind='bar', ax=ax)
    ax.set_title('Cumulative ' + category + ' chargers by year')
    ax.set_xlabel('Year')
    ax.set_ylabel('Total chargers')

    # Set the lower limit of the y-axis to 0
    ax.set_ylim(bottom=0)

    plt.show()

# Calculate the cumulative sum for the total chargers from all categories
total_chargers_cumulative = total_chargers_df.cumsum()

# Create a bar chart for the cumulative total chargers (all categories)
fig, ax = plt.subplots()
total_chargers_cumulative.plot(kind='bar', stacked=True, ax=ax)
ax.set_title('Cumulative chargers by year (all categories)')
ax.set_xlabel('Year')
ax.set_ylabel('Total chargers')

# Set the lower limit of the y-axis to 0
ax.set_ylim(bottom=0)

plt.show()

# Save the total chargers cumulative DataFrame to the dictionary
output_dataframes['Total_cumulative'] = total_chargers_cumulative

# Access the DataFrame output variables for each charger category
level_1_cumulative_df = output_dataframes['Level 1_cumulative']
level_2_cumulative_df = output_dataframes['Level 2_cumulative']
dc_fast_cumulative_df = output_dataframes['DC Fast_cumulative']
total_cumulative_df = output_dataframes['Total_cumulative']

#### Save Dataframe to Excel File

In [ ]:
import pandas as pd
from google.colab import files
import os
import openpyxl

# Upload the existing Excel file to Google Colab
uploaded = files.upload()
existing_excel_file_name = list(uploaded.keys())[0]

# Load the existing Excel file with 'read_only=False'
book = openpyxl.load_workbook(existing_excel_file_name, read_only=False)

# Create an ExcelWriter object to save the updated Excel file
with pd.ExcelWriter(existing_excel_file_name, engine='openpyxl', mode='a') as writer:
    # Set the workbook object of the ExcelWriter to the existing Excel file
    writer.book = book

    # Add the new DataFrames as new sheets to the updated Excel file
    level_1_cumulative_df.to_excel(writer, sheet_name='Level 1 Cumulative', index=True)
    level_2_cumulative_df.to_excel(writer, sheet_name='Level 2 Cumulative', index=True)
    dc_fast_cumulative_df.to_excel(writer, sheet_name='DC Fast Cumulative', index=True)
    total_cumulative_df.to_excel(writer, sheet_name='Total Cumulative', index=True)

    # Save the updated Excel file
    writer.save()

# Download the updated Excel file to your computer
files.download(existing_excel_file_name)

# Remove the Excel file from the Google Colab environment
os.remove(existing_excel_file_name)